### ISSUE TITLE
用户代码如果有ThreadPool的子类且覆盖了execute、submit等方法，则在覆盖方法中补上插入MTC的逻辑

### ISSUE THREAD

**Issue by oldratlee** [alibaba/transmittable-thread-local#11]
以解决MTC可能失效的问题

**Comment by Qsimple** [comment]
【以解决MTC可能失效的问题】对于这个issue我有些不太明白，我看了看代码，[ExecutorTtlWrapper.java](https://github.com/alibaba/transmittable-thread-local/blob/master/src/main/java/com/alibaba/ttl/threadpool/ExecutorTtlWrapper.java)通过代理的方式包装了一个Executor，再重写了execute方法将command装饰成TtlRunnable，这个时候即使有用户继承了ThreadPool的子类，只有装饰成ExecutorTtlWrapper，MTC(我理解与TTL同意吧)应该是可以生效的吧。

**Comment by oldratlee** [comment]
@Qsimple 你说得对，我当时应该是没想明白，#2 也close了。
