### ISSUE TITLE
在某些多线程切换的情况中不需要TTL拷贝ThreadLocal

### ISSUE THREAD

**Issue by baifan** [alibaba/transmittable-thread-local#110]
场景：全链路监控异步发送统计信息

为了隔离发送监控数据对业务的影响，所有的业务数据都是使用线程池异步发送的。
这时候提交任务会copy链路信息，copy链路信息会产生很多无用的对象。
是否可以考虑，对线程池或者Runnable\Callable增加开关机制，防止这种多余的操作。

**Comment by oldratlee** [comment]
@baifan 你可以通过 设计规划不同命名空间，来区分出不同的用途，这样就不会出现『产生很多无用的对象』，只用 你 要空间/用途 的对象。

# 展开说明如下：

`TTL`，提供的是一个通道，来传递数据，并不感知在上面业务使用上业务哪些是需要或不需要的。

换句话说，业务可以通过不同`TTL`实例 来规划区分出不同的用途，对应你的场景：

1. 『业务数据』
1. 『线程池异步发送』操作中 关心的 值 copy链路信息

实际可以有的使用方式：

1. 显式不同的`TTL`实例，来表示不同传递值的用途。如 『copy链路信息』的传递值（`TTL`值）只是『线程池异步发送』关心『链路信息』（可以只是『监控』系统级值，非业务）
2. 另一个思想其实一样的做法是：用一个`TTL`实例，但`TTL`中值是个Map，用不同`Key`来区分用途。

**Comment by baifan** [comment]
@oldratlee 感谢详细耐心的解答。
可能我没有表述清楚我的场景，我们场景中的隔离不是业务数据的隔离，是监控发送行为和业务行为的隔离。
简单的来说，就是同一个JVM中，大部分的业务线程切换的时候`TransmittableThreadLocal`机制都生效，但在某个指定线程池提交Runnable的时候，不希望进行`TransmittableThreadLocal#copy`这个操作，因为这个操作，对即将执行Runnable没有意义，而且因为copy中clone了部分对象，如果执行了`TransmittableThreadLocal#copy`，还会在内存中新增一些对象和增加一些耗时。我想避免这次inherit。

看了一下TTL的机制，只有重写一个新的ThreadPool才能解决这个问题，觉得有点重。
是否可以改为新建两个`class`:
```java
public interface TtlNoWrapCallable<V> extends Callable<V> {
}
```

```java
public interface TtlNoWrapRunnable extends Runnable {
}
```

这里修改了接口的返回类型，增加`TtlNoWrapCallable`的逻辑。
```java
 public static <T> Callable<T> get(Callable<T> callable, boolean releaseTtlValueReferenceAfterCall, boolean idempotent) {
        if (null == callable) {
            return null;
        }
        if (callable instanceof TtlNoWrapCallable) {
            return callable;
        }

        if (callable instanceof TtlCallable) {
            if (idempotent) {
                // avoid redundant decoration, and ensure idempotency
                return callable;
            } else {
                throw new IllegalStateException("Already TtlCallable!");
            }
        }
        return new TtlCallable<T>(callable, releaseTtlValueReferenceAfterCall);
    }
```

**Comment by oldratlee** [comment]
> 大部分的业务线程切换的时候TransmittableThreadLocal机制都生效，但在某个指定线程池提交Runnable的时候，不希望进行TransmittableThreadLocal#copy这个操作，

能具体些说明 上面『大部分』、『某个线程池不希望』的场景和后面的原因吗？ @baifan ❤️
方便我理解场景和思考解决方法。

**Comment by baifan** [comment]
大致情况是这样的，全链路监控需要知道上下文，所以使用TTL保存了一个Trace对象，保证Trace对象在线程池提交任务的时候，也能够传递，由于线程安全机制，需要对Trace进行一次深拷贝`Trace#clone()`，这方法会产生一些新的对象，是正常业务的需要。但一个Trace监控结束后，需要发送统计信息给服务端，为了发送统计信息不影响正常业务，使用线程池发送给后端的统计服务，由于使用线程池&TTL，根据TTL的机制会调用一次深拷贝`Trace#clone()`，我的需求是规避这次深拷贝。

```java

private ThreadPoolExecutor executor;

executor.execute((TtlNoWrapRunnable) () -> {
    for (Sender sender : senders) {
        sender.send(trace);
    }
});
```

**Comment by oldratlee** [comment]
> 由于线程安全机制，需要对Trace进行一次深拷贝`Trace#clone()`，这方法会产生一些新的对象，是正常业务的需要。

第一感觉是 每次传递做`Trace#clone()`，这个做法有些重了。原因是：

- `Trace`对象属于一个线程（`ThreadLocal`语义）
- 要保证这点，
    - 在传递时就做`Trace#clone()`是一种方案/做法，有些重了。
        - 传递时就做，如此之早了，以至于这样一个方案，要让你倒过来在流程上调整优化。
        - `Java`的`clone`本身就比较重，几乎没人用。
    - 另一种做法是，`Trace`类要实现成修改时，再拷贝（即`Copy on Write/COW`）。
这种做法本身就更精细（内存/计算得使用各种场景下都更优），自然也没有你现在的问题。

**Comment by baifan** [comment]
`Trace#clone`是我们自己封装的方法。
`COW`是一个很棒的策略。
受教了，非常感谢~

**Comment by oldratlee** [comment]
好的，我先把这个`issue` Close了。

后续有问题，也欢迎讨论 ❤️

**Comment by oldratlee** [comment]
@baifan 

第一感觉是：

`Copy On Write/COW`是在`write`时来触发，在`get`（读`TTL value`）在判断处理的时间已经不对了。

**Comment by baifan** [comment]
@oldratlee 
非常感谢，使用warp的方法包装了两个属性，减少了不必要的copy动作。:thumbsup::thumbsup::thumbsup:
