### ISSUE TITLE
TransmittableThreadLocal的传递只有浅拷贝吗？

### ISSUE THREAD

**Issue by Ronustine** [alibaba/transmittable-thread-local#111]
Hello，做项目是遇到一个问题：用线程池去执行一个执行时间较长的任务，但是任务线程需要父线程的ThreadLoacl。而TransmittableThreadLocal传递似乎只是传递了引用，并不是深拷贝。
这样会引起一个问题，父线程ThreadLoacl如果置空或者值有修改的情况下，任务线程也会随之改变。我觉得在任务提交后，值不应该有变动吧？
请问能否控制拷贝方式呢？
不好意思，第一次提问，请多包涵哈，若能帮忙解惑，不胜感激~

**Comment by oldratlee** [comment]
值传递拷贝方式通过`copy`方法来定制，缺省是直接传的是引用。

更多参见[User Guide文档](https://github.com/alibaba/transmittable-thread-local#-user-guide)说明：

![image](https://user-images.githubusercontent.com/1063891/45217065-4f1ed900-b2d5-11e8-932c-9464fdd0d0d6.png)

### PS：『引用传递』并不是 『浅拷贝』

**Comment by SZMOFEI** [comment]
niubi
