### ISSUE TITLE
simplify the try-finally code gen by javassist, do not need copy method

### ISSUE THREAD

**Issue by oldratlee** [alibaba/transmittable-thread-local#115]
see official documentation: http://www.javassist.org/tutorial/tutorial2.html :

> To execute it when an exception is thrown, the second parameter asFinally to insertAfter() must be true.
>
> If an exception is thrown, the compiled code inserted by insertAfter() is executed as a finally clause. The value of $_ is 0 or null in the compiled code. After the execution of the compiled code terminates, the exception originally thrown is re-thrown to the caller. Note that the value of $_ is never thrown to the caller; it is rather discarded.

Of course, need  new unit test to confirm this `javassist` behave.

@wuwen5 please re-check when you're convenient. ❤️

**Comment by wuwen5** [comment]
At first I use this way, But I have met some problems in testing.
like this: https://issues.jboss.org/browse/JASSIST-232?_sscc=t

**Comment by oldratlee** [comment]
@wuwen5  You are so right! 👍

--------------

add unit test to confirm this javassist insertAfter behave 

- insertAfter() can execute as a finally clause
- but fail to cooperate with add local var
