### ISSUE TITLE
如何子线程向父线程传递值？

### ISSUE THREAD

**Issue by zongchangbo** [alibaba/transmittable-thread-local#125]
目前发现的都是主线程到子线程的 值传递；
那从子线程到主线程的 却不能实现，这个有办法解决吗？

**Comment by oldratlee** [comment]
> 目前发现的都是主线程到子线程的 值传递；
> 那从子线程到主线程的 却不能实现

## 首先

任何支持多线程的环境都 支持 从不同线程之前 『传递』（或说共享）状态。 @zongchangbo 
\# 共享状态（引用） 注意同步 即可，即 平时 大家说的 并发编程。

## 然后

`transmittable-thread-local`提供的是 一个 典型场景下的规范化/模式化的解法，进而 简化 使用、实现和系统设计。

参见文档：

- https://github.com/alibaba/transmittable-thread-local#-%E5%8A%9F%E8%83%BD
> `JDK`的[`InheritableThreadLocal`](https://docs.oracle.com/javase/10/docs/api/java/lang/InheritableThreadLocal.html)类可以完成父线程到子线程的值传递。但对于使用线程池等会池化复用线程的组件的情况，线程由线程池创建好，并且线程是池化起来反复使用的；这时父子线程关系的`ThreadLocal`值传递已经没有意义，应用需要的实际上是把 **任务提交给线程池时**的`ThreadLocal`值传递到 **任务执行时**。
- 🎨 需求场景
https://github.com/alibaba/transmittable-thread-local/blob/master/docs/requirement-scenario.md

## 更多讨论参见

- 子线程池中复用的线程无法随父线程池中的线程的更新而更新
https://github.com/alibaba/transmittable-thread-local/issues/117#issuecomment-432169173
- Session级Cache场景下，TransmittableThreadLocal的使用问题
https://github.com/alibaba/transmittable-thread-local/issues/122#issuecomment-442728409

**Comment by zongchangbo** [comment]
嗯  谢谢啊，TTL缺省向子线程传递的是引用， 而我之前用的是String  这种弱引用类型 ，所以失败了

**Comment by oldratlee** [comment]
COOL 解决了就好 ❤️

## PS 关于`String`类型

> 之前用的是`String`这种弱引用类型 ，所以失败了

更准确地说，

- `String`是实现成`Immutable`的，即不能修改，即父线程不可能看到子线程变更。
- `String`类型的变量，如果你没有做了专门的处理（如使用`WeakHashMap `/`WeakReference `之类的），本身`String`变量是强引用 非弱引用。

**Comment by zongchangbo** [comment]
下面的这个demo是可以的：
public class CustomThreadLocal {
    static TransmittableThreadLocal<String> threadLocal = new TransmittableThreadLocal<>();
    public static void main(String[] args) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                CustomThreadLocal.threadLocal.set("test: " + new Random(10).nextInt());
                new Service().call();
            }
        }).start();
    }
}

class Service {
    public void call() {
        //System.out.println("Service:" + Thread.currentThread().getName());
        System.out.println("Service:" + CustomThreadLocal.threadLocal.get());
        new Dao().call();
    }
}

class Dao {
    public void call() {
        System.out.println("==========================");
       // System.out.println("Dao:" + Thread.currentThread().getName());
        System.out.println("Dao:" + CustomThreadLocal.threadLocal.get());
    }
}

但是我实际工作中的不行
@Slf4j
public class PrometheusMetricsInterceptor extends HandlerInterceptorAdapter {

    static final Counter requestCounter = Counter.build()
            .name("cuishoufen_http_requests_total").labelNames("path", "method", "code")
            .help("Total requests.").register();

    public static final TransmittableThreadLocal<String> localStatus = new TransmittableThreadLocal<String>();

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) throws Exception {
        String requestURI = request.getRequestURI();
        String method = request.getMethod();
        int status = response.getStatus();
        requestCounter.labels(requestURI, method, localStatus.get() == null ? String.valueOf(status): localStatus.get()).inc();
        localStatus.remove();
        super.afterCompletion(request, response, handler, ex);
    }
}



@Override
    @HystrixCommand(fallbackMethod = "getCuishouTag_fallback",
            groupKey = "getCuishouTag", commandKey = "getCuishouTag", threadPoolKey = "getCuishouTag", commandProperties = {
            //设置调用者等待命令执行的超时限制，超过此时间，HystrixCommand被标记为TIMEOUT，并执行回退逻辑
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "3000"),
            @HystrixProperty(name = "fallback.isolation.semaphore.maxConcurrentRequests", value = "200"),
            //设置在一个滚动窗口中，打开断路器的最少请求数
            @HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "4"),
            //设置在回路被打开，拒绝请求到再次尝试请求并决定回路是否继续打开的时间
            @HystrixProperty(name = "circuitBreaker.sleepWindowInMilliseconds", value = "60000"),
            //设置统计的滚动窗口的时间段大小。该属性是线程池保持指标时间长短
            @HystrixProperty(name = "metrics.rollingStats.timeInMilliseconds", value = "180000") }, threadPoolProperties = {
            @HystrixProperty(name = "coreSize", value = "30"),
            @HystrixProperty(name = "maxQueueSize", value = "200"),
            //设置队列拒绝的阈值——一个人为设置的拒绝访问的最大队列值，即使maxQueueSize还没有达到
            @HystrixProperty(name = "queueSizeRejectionThreshold", value = "50"),
            //设置统计的滚动窗口的时间段大小。该属性是线程池保持指标时间长短
            @HystrixProperty(name = "metrics.rollingStats.timeInMilliseconds", value = "180000")
    })
    public HashMap<String, String> getCuishouTag(String tel) {
        HashMap<String,String> hm = new HashMap<String,String>();
        try {
            String param = buildParam(tel);
            String response = getResponse(URL_2, param);
            if (StringUtils.isNotBlank(response)) {
                hm = parseResponse(response);
            }
        }catch (Exception e){
           PrometheusMetricsInterceptor.localStatus.set("9999")
            log.error("getCuishouTag process error, tel={}", tel, e);
            return hm;
        }
        return hm;
    }

**Comment by zongchangbo** [comment]
然后我的解决方案就是把String  换成一个对象，请问为何会发生这样的事情？

**Comment by oldratlee** [comment]
@zongchangbo 

因为 涉及 `HandlerInterceptorAdapter`/`HystrixCommand` ，要具体分析这些涉及框架的 整体流程 与 代码实现。

这些 框架 我没有具体用过，所以 你要自己去分析一下了。 😄

**Comment by weiliguo15634145** [comment]
> 目前发现的都是主线程到子线程的 值传递； 那从子线程到主线程的 却不能实现，这个有办法解决吗？

解决了吗？ 我现在也遇到了同样的问题。我有一个需求是收集所有子线程的执行日志然后到父线程汇总 。

**Comment by zongchangbo** [comment]
微信说吧，809116583




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/transmittable-thread-local"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/transmittable-thread-local] 如何子线程向父线程传递值？ (#125)





  
目前发现的都是主线程到子线程的 值传递； 那从子线程到主线程的 却不能实现，这个有办法解决吗？
  
解决了吗？ 我现在也遇到了同样的问题。我有一个需求是收集所有子线程的执行日志然后到父线程汇总 。
