### ISSUE TITLE
关于实现：在TtlRunnable.get(task)初始化中完成TTL的值抓取，即TtlRunnable.get初始之后的TTL值不会被传递

### ISSUE THREAD

**Issue by LQZYC** [alibaba/transmittable-thread-local#127]
```java
import com.alibaba.ttl.TransmittableThreadLocal;
import com.alibaba.ttl.TtlRunnable;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

class Scratch {
    public static void main(String[] args) {

        TransmittableThreadLocal<String> parent0 = new TransmittableThreadLocal<String>();
        TransmittableThreadLocal<String> parent1 = new TransmittableThreadLocal<String>();
        parent0.set("parent0");

        Runnable task = () -> {
            System.out.println(parent0.get());
            System.out.println(parent1.get());
        };
        Runnable ttlRunnable = TtlRunnable.get(task);
        parent1.set("parent1");

        ExecutorService executorService = Executors.newFixedThreadPool(8);
        executorService.submit(ttlRunnable);

        executorService.shutdown();
    }
}
```

以上代码输出为

```
parent0
null
```

----------------------

无法获取到parent1对象在父线程设置的值。

代码如果`parent1.set("parent1")`在`Runnable ttlRunnable = TtlRunnable.get(task)`初始化之前设置才可以看到。

**Comment by LQZYC** [comment]
看了下代码是这里删除了 
com.alibaba.ttl.TransmittableThreadLocal.Transmitter#replay

// clear the TTL values that is not in captured
                // avoid the extra TTL values after replay when run task
                if (!capturedMap.containsKey(threadLocal)) {
                    iterator.remove();
                    threadLocal.superRemove();
                }

是专门设计的吗？只能捕获TtlRunnable创建前父线程中设置的上下文？

**Comment by oldratlee** [comment]
> 无法获取到parent1对象在父线程设置的值。
>
> 代码如果`parent1.set("parent1")`在`Runnable ttlRunnable = TtlRunnable.get(task)`初始化之前设置才可以看到。

@LQZYC 是这样。

抓取 **父操作的`TTL`的值** 发生在 **`TtlRunnable.get`**，即在这个操作之后不会影响。

> 是专门设计的吗？只能捕获TtlRunnable创建前父线程中设置的上下文？

是的专门设计。这样整个流程 固定明确，可以方便分析推理。

关于 『捕获`TtlRunnable`创建前父线程中设置的上下文』这个问题，展开 还涉及值/引用，不是一句话。如果上面说的理解有些困难，可以先看一下关于`TTL`的Issue：

## 讨论和使用注意参见

- 关于 父子传递
  - 子线程池中复用的线程无法随父线程池中的线程的更新而更新
https://github.com/alibaba/transmittable-thread-local/issues/117#issuecomment-432169173
  - Session级Cache场景下，TransmittableThreadLocal的使用问题
https://github.com/alibaba/transmittable-thread-local/issues/122#issuecomment-442728409
- 更多讨论参见 Issue中`question` Tag:
https://github.com/alibaba/transmittable-thread-local/issues?utf8=%E2%9C%93&q=label%3Aquestion

**Comment by oldratlee** [comment]
这样的设计，可以 解决 复杂&典型的场景，并简化分析和使用。

你可以 说一下你的场景？
有碰到 什么 你不能解决的场景 或问题吗？ @LQZYC
