### ISSUE TITLE
这个库带来怎样的好处和优势？

### ISSUE THREAD

**Issue by wilddylan** [alibaba/transmittable-thread-local#128]

**Comment by oldratlee** [comment]
> 这个库 到底能带来怎样的好处和优势

当要说一个方案『好处』和『优势』时，要说明的是 『 **_解决一个问题_** 的 **_另一其它方案_** 的 **_对比_**』 :) @wilddylan ，即 涉及3部分： 1) 解决的问题 ，2) 其它解决方案 和 3) 对比。

# 1. 关于 解决的问题

简单地说，『异步执行上下文的传递』。

更多可以看文档中的说明：[功能](https://github.com/alibaba/transmittable-thread-local#-%E5%8A%9F%E8%83%BD) 和 [需求场景](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/requirement-scenario.md)。

# 2. 其它解决方案

解决『异步执行上下文的传递』，手动的直接方案是下面的示例代码。

```java
import java.util.HashMap;
import java.util.Map;

public class Demo {


    public static void main(String[] args) {
        // 得到当前上下文
        final Map<String, String> context_value = getContext();

        // 捕捉上下文
        Map<String, String> context_copy = new HashMap<>(context_value);
        Runnable asyncLogic = () -> {
            // 在异步执行逻辑中，使用上下文 
            System.out.println(context_copy);
        };
        new Thread(asyncLogic).start();
    }

    private static Map<String, String> getContext() {
        return context.get();
    }

    // 使用 ThreadLocal：
    //   - 可以 不同的线程（如执行不同的请求用户的处理） 有自己的Context。
    //   - 避免 Context 总是通过 函数参数 传递，中间路过的业务的逻辑 都关注/感知 框架的上下文
    private static ThreadLocal<Map<String, String>> context = ThreadLocal.withInitial(HashMap::new);
}
```

## 这样的做法 的问题

### 业务实现逻辑 角度来看

- 业务逻辑自己 要知道 哪些上下文，并 一个一个去 捕捉。
- 直接依赖 不同 上下文 逻辑/类（比如 RPC的上下文、不同业务模块中要异步执行的上下文）
- 要事先知道 哪些 要异步执行的上下文，如果有 新异步执行的上下文 出现了，要添加 几行代码。
   这样 增加的事，对于业务来说，操作困难 可能遗漏，就是线上 故障了。

### 从异步执行方式来看

上面

# 对比

**Comment by wilddylan** [comment]
很棒唉 ~ 嘿嘿，为你点赞，快给我一个你加密的工号，我去给你点赞！

**Comment by oldratlee** [comment]
> 很棒唉 ~ 嘿嘿，为你点赞，快给我一个你加密的工号，我去给你点赞！

噗～ 直接用我的id `oldratlee` 在内网就查到我了。
我的名字 & 花名 都直接在我的`github`主页上： https://github.com/oldratlee 。 

PS： 这个`Issue`不用关了，方便 其它人可以看到 ❤️ @wilddylan

**Comment by yinjihuan** [comment]
直接使用TransmittableThreadLocal就可以跨线程池传递了，想请教下修饰线程或者线程池的作用是什么？我测下来，不修饰也是可以的

**Comment by oldratlee** [comment]
`TransmittableThreadLocal`有3种使用方式，参见文档：

1. [修饰`Runnable`和`Callable`](https://github.com/alibaba/transmittable-thread-local/#21-%E4%BF%AE%E9%A5%B0runnable%E5%92%8Ccallable)
2. [修饰线程池](https://github.com/alibaba/transmittable-thread-local/#22-%E4%BF%AE%E9%A5%B0%E7%BA%BF%E7%A8%8B%E6%B1%A0)
3. [使用`Java Agent`来修饰`JDK`线程池实现类](https://github.com/alibaba/transmittable-thread-local/#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB)

可以认为后一种是前一种的对用户使用的简化。第3种『修饰线程或者线程池』的效果是『可以做到应用代码 **无侵入**』。具体请参见上面的文档说明。 @wilddylan

**Comment by yinjihuan** [comment]
> 直接使用TransmittableThreadLocal就可以跨线程池传递了，想请教下修饰线程或者线程池的作用是什么？我测下来，不修饰也是可以的

我是想问这个问题，是不是可以不用配合上面的三种方式，直接使用TransmittableThreadLocal就可以了@oldratlee

**Comment by oldratlee** [comment]
> 是不是可以不用配合上面的三种方式，直接使用TransmittableThreadLocal就可以了

不行的。

> 直接使用TransmittableThreadLocal就可以跨线程池传递了，想请教下修饰线程或者线程池的作用是什么？我测下来，不修饰也是可以的

你的测试Case不全，不典型。 

『不全，不典型』的验证方法，比如： @yinjihuan 
把你的测试Case换成 `ThreadLocal`，是不是 也是通过。

**Comment by shenjianeng** [comment]
看到这个issues的标题，想好奇的问一句，除了好处和优势之外，系统引入这个框架的成本是什么

**Comment by oldratlee** [comment]
欢迎大家继续讨论 ❤️

**Comment by shenjianeng** [comment]
这是来自邮箱的自动回复邮件，我已收到邮件。-------------------------------------------------
