### ISSUE TITLE
为什么test里面的代码都是kotlin写的

### ISSUE THREAD

**Issue by shengchaojie** [alibaba/transmittable-thread-local#129]

**Comment by oldratlee** [comment]
测试代码使用`Kotlin`，是因为`Kotlin`更现代化写起来更方便。

了解`Kotlin`，可以看看[个人整理的书单](https://www.douban.com/doulist/67457911/)。

--------------

另一个对应的问题是『为什么生产代码不使用`Kotlin`？』

原因是 减少`TTL`库的依赖。作为一个底层基础库，期望 0依赖。
