### ISSUE TITLE
请教个问题：TransmittableThreadLocal中的holder为什么不使用ThreadLocal

### ISSUE THREAD

**Issue by yearyeardiff** [alibaba/transmittable-thread-local#132]
我对holder的理解是：保存当前线程所有的threadlocal用于在`TtlRunnable.get(task)`生成快照。个人觉得没有必要从使用InheritableThreadLocal类型的holder从父线程中继承，完全可以从生成的快照中恢复到holder中

**Comment by yearyeardiff** [comment]
还有个问题：
![image](https://user-images.githubusercontent.com/10304305/54997905-cd3f9480-5007-11e9-9c8a-117deb7a53db.png)
从这段代码中可以看出，task所在线程每次使用的threadlocal都是从`captured`,和此时线程holder中的threadlocal没有关系，如果没有关系，那为什么还要备份和恢复呢？这样不会有内存泄漏吗？

**Comment by oldratlee** [comment]
> TransmittableThreadLocal中的holder为什么不使用ThreadLocal
>
> 我对holder的理解是：保存当前线程所有的threadlocal用于在TtlRunnable.get(task)生成快照。
> 个人觉得没有必要从使用InheritableThreadLocal类型的holder从父线程中继承，
> 可以从生成的快照中恢复到holder中


对应的测试Case如下：
\# 不具体解释，整体流程说明起来复杂，如果你有兴趣可以理解梳理出来。

期望输出 `hello hello`。
如果`holder`使用`ThreadLocal`，输出的是`hello null`。


```java
import com.alibaba.ttl.TransmittableThreadLocal;
import com.alibaba.ttl.TtlRunnable;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Demo {
    public static void main(String[] args) throws Exception {
        final ExecutorService executorService = Executors.newSingleThreadExecutor();
        final TransmittableThreadLocal<String> ttl = new TransmittableThreadLocal<>();
        ttl.set("hello");

        executorService.submit(TtlRunnable.get(() -> System.out.println(ttl.get())));
        Thread.sleep(200);

        new Thread(
                () -> {
                    // 在new线程中，执行线程池操作
                    final TtlRunnable task = TtlRunnable.get(() -> System.out.println(ttl.get()));
                    executorService.submit(task);
                }
        ).start();
    }
}
```

------------------

这点 提过Bug 并修复，具体 参见 Issue #70 嵌入Thread调用的bug

**Comment by oldratlee** [comment]
> 从这段代码中可以看出，
> task所在线程每次使用的threadlocal都是从captured，
> 和此时线程holder中的threadlocal没有关系。
> 如果没有关系，那为什么还要备份和恢复呢？这样不会有内存泄漏吗？

-『和此时线程holder中的threadlocal没有关系』
   这个过程 和 『holder中的threadlocal』有关，具体看 `replay`方法的实现
- 不会『内存泄漏』。
  - 可以通过完整的实现逻辑 来分析确定
  - 也做过 内存的压力测试。
    更多说明 参见 [文档 - 性能测试](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/performance-test.md)，有脚本和测试运行的说明，你可以自己也试试。

**Comment by yearyeardiff** [comment]
懂了，之前的理解是因为没有考虑到下面的场景。
```java
new Thread(
                () -> {
                    // 在new线程中，执行线程池操作
                    final TtlRunnable task = TtlRunnable.get(() -> System.out.println(ttl.get()));
                    executorService.submit(task);
                }
        ).start();
```
解答很详细，感谢！

**Comment by gowherefindp** [comment]
能请教一下吗,为什么这个场景下new Thread()后 holder中没有"hello"了
