### ISSUE TITLE
agent 类增强后  netty的线程池报错

### ISSUE THREAD

**Issue by woshioosm** [alibaba/transmittable-thread-local#133]
netty的线程池 默认使用的是 MemoryAwareThreadPoolExecutor  该Executor中定义了 自己的runnable实现MemoryAwareRunnable。
使用ttl增强后报错：

```java
java.lang.ClassCastException: com.alibaba.ttl.TtlRunnable cannot be cast to org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor.decreaseCounter(MemoryAwareThreadPoolExecutor.java:517)
	at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor.beforeExecute(MemoryAwareThreadPoolExecutor.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1139)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

具体报错就是 netty 想把task转成自己的runnable是类型错误
`increment = ((MemoryAwareRunnable) task).estimatedSize;`

同理 对于其他自定义线程池和runnable的程序 ， 通过增强使用TtlRunnable  是否有风险？

**Comment by oldratlee** [comment]
@woshioosm 

这个 Issue https://github.com/alibaba/transmittable-thread-local/issues/121#issuecomment-436564699 也涉及这个问题，解决方法是：

> 当然背后，觉得可能应该要做好的是：
>
> pool的beforeExecute方法 agent也要改好，
> 传的runnable参数已经去TtlRunnable的wrapper了。
> 真正不感知TtlRunnable。

需要 可以把这个需要 做一下 :)

**Comment by oldratlee** [comment]
@woshioosm 

现在 一个解决方法：

升级到 `Netty 4`，在`Netty 4`中已经没有 `org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor`类（这个`Netty 3`实现中有的类）。

当然 升级`Netty`要做的事 也很不少。 😄

**Comment by woshioosm** [comment]
1. 如果是api的角度 使用ttlRunable等方式wrap感觉很合适 ，不会影响其他的executor中操作自己的Runable。
2. 但是既然使用了字节码 能否切的更下层一些， 比如说 runable callable的方法最终都是由 futureTask的run方法中的call 来进行调用 是否可以对其进行增强（增强一处可以同时满足runnable和callable）
3.  基于v2.10.2 jdk8 进行了实验 写了一个简答的transformor 完全仿制了ttlrunable的切面方式
https://github.com/woshioosm/transmittable-thread-local/blob/dev/src/main/java/com/alibaba/ttl/threadpool/agent/internal/transformlet/impl/TtlFutureTaskTransformlet.java
agent只使用这一个transformletList.add(new TtlFutureTaskTransformlet()); 即可 
代码没做复杂的考虑，仅简单进行了Executor线程池的实验ok 
4. 这种方式应该对Executor 也不需要进行什么操作，也不需要创造新的类 是否可以作为一种方式进行考虑？ 可以讨论下。

**Comment by oldratlee** [comment]
> 2\. 但是既然使用了字节码 能否切的更下层一些， 比如说`Runable`、`Callable`的方法最终都是由`FutureTask`的`run`方法中的`call`来进行调用 是否可以对其进行增强（增强一处可以同时满足`Runable`和`Callable`）
@woshioosm 还好的思路 👍 我也想一下 ❤️

这样的做法，目前想到需要要注意的问题：

1. 与`ThreadPoolExecutor`的实现实现细节相关，不是面向`API`，如果要跟进不同版本`JDK`和`ThreadPoolExecutor`实现方式调整，否则可能`Break`功能。
2. 与用户已使用的Wrap使用方式（如 `TtlRunnable.get`）输入，与开启Agent后的协作（如 不期望多次Wrap） 要注意。

**Comment by woshioosm** [comment]
@oldratlee 
1.  嗯 说的对。  jdk需要 保持关注future的 result = c.call();这行不能发生变化。   个人觉得可以做些判断， 如果它不存在了 ，再生效替补的 transformor。
 
2. 对于如果用户使用api的情况，可以添加判断逻辑 （参见：https://github.com/woshioosm/transmittable-thread-local/blob/dev/src/main/java/com/alibaba/ttl/threadpool/agent/internal/transformlet/impl/TtlFutureTaskTransformlet.java）
在futureTask的构造方法处判断是否是Ttl包裹后的runnbale和callable， 在进行后面的逻辑

`String code = "isApiTtl=($1 instanceof com.alibaba.ttl.TtlCallable || $1 instanceof com.alibaba.ttl.TtlRunnable)?true:false;";
`

3. 我们本身是一个追踪组件， 所以不能要求用户使用api，也不能要求用户升级netty4 ，也不能保证用户没有和netty3一样 自己对线程池进行了处理， 的确头疼。

**Comment by auyang-0626** [comment]
@oldratlee 
你好，我们在trace系统中引入了ttl.同样遇到用户在beforeExecutor方法中，强转runnable的类型报错。
我的解决方法是  agent增强的时候，拦截所有的ExecutorService派生出来的类，把它们的beforeExecutor和afterExecutor都增强下，从TtlRunnable取出用户原始的类型，然后还回去。
这种方式你觉得会有什么隐患吗？

**Comment by oldratlee** [comment]
@auyang-0626 在版本`2.11.0-RC1`中解决这个问题，就是你的思路：

> agent增强的时候，拦截所有的ExecutorService派生出来的类，把它们的beforeExecutor和afterExecutor都增强下，从TtlRunnable取出用户原始的类型，然后还回去。

另外加的判断逻辑是：

只是有`Agent`的情况下（即`Auto Wrapper`），才会做这个`Auto Unwrap`操作。

**Comment by DreamLettuce** [comment]
> @woshioosm @auyang-0626
> 
> 在版本 **_`2.11.0`_** 中，已经解决了这个问题。 https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.11.0
> 
> > * support unwrap ttl runnable for before/afterExecute methods of executor subclass when decorate by ttl agent  [强转类型失败的bug #141](https://github.com/alibaba/transmittable-thread-local/issues/141) 🚗
> 
> 实现方式 即 是你的思路： @auyang-0626
> 
> > agent增强的时候，拦截所有的ExecutorService派生出来的类，把它们的beforeExecutor和afterExecutor都增强下，从TtlRunnable取出用户原始的类型，然后还回去。
> 
> **另外加的判断逻辑**是：
> 
> 只在`Agent`的情况下（即`Auto Wrapper`），才会做对应的这个`Auto Unwrap`操作。

![image](https://user-images.githubusercontent.com/7601244/158528478-c8b3330d-50e0-462e-a198-92171c0fba2f.png)

看代码是根据`TtlAttachments.KEY_IS_AUTO_WRAPPER` 标记判断是否为`Auto Wrapper`，但是上方增强代码是直接调用的setAutoWrapperAttachment方法，并未判断是否被agent真正的增强成功。

如果用户调用线程池execute/submit时传参类型为TtlRunnable，则实际未被agent增强（因为TtlRunnable.get中有重复增强判断），却在beforeExecute/afterExecute中执行了unwarap逻辑（因为TtlRunnable本身实现了TtlAttachments）。

这样的话如果用户在自定义beforeExecute/afterExecute中做了类似的强转动作，还是会报错`ClassCastException`，不知道理解的对不对，求大佬解答。 @oldratlee 

测试code：
```
    public static void main(String[] args) {
        MyThreadPoolExecutor myThreadPoolExecutor = new MyThreadPoolExecutor(1, 1, 1, TimeUnit.MINUTES, new LinkedBlockingQueue<>());
        myThreadPoolExecutor.execute(TtlRunnable.get(() -> System.out.println("agent test")));
    }


    static class MyThreadPoolExecutor extends ThreadPoolExecutor {

        public MyThreadPoolExecutor(int corePoolSize, int maximumPoolSize, long keepAliveTime, TimeUnit unit, BlockingQueue<Runnable> workQueue) {
            super(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue);
        }

        @Override
        protected void beforeExecute(Thread t, Runnable r) {
            TtlRunnable ttlRunnable = (TtlRunnable) r;
            super.beforeExecute(t, r);
        }
    }
```

**Comment by oldratlee** [comment]
@DreamLettuce  问题收到。

独立的问题，请开个新的 issue。 🙏

**Comment by oldratlee** [comment]
@DreamLettuce 

## 问题复现

在单元测试中，添加了复现的`Test Case`

https://github.com/alibaba/transmittable-thread-local/blob/32adad1138dd6b7c01483c83495cd8545d80cd4a/src/test/java/com/alibaba/ttl/threadpool/BeforeAndAfterExecuteMethodOfExecutorSubclassTest.kt#L58-L76

集成测试失败并复现问题：

```java
There was 1 failure:
1) underAgent_task_is_explicit_TtlRunnable__should_not_be_unwrapped(com.alibaba.test.ttl.threadpool.BeforeAndAfterExecuteMethodOfExecutorSubclassTest)
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.alibaba.test.ttl.threadpool.BeforeAndAfterExecuteMethodOfExecutorSubclassTest.underAgent_task_is_explicit_TtlRunnable__should_not_be_unwrapped(BeforeAndAfterExecuteMethodOfExecutorSubclassTest.kt:75)
FAILURES!!!
```

https://ci.appveyor.com/project/oldratlee/transmittable-thread-local/builds/42950727/job/cwwfxds3f0mx0d93#L555

## 问题修复

- 修复提交： e04f6f43687a8b9c844033b5532bbd50c166f783
- 集成测试 恢复成功了
https://ci.appveyor.com/project/oldratlee/transmittable-thread-local/builds/42950728/job/lpi7murb4fc05k67

**Comment by DreamLettuce** [comment]
> ## PS 关于，是否有实际的业务使用场景？
> 在`beforeExecute/afterExecute`中做强转`TtlRunnable`，即`TtlRunnable ttlRunnable = (TtlRunnable) r;`， 这样做的 实际业务需求场景是什么？ ❤️ @DreamLettuce

目前没有实际的业务场景，只是我们目前使用TTL(2.10.*版本)时遇到当前issue netty线程池强转的bug，查看社区fix代码时发现的这个小问题。

我也觉得一般情况下业务使用了agent不会再直接调用TtlRunnable对象，但是也有可能先使用了Java SDK，后续如果改为使用agent可能会暴露这个问题。

**Comment by oldratlee** [comment]
> 目前没有实际的业务场景，只是我们目前使用TTL(`v2.10.x`)时遇到当前issue netty线程池强转的bug，查看社区fix代码时发现的这个小问题。

推荐跟进升级，避免踩老版本的Bug。@DreamLettuce

具体看各版本release note中的说明：

https://github.com/alibaba/transmittable-thread-local/releases
