### ISSUE TITLE
关于clean extra TTL value的疑问

### ISSUE THREAD

**Issue by luoxn28** [alibaba/transmittable-thread-local#134]
您好，看到clean extra TTL value这块逻辑，有个疑问，特请教下，谢谢。

疑问点：

*从目前transmittable-thread-local的TtlRunnable实现来看，在TtlRunable run时，会以TtlRunnable.get时间点获取的captured（类似TTL快照）为准，holder中不在captured的先移除，在的会被替换*。 

holder中不在captured的先移除，这样会导致当前线程之前set过的TransmittableThreadLocal变量数据丢失，如果父线程中也存在该TransmittableThreadLocal变量但是没set过？

```java
public static Object replay(@Nonnull Object captured) {
	@SuppressWarnings("unchecked")
	Map<TransmittableThreadLocal<?>, Object> capturedMap = (Map<TransmittableThreadLocal<?>, Object>) captured;
	Map<TransmittableThreadLocal<?>, Object> backup = new HashMap<TransmittableThreadLocal<?>, Object>();

	for (Iterator<? extends Map.Entry<TransmittableThreadLocal<?>, ?>> iterator = holder.get().entrySet().iterator();
		 iterator.hasNext(); ) {
		Map.Entry<TransmittableThreadLocal<?>, ?> next = iterator.next();
		TransmittableThreadLocal<?> threadLocal = next.getKey();

		// backup
		backup.put(threadLocal, threadLocal.get());

		// clear the TTL values that is not in captured
		// avoid the extra TTL values after replay when run task
		// 这里会排除当前线程holder中非captured来的所有ThreadLcoal，在restore时在重新放回来
		if (!capturedMap.containsKey(threadLocal)) {
			iterator.remove();
			threadLocal.superRemove();
		}
	}

	// set TTL values to captured
	setTtlValuesTo(capturedMap);

	// call beforeExecute callback
	doExecuteCallback(true);

	return backup;
}
```

这里我有个疑问，如果当前线程holder中有一个TransmittableThreadLocal（captured中没有），并且当前线程之前也set过该TransmittableThreadLocal，执行到上述逻辑时，当前线程的TransmittableThreadLocal变量数据丢失，示例代码如下：

```java
ExecutorService executor = Executors.newFixedThreadPool(1);
executor.submit(() -> {});

TransmittableThreadLocal<String> child = new TransmittableThreadLocal<>();
executor.submit(() -> {
    child.set("value-set-in-child");
    System.out.println(Thread.currentThread().getName() + ": " + child.get());
});

final TransmittableThreadLocal<String> parent = new TransmittableThreadLocal<>();
parent.set("value-set-in-parent");
executor.submit(TtlRunnable.get(() -> {
    System.out.println(Thread.currentThread().getName() + ": " + child.get()); // 这里child.get为null
    System.out.println(Thread.currentThread().getName() + ": " + parent.get());
}));

executor.shutdown();
```

输出结果为：

```
pool-1-thread-1: value-set-in-child
pool-1-thread-1: null
pool-1-thread-1: value-set-in-parent
```

从目前transmittable-thread-local的TtlRunnable实现来看，在TtlRunable run时，会以TtlRunnable.get时间点获取的captured（类似TTL快照）为准，holder中不在captured的先移除，在的会被替换。这样处理的话，相当于针对TransmittableThreadLocal来说，都是以captured为最高优先级了。

这样来看，TransmittableThreadLocal在TtlRunnable中不像一个ThreadLocal，是一个父线程Transmittable上下文的映射（个人理解），而在普通Runable中才像一个ThreadLocal。

类似issue：https://github.com/alibaba/transmittable-thread-local/issues/90  https://github.com/alibaba/transmittable-thread-local/issues/127

**Comment by oldratlee** [comment]
> holder中不在captured的先移除，这样会导致当前线程之前set过的TransmittableThreadLocal变量数据丢失，如果父线程中也存在该TransmittableThreadLocal变量但是没set过？

1. `TransmittableThreadLocal`一般是`static`，即`TransmittableThreadLocal`对象本身是全局存在的。
2. `TransmittableThreadLocal`传递的是 `TransmittableThreadLocal`的`value`。
    - `ThreadLocal`（含`InheritableThreadLocal `、`TransmittableThreadLocal`）的`value`是`Lazy Init`（延迟初始化的）。
        -  `ThreadLocal`为什么是延迟初始化，这个问题应该是容易理解的，原因是：
            在没有具体业务场景前提下，这样的做法避免内存浪费。 
    - `ThreadLocal`的`get`/`set`操作会初始化`ThreadLocal`的值。
    - 综上说明，需要传递场景，就需要显式保证`value`已经有了（通过`get`/`set`操作触发）。

**Comment by luoxn28** [comment]
谢谢回复~ 你说的这些我是理解的，ttl代码也是这样实现的。

『如果父线程中没set过，就出现在子线程（更严谨地说，是被传递的线程）』
这其实是 Bug :) --- 使用transmittable-thread-local，是不推荐这种父线程中没有set过的TransmittableThreadLocal变量，就出现在被传递线程的，我当时是看到`clean extra TTL value`这块代码时感觉这种场景有问题，实际上不推荐这样使用的~
