### ISSUE TITLE
仅仅通过代理Runnable能否实现同样的功能

### ISSUE THREAD

**Issue by xiexianchao** [alibaba/transmittable-thread-local#135]
我理解的是`TTL`源码主要分为两部分，一部分是`TransmittableThreadLocal`，另一部分是`Runnable`、`Callable`等代理类。

我有一个问题，仅仅通过代理`Runnable`能够实现跨线程池的上下文传递吗或者说这样有什么缺点？

比如这样：

```java
public class MyRunnable implements Runnable {
    private Runnable runnable;
    private Content content;

    public MyRunnable(Runnable runnable) {
        this.runnable = runnable;
        content = (Content) ContentHolder.get();
    }
    @Override
    public void run() {
        ContentHolder.set(content);
        runnable.run();
        ContentHolder.remove();
    }
}
```

**Comment by oldratlee** [comment]
@xiexianchao 简单场景（如只涉及单个上下文时）这个做法是够用。

随着应用场景复杂，如

- 涉及多个上下文
- 使用方期望透明 要关心的不同上下文的传递
- 嵌套且同不切换线程情况下，安全的设置与清理
你示例做法会有问题

上下文传递成为一个架构问题，需要关注并解决好的点变得错综复杂起来了。

展开的讨论 详见 Issue #128 这个库带来怎样的好处和优势？
