### ISSUE TITLE
使用TransmittableThreadLocal后项目中shiro无法进行登录认证

### ISSUE THREAD

**Issue by chanbaor** [alibaba/transmittable-thread-local#137]

**Comment by chanbaor** [comment]
使用TransmittableThreadLocal后项目中shiro无法进行登录认证，抛No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.异常，去掉TransmittableThreadLocal后正常。

**Comment by oldratlee** [comment]
和具体流程、传递的数据和使用框架相关，推荐你自己了解分析一下。

或者给一个极简的可运行复现问题的代码实现。 @chanbaor
