### ISSUE TITLE
TransmittableThreadLocal使用问题

### ISSUE THREAD

**Issue by yinjihuan** [alibaba/transmittable-thread-local#138]
我目前测试下来，发现只需要使用`TransmittableThreadLocal`就可以跨线程池传递，疑问是到底要不要进行线程的修饰？

或者说，是不是可以不用配合下面的使用三种方式，直接使用`TransmittableThreadLocal`就可以了

-------

`TransmittableThreadLocal`有3种使用方式：

1. [修饰`Runnable`和`Callable`](https://github.com/alibaba/transmittable-thread-local/#21-%E4%BF%AE%E9%A5%B0runnable%E5%92%8Ccallable)
2. [修饰线程池](https://github.com/alibaba/transmittable-thread-local/#22-%E4%BF%AE%E9%A5%B0%E7%BA%BF%E7%A8%8B%E6%B1%A0)
3. [使用`Java Agent`来修饰`JDK`线程池实现类](https://github.com/alibaba/transmittable-thread-local/#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB)

**Comment by yinjihuan** [comment]
用threadLocal是获取不到值的，用TransmittableThreadLocal就可以

**Comment by oldratlee** [comment]
`TransmittableThreadLocal`有3种使用方式，参见文档：

1. [修饰`Runnable`和`Callable`](https://github.com/alibaba/transmittable-thread-local/#21-%E4%BF%AE%E9%A5%B0runnable%E5%92%8Ccallable)
2. [修饰线程池](https://github.com/alibaba/transmittable-thread-local/#22-%E4%BF%AE%E9%A5%B0%E7%BA%BF%E7%A8%8B%E6%B1%A0)
3. [使用`Java Agent`来修饰`JDK`线程池实现类](https://github.com/alibaba/transmittable-thread-local/#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB)

3种使用方式都是可以完成跨线程池传递的。

可以认为后一种是前一种的对用户使用的简化。第3种『修饰线程或者线程池』的效果是『可以做到应用代码 **无侵入**』。

不同使用方式，你可以按需选用，具体请参见上面的文档说明。 @wilddylan 

---------------

> 是不是可以不用配合上面的三种方式，直接使用TransmittableThreadLocal就可以了

不行的。

> 直接使用TransmittableThreadLocal就可以跨线程池传递了，想请教下修饰线程或者线程池的作用是什么？我测下来，不修饰也是可以的

你的测试Case不全、不典型。 

『测试Case不全、不典型』的验证方法，比如： @yinjihuan 
在你的测试Case里，`TransmittableThreadLocal`换成`ThreadLocal`，是不是 也是通过的。

-------

#### @yinjihuan  能把这个问题开一下独立的Issue吗？不在这个Issue里讨论 :)

**Comment by oldratlee** [comment]
> 用threadLocal是获取不到值的，用TransmittableThreadLocal就可以

给一下 你的 测试 Case？ 我看一下 :)

**Comment by yinjihuan** [comment]
链接: https://pan.baidu.com/s/1vh8ncJHcrHCmsiXK5dv7Ow 提取码: mpp4 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by yinjihuan** [comment]
传到网盘了
启动项目，访问http://localhost:8311/test?id=1，可以看到控制台有如下输出：


http-nio-8311-exec-2:controller.test:1
SimpleAsyncTaskExecutor-1:service.test:null


第一行是Controller输出的，用的是tomcat的线程
第二行是Service输出的，用的是异步线程池的线程
使用ThreadLocal进行值传递是获取不到的

将RpcContent中ThreadLocal改成TransmittableThreadLocal后再次测试，值可以获取到，并没有对线程进行修饰

**Comment by oldratlee** [comment]
> 链接: https://pan.baidu.com/s/1vh8ncJHcrHCmsiXK5dv7Ow 提取码: mpp4 复制这段内容后打开百度网盘手机App，操作更方便哦

在Github上，推荐 直接走一个仓库的代码工程  :)

**Comment by yinjihuan** [comment]
我再详细测试下

**Comment by yinjihuan** [comment]
没问题了，之前我测过的，『小伙伴同学们写的 TTL使用场景 与 设计实现解析的文章』里面有2篇文章还是我自己写的，哈哈。
只是最近我稍微试了一下，没仔细测，发现不修饰也可以获取值，我以为新版本改进了。
