### ISSUE TITLE
关于内存泄漏的问题

### ISSUE THREAD

**Issue by dictionaryshi** [alibaba/transmittable-thread-local#140]
咨询下， 子线程自动拷贝了父线程中的变量， 那么一般子线程不考虑主动删除拷贝过来的变量，是不是有内存泄漏的风险呢。

**Comment by oldratlee** [comment]
> 一般子线程不考虑主动删除拷贝过来的变量，是不是有内存泄漏的风险

子线程中 执行的过程是：

- `Replay`：重放父线程过来的上下文。框架完成，业务不受业务影响。
- 执行业务逻辑
- `Restore`： 恢复成执行前自己上下文。框架完成，业务不受业务影响。
    这一步的结果是，不再引用释放父线程过来的上下文。
    即不会因为`transmittable-thread-local`的传递过程引入内存泄漏的问题。

更信息参见：

- 文档：[所有TTL值的抓取、回放和恢复方法（即CRR操作）](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
- 可以看看 Issue『小伙伴同学们写的 TTL使用场景 与 设计实现解析的文章（写得都很好！ ）❤️ #123』
    - 推荐 梳理一下`TransmittableThreadLocal`的系统流程、查看代码实现。 @yinjihuan
- 在其它Issue中 已经有方面的讨论，如 [是否有内存泄露的风险？#96](https://github.com/alibaba/transmittable-thread-local/issues/96)
    - 可以翻一下相关的 [Issue列表 `q=内存+label%3Aquestion`](https://github.com/alibaba/transmittable-thread-local/issues?q=%E5%86%85%E5%AD%98+label%3Aquestion)
