### ISSUE TITLE
强转类型失败的bug

### ISSUE THREAD

**Issue by auyang-0626** [alibaba/transmittable-thread-local#141]
你好，我们在trace系统中引入了ttl.同样遇到用户在beforeExecutor方法中，强转runnable的类型报错。

我的解决方法是：

agent增强的时候，拦截所有的ExecutorService派生出来的类，把它们的beforeExecutor和afterExecutor都增强下，从TtlRunnable取出用户原始的类型，然后还回去。

这种方式你觉得会有什么隐患吗？

**Comment by oldratlee** [comment]
#133 同一个问题

**Comment by oldratlee** [comment]
@auyang-0626 发布了版本`2.11.0-RC1` 来解决这个问题。

你试试 是不是 OK的？ :)
