### ISSUE TITLE
TtlRunnable A run执行最后一行sleep, TtlRunnable B执行完毕 释放TransmittableThread Local holder, TtlRunnable A进入restore holder还是有值怎么做到的

### ISSUE THREAD

**Issue by qq31715879** [alibaba/transmittable-thread-local#142]
源码学习提问

```java
Runnable runnable = new Runnable() {
    @Override
    public void run() {
        System.out.println(transmittableThreadLocal.get());
        transmittableThreadLocal.set("aaaa");
        System.out.println(transmittableThreadLocal.get());
        transmittableThreadLocal.set("bbb");
        System.out.println(transmittableThreadLocal.get());

        try {
            Thread.sleep(7000);
        } catch (InterruptedException e) {
        }
        System.out.println("Thread 1 执行完毕");
    }
};

ExecutorService executorService = Executors.newFixedThreadPool(2);
TtlRunnable ttlRunnable = TtlRunnable.get(runnable);
executorService.execute(ttlRunnable);

Runnable runnable1 = new Runnable() {
    @Override
    public void run() {
        System.out.println(transmittableThreadLocal.get());
        transmittableThreadLocal.set("111");
        System.out.println(transmittableThreadLocal.get());
        transmittableThreadLocal.set("222");
        System.out.println(transmittableThreadLocal.get());
        System.out.println("Thread 2 执行完毕");
    }
};
TtlRunnable ttlRunnable1 = TtlRunnable.get(runnable1);
executorService.submit(ttlRunnable1);
```

----------------------------------------------------------------------------

- TtlRunnable A和B共同使用一个TransmittableThreadLocal
- TtlRunnable A run执行最后一行sleep
- TtlRunnable B run执行完毕 -> 释放TransmittableThreadLocal holder，holder中的map size == 0
- TtlRunnable A开始进入restore，但是进入方法之前，holder中的map值被恢复了，holder还是有值
    怎么做到的？

----------------------------------------------------------------------------

```bash
start restore TransmittableThreadLocal$1@4449983f {TransmittableThreadLocal@5754de5a=null}
    for holder.get() size 1
remove 222
end restore TransmittableThreadLocal$1@4449983f {}  holder.get() size 0
end restore TransmittableThreadLocal$1@4449983f {}  holder.get() size 0
setTtlValuesTo restore TransmittableThreadLocal$1@4449983f {}  holder.get() size 0
restore 结束执行
restore 结束执行 TransmittableThreadLocal$1@4449983f {}  holder.get() size 0
Thread 1 执行完毕
run 执行完毕
run 执行完毕 TransmittableThreadLocal$1@4449983f {TransmittableThreadLocal@5754de5a=null}
    holder.get() size 1

# 这里ttlrunable A sleep完了之后开始restore
# 但是TransmittableThreadLocal.holder突然又有值了
# 这里的值啥时候又塞进去了

restore 开始执行
restore 开始执行 TransmittableThreadLocal$1@4449983f {TransmittableThreadLocal@5754de5a=null}
    holder.get() size 1
restore backupMap 0
doExecuteCallback bbb
start restore TransmittableThreadLocal$1@4449983f {TransmittableThreadLocal@5754de5a=null}
    for holder.get() size 1
remove bbb
end restore TransmittableThreadLocal$1@4449983f {} holder.get() size 0
end restore TransmittableThreadLocal$1@4449983f {} holder.get() size 0
setTtlValuesTo restore TransmittableThreadLocal$1@4449983f {}  holder.get() size 0
restore 结束执行
restore 结束执行 TransmittableThreadLocal$1@4449983f {}  holder.get() size 0
```

**Comment by oldratlee** [comment]
> - TtlRunnable A和B共同使用一个TransmittableThreadLocal
> - TtlRunnable A run执行最后一行sleep
> - TtlRunnable B run执行完毕 -> 释放TransmittableThreadLocal holder，holder中的map size == 0
> - TtlRunnable A开始进入restore，但是进入方法之前，holder中的map值被恢复了，holder还是有值
>     怎么做到的？

你的信息说明 还不清楚。比如 

> 『TtlRunnable A开始进入restore，但是进入方法之前，holder中的map值被恢复了』

不清楚你说的是，恢复 成什么了？你期望的恢复 成什么？

------------

### @qq31715879 推荐：

- 要注意的是`holder`本身是一个`InheritableThreadLocal`。
- 文档：[所有TTL值的抓取、回放和恢复方法（即CRR操作）](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
- 可以看看『[小伙伴同学们写的 设计实现解析文章（写得都很好！ ）❤️ #123](https://github.com/alibaba/transmittable-thread-local/issues/123#issuecomment-476709456)』
    - 推荐 梳理一下`TransmittableThreadLocal`的系统流程、查看代码实现。

**Comment by qq31715879** [comment]
InheritableThreadLocal<Map<TransmittableThreadLocal<?>, ?>> holder

demo是两个ttlRunable 
Thread a 执行ttlRunable A , ttlRunable A run最后一行是sleep 10s
Thread b和Therad a并发执行, 
Thread b执行ttlRunable B , 那么ttlRunable B会先触发TransmittableThreadLocal.Transmitter.restore(backup);这方法
这方法吧holder中的map清空了, map的size是0

10s之后Thread a的ttlrunable a开始执行
TransmittableThreadLocal.Transmitter.restore(backup);这方法
但是共同操作的holder
InheritableThreadLocal<Map<TransmittableThreadLocal<?>, ?>> holder
这时候居然有值了, debug没看出来什么时候给holder中的map put了值
求大佬指教 困惑了好久

**Comment by qq31715879** [comment]
感谢提醒, 想起来了 holder本身是一个Threadlocal所以线程b释放的是自己的threadlocal 所以有值

**Comment by qq31715879** [comment]
感谢大佬回复




------------------ 原始邮件 ------------------
发件人: "李鼎(哲良)"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 晚上8:38
收件人: "alibaba/transmittable-thread-local"<transmittable-thread-local@noreply.github.com>;
抄送: "kael"<31715879@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/transmittable-thread-local] TtlRunnable A run执行最后一行sleep, TtlRunnable B执行完毕 释放TransmittableThread Local holder, TtlRunnable A进入restore holder还是有值怎么做到的 (#142)



  
TtlRunnable A和B共同使用一个TransmittableThreadLocal
 
TtlRunnable A run执行最后一行sleep
 
TtlRunnable B run执行完毕 -> 释放TransmittableThreadLocal holder，holder中的map size == 0
 
TtlRunnable A开始进入restore，但是进入方法之前，holder中的map值被恢复了，holder还是有值
 怎么做到的？
   
你的信息说明 还不清楚。比如
  
『TtlRunnable A开始进入restore，但是进入方法之前，holder中的map值被恢复了』
  
不清楚你说的是，恢复 成什么了？你期望的恢复 成什么？
 
 
@qq31715879 推荐：
  
要注意的是holder本身是一个InheritableThreadLocal。
 
文档：所有TTL值的抓取、回放和恢复方法（即CRR操作）
 
可以看看『小伙伴同学们写的 设计实现解析文章（写得都很好！ ）❤️ #123』  
推荐 梳理一下TransmittableThreadLocal的系统流程、查看代码实现。
