### ISSUE TITLE
没有特别理解 capture replay restore 这样的方式的好处？

### ISSUE THREAD

**Issue by soca2013** [alibaba/transmittable-thread-local#145]
如果直接用map，在capture 时清理map中的数据，同时在restore 清理map中的数据，会有什么影响？想了半小时，实在没想清楚在什么场景下，下面这代码的意义：

```java
 for (Iterator<? extends Map.Entry<TransmittableThreadLocal<?>, ?>> iterator = holder.get().entrySet().iterator();
             iterator.hasNext(); ) {
    Map.Entry<TransmittableThreadLocal<?>, ?> next = iterator.next();
    TransmittableThreadLocal<?> threadLocal = next.getKey();

    // backup
    backup.put(threadLocal, threadLocal.get());

    // clear the TTL values that is not in captured
    // avoid the extra TTL values after replay when run task
    if (!capturedMap.containsKey(threadLocal)) {
        iterator.remove();
        threadLocal.superRemove();
    }
}
```

同时，在run 的 finally 中restore 的原因也没想明白， 如果线程结束了，那么 把之前的  TransmittableThreadLocal restore回来有什么意义？ 线程复用的话，应该是在下次线程执行时复用 启动线程的 TransmittableThreadLocal，而不是restore 的TransmittableThreadLocal。

谢谢啦解答下。

**Comment by oldratlee** [comment]
# 提供反例式的回答

> ## 如果直接用map，在capture 时清理map中的数据，同时在restore 清理map中的数据，会有什么影响？

你说的是 map 是指 `holder`吗？如果是，说明如下：

### 『在capture 时清理map中的数据』 的问题

```java
ExecutorService executorService = ...

Runnable bizTask = ...
// <doCaptrue>  
// 在capture 时清理Holder中的数据
Runnable ttlRunnable = Runnable TtlRunnable.get();

executorService.submit(ttlRunnable);

// 后续运行，因为 Holder 没有KV了，即 后续的传递的内容是空。
// 都不会再正确传递，恢复成空。
// !!Bug!!

Runnable 后续的bizTask = ...
Runnable 后续的ttlRunnable = Runnable TtlRunnable.get();

executorService.submit(ttlRunnable);
```

### 『在restore 清理map中的数据』 的问题

提交到线程池的任务 可能 在本线程直接执行（参见 [『`CallerRunsPolicy`』](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.CallerRunsPolicy.html)。

问题说明如下：

```java
Runnable bizTask = ...
Runnable ttlRunnable = Runnable TtlRunnable.get();

// <doRestore>  
// 在restore 清理map中的数据
// 且是 本线程直接执行时，
executorService.submit(ttlRunnable);

// 后续运行，因为 Holder 没有KV了，即 后续的传递的内容是空。
// 都不会再正确传递，恢复成空。
// !!Bug!!
```

> ## 在run 的 finally 中restore 的原因也没想明白，
> 1. 如果线程结束了，那么 把之前的 TransmittableThreadLocal restore回来有什么意义？ 
> 2. 线程复用的话，应该是在下次线程执行时复用 启动线程的 TransmittableThreadLocal，而不是restore 的TransmittableThreadLocal。

还是 因为 『提交到线程池的任务 可能 在本线程直接执行』『Restore』确保没有上面的**_`Bug`_**。

# 按原则的回答

`CRR(Capture/Replay/Restore)`是一个面向上下文传递设计的流程，通过这个流程的分析可以保证/证明 正确性。

这个正确性的分析/证明 ，不依赖于 局部与反例。

# PS

如果你有兴趣『整体流程与分析』推荐：

- 文档：[所有TTL值的抓取、回放和恢复方法（即CRR操作）](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
- 可以看看『[小伙伴同学们写的 设计实现解析文章（写得都很好！ ）❤️ #123](https://github.com/alibaba/transmittable-thread-local/issues/123#issuecomment-476709456)』
    - 推荐 梳理一下`TransmittableThreadLocal`的系统流程、查看代码实现。

**Comment by ruanzhi** [comment]
能详细讲解一下：提交到线程池的任务 可能 在本线程直接执行』『Restore』确保没有上面的 Bug
`Runnable bizTask = ...
Runnable ttlRunnable = TtlRunnable.get();

// <doRestore>  
// 在restore 清理map中的数据
// 且是 本线程直接执行时，
executorService.submit(ttlRunnable);

// 后续运行，因为 Holder 没有KV了，即 后续的传递的内容是空。
// 都不会再正确传递，恢复成空。
// !!Bug!!`
这里头提交了任务，也需要等这个提交任务线程的当前任务结束了，才能让他在获取新的任务，这时候获取的任务可能就是自己提交的，因此没太明白，这种replay的时候备份一下，restore在恢复回来这种机制

**Comment by ruanzhi** [comment]
> # 提供反例式的回答
> > ## 如果直接用map，在capture 时清理map中的数据，同时在restore 清理map中的数据，会有什么影响？
> 
> 你说的是 map 是指 `holder`吗？如果是，说明如下：
> 
> ### 『在capture 时清理map中的数据』 的问题
> ```java
> ExecutorService executorService = ...
> 
> Runnable bizTask = ...
> // <doCaptrue>  
> // 在capture 时清理Holder中的数据
> Runnable ttlRunnable = TtlRunnable.get();
> 
> executorService.submit(ttlRunnable);
> 
> // 后续运行，因为 Holder 没有KV了，即 后续的传递的内容是空。
> // 都不会再正确传递，恢复成空。
> // !!Bug!!
> 
> Runnable 后续的bizTask = ...
> Runnable 后续的ttlRunnable = TtlRunnable.get();
> 
> executorService.submit(ttlRunnable);
> ```
> 
> ### 『在restore 清理map中的数据』 的问题
> 提交到线程池的任务 可能 在本线程直接执行（参见 [『`CallerRunsPolicy`』](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.CallerRunsPolicy.html)。
> 
> 问题说明如下：
> 
> ```java
> Runnable bizTask = ...
> Runnable ttlRunnable = TtlRunnable.get();
> 
> // <doRestore>  
> // 在restore 清理map中的数据
> // 且是 本线程直接执行时，
> executorService.submit(ttlRunnable);
> 
> // 后续运行，因为 Holder 没有KV了，即 后续的传递的内容是空。
> // 都不会再正确传递，恢复成空。
> // !!Bug!!
> ```
> 
> > ## 在run 的 finally 中restore 的原因也没想明白，
> > 
> > 1. 如果线程结束了，那么 把之前的 TransmittableThreadLocal restore回来有什么意义？
> > 2. 线程复用的话，应该是在下次线程执行时复用 启动线程的 TransmittableThreadLocal，而不是restore 的TransmittableThreadLocal。
> 
> 还是 因为 『提交到线程池的任务 可能 在本线程直接执行』『Restore』确保没有上面的 **_`Bug`_**。
> 
> # 按原则的回答
> ### 原则：通过 整体流程/设计/代码实现 来 分析/证明 正确性。 @soca2013
> `CRR(Capture/Replay/Restore)`是一个面向上下文传递设计的流程，通过这个流程的分析可以保证/证明 正确性。
> 
> 这个正确性的分析/证明 ，不依赖于 局部与反例。
> 
> ### 总结一下：尽量首先去确定分析自己程序的正确性，而不是找反例。不分析依赖反例，又因为经验受限找不到反例认为没问题而上线，这其实就是我们程序出bug的原因。
> @soca2013 有说得不明白的地方，欢迎交流。 ❤️
> 
> # PS
> 如果你有兴趣『整体流程与分析』推荐：
> 
> * 文档：[所有TTL值的抓取、回放和恢复方法（即CRR操作）](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
> * 可以看看『[小伙伴同学们写的 设计实现解析文章（写得都很好！ ）❤️ #123](https://github.com/alibaba/transmittable-thread-local/issues/123#issuecomment-476709456)』
>   
>   * 推荐 梳理一下`TransmittableThreadLocal`的系统流程、查看代码实现。

能详细讲解一下：提交到线程池的任务 可能 在本线程直接执行』『Restore』确保没有上面的 Bug
`Runnable bizTask = ...
Runnable ttlRunnable = TtlRunnable.get();

//
// 在restore 清理map中的数据
// 且是 本线程直接执行时，
executorService.submit(ttlRunnable);

// 后续运行，因为 Holder 没有KV了，即 后续的传递的内容是空。
// 都不会再正确传递，恢复成空。
// !!Bug!!`
这里头提交了任务，也需要等这个提交任务线程的当前任务结束了，才能让他在获取新的任务，这时候获取的任务可能就是自己提交的，因此没太明白，这种replay的时候备份一下，restore在恢复回来这种机制
