### ISSUE TITLE
biz 全称是啥？就是喜欢起名字。。

### ISSUE THREAD

**Issue by Daiqiangdeveloper** [alibaba/transmittable-thread-local#147]
![image](https://user-images.githubusercontent.com/19928030/64906661-c9b9da00-d71b-11e9-9203-d01e748dd13c.png)

**Comment by oldratlee** [comment]
`biz`是`business`/业务 的缩写。 @Daiqiangdeveloper 

`biz code`是 业务代码的意思。 😄

**Comment by Daiqiangdeveloper** [comment]
哈哈哈  谢谢解答
