### ISSUE TITLE
agent增强后，Tomcat使用Http11Nio2Protocol协议导致的性能问题

### ISSUE THREAD

**Issue by lesterwang** [alibaba/transmittable-thread-local#148]
在`Tomcat`容器使用`Http11Nio2Protocol`协议时，请求的分发会执行到：

```java
indexOf:929, ScheduledThreadPoolExecutor$DelayedWorkQueue (java.util.concurrent)
remove:958, ScheduledThreadPoolExecutor$DelayedWorkQueue (java.util.concurrent)
remove:1766, ThreadPoolExecutor (java.util.concurrent)
cancel:281, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
finishRead:419, UnixAsynchronousSocketChannelImpl (sun.nio.ch)
finish:191, UnixAsynchronousSocketChannelImpl (sun.nio.ch)
onEvent:213, UnixAsynchronousSocketChannelImpl (sun.nio.ch)
run:293, EPollPort$EventHandlerTask (sun.nio.ch)
run:748, Thread (java.lang)
```

其中`indexOf`的逻辑为：

```java
private int indexOf(Object x) {
    if (x != null) {
        if (x instanceof ScheduledFutureTask) {
            int i = ((ScheduledFutureTask) x).heapIndex;
            // Sanity check; x could conceivably be a
            // ScheduledFutureTask from some other pool.
            if (i >= 0 && i < size && queue[i] == x)
                return i;
            } else {
                for (int i = 0; i < size; i++)
                    if (x.equals(queue[i]))
                        return i;
            }
        }
    return -1;
}
```

在使用`TTL Agent`增强的情况下，`ThreadPoolExecutor.remove(Runnable task)`的参数`task`会被转换为`com.alibaba.ttl.TtlRunnable`，在执行

```java
if (x instanceof ScheduledFutureTask)
```

语句时，执行结果永远为`false`，`TtlRunnable`会和队列中的每一个任务进行比较，且结果为`false`，在高并发的情况下，任务队列中的任务会有几千到几十万个不等，`x.equals(queue[i])`成为一个严重影响性能的操作，且无法及时清理掉任务进一步影响性能。

这种情况怎么处理比较合适呢？

**Comment by oldratlee** [comment]
问题收到，我理解一下。

看你已经分析过源码了，方便分离一下问题，给一下 极简的（不涉及Tomcat）可运行复现问题的测试Demo代码吗？

如果能写成个UT就更好了： @lesterwang ❤️

- Fork这个仓库
- 添加一个 极简的可运行复现问题的 UT Case

**Comment by lesterwang** [comment]
@oldratlee 因为这个问题牵扯到
```
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask
```
这个内部类（非public的），不适用tomcat容器很难复现这个问题，使用springBoot 1.5.x版本，然后添加一个bean：
```
@Bean
public EmbeddedServletContainerCustomizer tomcatCustomizer() {
    return container -> {
        if (container instanceof TomcatEmbeddedServletContainerFactory) {
            ((TomcatEmbeddedServletContainerFactory) container)
                    .setProtocol("org.apache.coyote.http11.Http11Nio2Protocol");
        }
    };
}
```
随意提供一个接口访问应该能复现这个问题。需要的话明天我再提供一个单独的项目方便测试。

当使用Http11Nio2Protocol协议处理请求时，会通过
```
ScheduledThreadPoolExecutor.reExecutePeriodic(RunnableScheduledFuture<?> task)```
来添加任务，由于task既不是Runnable也不是Callable，所以不会被转换为TtlRunnable。
后续的执行都是使用ScheduledThreadPoolExecutor#DelayedWorkQueue这个内部内的方法，即使参数时Runnable也不会被TTL框架转换，最终加入到DelayedWorkQueue#queue队列里的任务时非TtlRunnable的。

同时Http11Nio2Protocol协议会通过
```
sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(boolean var1)
```
方法来清理任务，该方法会调用到
```
java.util.concurrent.remove(Runnable task)
```
这时task会被转换为TtlRunnable，最终导致
```
ScheduledThreadPoolExecutor$DelayedWorkQueue.indexOf(Object x)
```
效率严重降低。

**Comment by oldratlee** [comment]
做了一个`ScheduledThreadPoolExecutor`/`ScheduledFutureTask`的使用Demo：

https://github.com/alibaba/transmittable-thread-local/blob/d4142bde4a2a6fffa022a74686c14edabaa6e9dd/src/test/java/com/alibaba/demo/scheduled_thread_pool_executor/ScheduledFutureTaskDemo.kt#L20-L26

在使用`TTL Agent`增强的情况下，与不使用`TTL  Agent`一样，

都可以通过[`ScheduledFuture`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ScheduledFuture.html)的`cancel`方法，清理/删除定时任务。

PS： 对于Agent方式通过脚本方便些来完成运行（省得设置`Agent`参数）

```bash
$ scripts/run-agent-for-class.sh com.alibaba.demo.scheduled_thread_pool_executor.ScheduledFutureTaskDemoKt
```

输出如下：

```java
I'm a Runnable task, I'm working...
I'm a Runnable task, I'm working...
I'm a Runnable task, I'm working...
cancel
canceled: true
Bye
```


------------------------

以`Agent`方式运行，Debug的断住 `ScheduledFuture`的`cancel`方法：
![image](https://user-images.githubusercontent.com/1063891/69899348-a3611d80-139f-11ea-8d09-34d4fbde1bd9.png)

可以确认 
- TTL的修饰是生效的；
- 不同的实例的引用关系是：
    `ScheduledFuture`实例 -> `java.util.concurrent.Executors.RunnableAdapter` -> 提交的定时`task`（经过的TTL Wrap）

**Comment by oldratlee** [comment]
因为整个 `TTL`及其`Java Agent`增强的实现 是

- 基于各个`Executor`（如`ScheduledThreadPoolExecutor `、`ThreadPoolExecutor `）的`API`语义
- 不是`Executor`的内部实现

所以使用（无论是一般的业务使用，还是`Tomcat`的`Executor`使用方式）应该是不会有问题的。

如果`Tomcat`的实现非常HACK，非常依赖的`Executor`的内部实现方式，是可能会出问题，一般大家的设计不会这么做。

---------------

还是请 @lesterwang 给一个可运行复现问题的测试Demo/UT。

我先Close这个Issue了， 
如有可以可运行复现问题的测试Demo/UT，请 @lesterwang 随时 Reopen 这个Issue。 ❤️
