### ISSUE TITLE
使用Hytrix的线程池如何修饰呢

### ISSUE THREAD

**Issue by 0josh0** [alibaba/transmittable-thread-local#149]
如题

**Comment by oldratlee** [comment]
有些文章说明，比如：

- Spring Cloud中Hystrix 线程隔离导致ThreadLocal数据丢失
    - 上篇 http://cxytiandi.com/blog/detail/13331
    - 下篇 http://cxytiandi.com/blog/detail/18782

可以看一下。

具体采用可以自己搜索、试用再看看 :)
