### ISSUE TITLE
javaagent路径配置问题

### ISSUE THREAD

**Issue by 0josh0** [alibaba/transmittable-thread-local#150]
你好，在github上看见`transmittable-thread-local`，非常想使用。

但是关于通过`javaagent`的方式使用不是很理解，想请问一下具体使用方式：

1. 在`pom`中引入`dependency`
1. 在启动脚本中增加：`-javaagent:WEB-INF/lib/transmittable-thread-local-2.10.2.jar`

不知道后面的路径用的对不对，我直接写的`war`解压后的相对路径，但是看样子好像没起作用，请教～

**Comment by 0josh0** [comment]
Jerry Lee <oldratlee@gmail.com> 于2019年9月21日周六 下午10:34写道：

2、在启动脚本中增加：-javaagent:WEB-INF/lib/transmittable-thread-local-2.10.2.jar
 
javaagent的路径 可以设置成 
相对路径
相对路径是指 启动WAR的WebServer（如Tomcat）的Java进程的当前路径。
或 绝对路径

在你的例子中，可以看出 你用的是 相对路径，且相对的 解压的WAR目录。

如果没有起作用，说明 启动WAR的WebServer（如Tomcat）的Java进程的当前路径 不是 解压的WAR目录。

请确认  启动WAR的WebServer（如Tomcat）的Java进程的当前路径 是什么，写正确相对路径 即可。

**Comment by oldratlee** [comment]
- `JavaAgent`指定的`Jar`文件路径，所以`WAR`文件中的`TTL Jar`文件，不能生效。
    - 解压了的`WAR`文件就有了`TTL Jar`文件。
- 查看进程的当前路径（`current/working directory`），可以试试`pwdx`命令（如果你机器上有这个命令的话）。
    - 更多与具体情况相关的查看方式，可以搜索一下。
