### ISSUE TITLE
不支持CompletableFuture?

### ISSUE THREAD

**Issue by cmershen1** [alibaba/transmittable-thread-local#151]
我使用`log4j2-ttl-thread-context-map`实现线程间的请求链路跟踪。

发现每次使用`CompletableFuture`时，日志打出的`traceid`都是一样的，是否不支持`CompletableFuture`？

**Comment by oldratlee** [comment]
方便分离一下问题，给一下 极简的（不涉及Tomcat）可运行复现问题的测试Demo代码吗？

如果能写成个UT就更好了： @cmershen1  ❤️

- Fork这个仓库
- 添加一个 极简的可运行复现问题的 UT Case
