### ISSUE TITLE
token存放在threatlocal中Hystrix线程隔离取值不到。

### ISSUE THREAD

**Issue by Nikati** [alibaba/transmittable-thread-local#153]
请问大家能提供一下解决DEMO吗。

**Comment by oldratlee** [comment]
@Nikati 可以看看这个 https://github.com/alibaba/transmittable-thread-local/issues/149#issuecomment-533793956 ，有文章说明`Hystrix`的问题及其解法：

> 有些文章说明，比如：
>
> - Spring Cloud中Hystrix 线程隔离导致ThreadLocal数据丢失
>    - 上篇 http://cxytiandi.com/blog/detail/13331
>    - 下篇 http://cxytiandi.com/blog/detail/18782
>        包含了 解决方法 的 说明。

----------

这边不怎么用`Hystrix`，我没有时间去挖这问题（`TTL`的使用问题）。

欢迎 @Nikati   ❤️
- 了解了上面的解法，能写个Demo。
- 通过Pull Request 贡献到 这个 项目里来
