### ISSUE TITLE
FutureTask/CompletableFuture的异步任务场景下，TTL的使用

### ISSUE THREAD

**Issue by liaofanxin** [alibaba/transmittable-thread-local#154]
请问在JDK1.8，CompletableFuture的异步任务的时候，如果做兼容？有demo可以参考一下吗

**Comment by oldratlee** [comment]
#  `FutureTask`

你说到的`FutureTask`是指[`java.util.concurrent.FutureTask`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/FutureTask.html)，是吧。 @liaofanxin 

`java.util.concurrent.FutureTask`是`Runnable`。一般是在[`ThreadPoolExecutor`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html)中执行，可以通过[`TTL`文档的说明的方法](https://github.com/alibaba/transmittable-thread-local#21-%E4%BF%AE%E9%A5%B0runnable%E5%92%8Ccallable)来使用：

- 2.1 修饰Runnable和Callable
- 2.2 修饰线程池
- 2.3 使用Java Agent来修饰JDK线程池实现类

这3个背后都是修饰`Runnable`，只是使用方式不同。

# `CompletableFuture`

`CompletableFuture`的执行，缺省使用执行器（[`ForkJoinPool`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.html)），底下转成`ForkJoinPool`的[`ForkJoinTask`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinTask.html)来执行，使用文档中[2.3 使用Java Agent来修饰JDK线程池实现类](https://github.com/alibaba/transmittable-thread-local#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB)的方式，透明支持`CompletableFuture`的TTL：

![image](https://user-images.githubusercontent.com/1063891/69871900-f8912680-12ee-11ea-81b2-8abbc364b404.png)

# `Stream`支持

参见Issue  #108： 线程内部使用了parallel stream 的场景下TTL的使用

# PS

Issue #74: 支持 jdk1.7 ForkJoinPool 和 jdk1.8 parallel stream

**Comment by liaofanxin** [comment]
多谢回复，已经找到解决办法，项目中已经引入，测试没问题，已发布上线



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 李鼎(哲良) <notifications@github.com&gt;
发送时间: 2019年11月29日 21:32
收件人: alibaba/transmittable-thread-local <transmittable-thread-local@noreply.github.com&gt;
抄送: 辛令剑 <804544174@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[alibaba/transmittable-thread-local] FutureTask/CompletableFuture的异步任务场景下，TTL的使用 (#154)




Closed #154.

**Comment by oldratlee** [comment]
能说一下你的场景和解决方法吗？😀 @liaofanxin

**Comment by liaofanxin** [comment]
使用场景：
&nbsp; &nbsp; &nbsp; &nbsp; 项目的日志targ（例如用户uid，订单id等），采用threadlocal来进行透传，但是在启用future或者threadpool来执行异步任务的时候，threadlocal中的日志targ是不能正常传递的
原因：
（1）threadlocal线程隔离
（2）InherbritableThreadLocal虽然可以解决线程隔离问题，但是无法解决线程池线程复用导致的日志targ混乱问题
原先解决方案：
（1）执行异步任务前重新获取threadlocal中的targ，然后在开启新任务的地方重新setThreadlocal
（2）targ作为参数进行传递
引入TTL后的方案
（1）采用ttl的TransmittableThreadLocal存储日志targ
（2）用TtlExecutors封装ThreadPool帮助类
（3）使用CompletableFuture并制定Executor



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 李鼎(哲良) <notifications@github.com&gt;
发送时间: 2019年11月29日 21:45
收件人: alibaba/transmittable-thread-local <transmittable-thread-local@noreply.github.com&gt;
抄送: 辛令剑 <804544174@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[alibaba/transmittable-thread-local] FutureTask/CompletableFuture的异步任务场景下，TTL的使用 (#154)




能说一下你的场景和解决方法吗？😀 @liaofanxin

**Comment by oldratlee** [comment]
> # 引入TTL后的方案
> ……
> 3. 使用CompletableFuture并制定Executor

关于『使用CompletableFuture并制定Executor』这点，对CompletableFuture及其使用ForkJoinPool Executor你是如何定制的？ @liaofanxin 

- 使用了『2.3 使用Java Agent来修饰JDK线程池实现类』的`Java Agent`方式吗？
- 如果没有使用`Java Agent`，你是如何做的？

**Comment by liaofanxin** [comment]
使用了2.3对用ForkJoinPool Executor进行修饰



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 李鼎(哲良) <notifications@github.com&gt;
发送时间: 2019年11月30日 14:13
收件人: alibaba/transmittable-thread-local <transmittable-thread-local@noreply.github.com&gt;
抄送: 辛令剑 <804544174@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[alibaba/transmittable-thread-local] FutureTask/CompletableFuture的异步任务场景下，TTL的使用 (#154)



 
引入TTL后的方案
 
……
 3. 使用CompletableFuture并制定Executor
  
关于『使用CompletableFuture并制定Executor』这点，对CompletableFuture及其使用ForkJoinPool Executor你是如何定制的？ @liaofanxin
  
使用了『2.3 使用Java Agent来修饰JDK线程池实现类』的Java Agent方式吗？ 

如果没有使用Java Agent，你是如何做的？

**Comment by LouisProgress** [comment]
> CompletableFuture

对的CompletableFuture的支持，能否分享一个demo，感谢！
