### ISSUE TITLE
Transmitter类中的一个WeakHashMap<ThreadLocal<Object>, TtlCopier<Object>>的变量threadLocalHolder有什么用

### ISSUE THREAD

**Issue by yongjie1992** [alibaba/transmittable-thread-local#155]
Transmitter类中的一个WeakHashMap<ThreadLocal<Object>, TtlCopier<Object>>的变量threadLocalHolder有什么用，在实际使用过程中这个Map一直都是空的，不清楚它的作用是什么

https://github.com/alibaba/transmittable-thread-local/blob/d4a9aa8a2e3f38da6f74e81a70eae5f8673a4c21/src/main/java/com/alibaba/ttl/TransmittableThreadLocal.java#L546-L550

**Comment by oldratlee** [comment]
@yongjie1992 

https://github.com/alibaba/transmittable-thread-local/blob/d4a9aa8a2e3f38da6f74e81a70eae5f8673a4c21/src/main/java/com/alibaba/ttl/TransmittableThreadLocal.java#L546-L550

这几个静态字段 是用于功能『集成`ThreadLocal`』

更多说明参见：

- Issue: ThreadLocal integration #130
- Transmitter的Javadoc
https://alibaba.github.io/transmittable-thread-local/apidocs/2.11.0/com/alibaba/ttl/TransmittableThreadLocal.Transmitter.html
![image](https://user-images.githubusercontent.com/1063891/69710661-bfb05080-113a-11ea-88b0-734316824acd.png)

**Comment by yongjie1992** [comment]
多谢指教！
