### ISSUE TITLE
@javax.annotation.Nonnull这个注解在jdk1.8里没有，请问需要引用什么依赖吗

### ISSUE THREAD

**Issue by sunzhiqiangGithub** [alibaba/transmittable-thread-local#156]
![image](https://user-images.githubusercontent.com/30972636/69970633-84a68680-1559-11ea-8287-3b0fe7794298.png)

**Comment by sunzhiqiangGithub** [comment]
![image](https://user-images.githubusercontent.com/30972636/69970774-cb947c00-1559-11ea-802a-cc262d5c9624.png)

**Comment by oldratlee** [comment]
@sunzhiqiangGithub

操作一下下面的步骤：

- IDE打开`pom4ide.xml`。不要打开`pom.xml`。
   因为有Java多版本支持，构建用的pom.xml，IDE支持不好
- 更新一下代码到最新`git pull --rebase`

### PS

因为涉及中间件工程（低java版本支持），我需要在dev gude里说明一下 开发注意事项。
我还没这个说明 😂

**Comment by oldratlee** [comment]
哦，你是在使用TTL。

下面2个代码质量的Annotation依赖，运行时是不需要的。

你需要（如为了IDE查看代码方便）可以自己加一下。

https://github.com/alibaba/transmittable-thread-local/blob/489004905b0f8f0679eb304ba250d5f8a915d469/pom.xml#L109-L132

**Comment by oldratlee** [comment]
哦，你是在使用TTL。

下面2个代码质量的Annotation依赖，运行时是不需要的。

你需要（如为了IDE查看代码方便）可以自己加一下。

https://github.com/alibaba/transmittable-thread-local/blob/489004905b0f8f0679eb304ba250d5f8a915d469/pom.xml#L109-L132

**Comment by sunzhiqiangGithub** [comment]
感谢大佬，我这个问题可能是因为idea的问题，可以编译成功，但是项目里报红。重新启动idea就可以了。

**Comment by sunzhiqiangGithub** [comment]
感谢大佬，可能是idea的问题，我在新版本上的idea是显示有红叉，但是可以通过编译。老版本的idea没有红叉。两个版本的idea都是可以通过编译，可能新版本idea的问题。

**Comment by oldratlee** [comment]
新新版本的IDEA我也在使用是可以的。

你按上面的更新代码、打开pom4ide.xml（更新ide工程）步骤再试试。
不行可以再Google搜索看看怎么解一下IDE问题。

Issue先close了 😀
