### ISSUE TITLE
pinpoint集成TtlAgent报错

### ISSUE THREAD

**Issue by nepoch** [alibaba/transmittable-thread-local#158]
使用版本

- [`pinpoint`](https://github.com/naver/pinpoint): 1.8.1
- `TTL`: 2.11.0

-------------------

在`pinpoint`的启动类中加入了`TtlAgent.premain(agentArgs, inst);`后报错，最后排查到：

- `TtlTransformer`类实现`ClassFileTransformer`接口`transform`是对于不增强的类直接返回了`EMPTY_BYTE_ARRAY = {}`
- 我看[`ClassFileTransformer`接口的`transform`方法`JavaDoc`的返回值说明](https://docs.oracle.com/en/java/javase/11/docs/api/java.instrument/java/lang/instrument/ClassFileTransformer.html#transform(java.lang.ClassLoader,java.lang.String,java.lang.Class,java.security.ProtectionDomain,byte%5B%5D))是

    ```java
    * @return  a well-formed class file buffer (the result of the transform),
               or <code>null</code> if no transform is performed.
    ```
    意思应该是说如果不做增强的话应该返回`null`这样
- 我试了改源码成返回`null`而不是`{}`，程序运行正常。

-----------------

`TtlTransformer`类的`transform`实现返回`EMPTY_BYTE_ARRAY = {}`是有什么特殊用意吗？这里改成返回`null`会不会有什么其他影响？

**Comment by oldratlee** [comment]
『`TtlTransformer`类的`transform`实现返回`EMPTY_BYTE_ARRAY = {}`』的原因参见  https://github.com/alibaba/transmittable-thread-local/pull/68#issuecomment-232903425 ：

> 用 empty array 来自代码质量改进的一个pull request #56
> 你可以从commit log( 4a5b292719a99414d9b46394544dc370bc27653f )里查到。
> 
> 我看持续集成多jdk版本都是通过的，就接纳了这个pr。
> https://github.com/alibaba/transmittable-thread-local/pull/68#issuecomment-232882555

----------------------

即 使用 empty array 而不是 `null`，是因为 优的代码实践，且 功能是OK的（`JDK Agent`有效支持）。

----------------------

从你提供的问题来看，使用`pinpoint`后，并不能使用`JDK Agent`一样能有效支持empty array的返回。

我改一下，发一个新版本。 @nepoch 

改成严格遵循 [`ClassFileTransformer`接口的`transform`方法的`JavaDoc`的返回值要求](https://docs.oracle.com/en/java/javase/11/docs/api/java.instrument/java/lang/instrument/ClassFileTransformer.html#transform(java.lang.ClassLoader,java.lang.String,java.lang.Class,java.security.ProtectionDomain,byte%5B%5D))，而不是 『优的代码实践』。

**Comment by oldratlee** [comment]
@nepoch 已发布 _**`v2.11.1`**_了，看看是不是 OK了？ :)
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.11.1

**Comment by nepoch** [comment]
> 已发布了 **_`v2.11.1`_** ：
> https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.11.1
> 
> @nepoch 使用新版本测试一下，是不是 OK了？ ❤️

@oldratlee 更新后测试正常，谢谢啦。

**Comment by hoverwinter** [comment]
@nepoch pinoint已经支持了异步上下文透传，你们的使用场景方便告诉一下么？

**Comment by nepoch** [comment]
> @nepoch pinpoint已经支持了异步上下文透传，你们的使用场景方便告诉一下么？
> 
> 为了传递业务上的 ThreadLocal 而非 tracing 的 threadlocal 么？

嗯嗯，有一些业务数据的传递。而且在线程池场景下也要拿到业务数据。我测试了pinpoint1.8.1版本，在使用线程池情况下也拿不到trx_id，所以直接集成了TTL。

**Comment by superbool** [comment]
> @nepoch pinpoint已经支持了异步上下文透传，你们的使用场景方便告诉一下么？
> 
> 为了传递业务上的 ThreadLocal 而非 tracing 的 threadlocal 么？

@hoverwinter 我们想在日志中记录每个请求的trace_id来实现日志全链路查询等功能，但pinpoint采样后，有些请求的trx_id没有，以及跨线程也会断掉。所以我们就想在Pinpoint中集成transmittable-thread-local，来实现跨线程的日志全链路追踪。不知道您有什么其他好的建议没
