### ISSUE TITLE
如何保证资源被清理，不会内存泄漏？

### ISSUE THREAD

**Issue by oldbig** [alibaba/transmittable-thread-local#160]
当前线程设置的一个值，在子线程，子子线程，孨线程中都可以访问到。
当创建很多复杂的子线程时，如何能在所有子线程中清理掉 remove() 那些值？
是需要找到所有子线程依次调用 remove清理吗？还是这个已经实现了无需自己手动清理？
谢谢！

**Comment by oldratlee** [comment]
重复。

参见
https://github.com/alibaba/transmittable-thread-local/issues/140#issuecomment-494767649
https://github.com/alibaba/transmittable-thread-local/issues/96#issuecomment-402594013

**Comment by oldbig** [comment]
谢谢 @oldratlee !
