### ISSUE TITLE
如何在启动fat jar时优雅的使用javaagent参数

### ISSUE THREAD

**Issue by Allurx** [alibaba/transmittable-thread-local#161]
我现在有一个通过`spring-boot-maven-plugin`打包后的`fat jar`，我是通过[使用Java Agent来修饰JDK线程池实现类](https://github.com/alibaba/transmittable-thread-local#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB)来启动这个`fat jar`的，启动命令类似以下这种方式

```sh
java -javaagent:path/to/transmittable-thread-local-2.11.2.jar -jar fat.jar
```

我现在有一个疑惑的地方：

- 当我将这个`fat jar`部署到服务器上时，我还必须保证目标服务器上有我当前`fat jar`所用到的`ttl.jar`
- 虽然`fat jar`内部已经包含了这个`jar`，但是我无法在`javaagent`后面指定`fat jar`中`ttl.jar`的路径
- 这样我就必须明确的知道目标服务器上`ttl.jar`的路径，然后再通过`javaagent`指定这个路径

请问有没有更加优雅的方式来使用`javaagent`指定`ttl.jar`呢？@oldratlee

**Comment by oldratlee** [comment]
`JavaAgent`需要指定`-javaagent`参数，即明确的知道目标服务器上`Agent Jar`的路径是需要的。
\# 没有找到不通过`-javaagent`参数设置好`Agent Jar`的方法。

可以通过一个脚本（简单的如`shell`脚本）来启动启动`Java`进程，在脚本中可以实现逻辑来发现`TTL/Agent Jar`的位置。 @Allurx Allurx

一种实现方式如下，比如

- 将
    - 启动脚本 `start.sh`
    - `fat.jar`
    - `Agent Jar`: `transmittable-thread-local-2.11.2.jar`
- 放在同一个目录
- 启动脚本 `start.sh` 实现 启动脚本的所在目录 

    ```sh
    #!/bin/bash

    # script file dir
    readonly BASE="$(basename "$(readlink -f "$0")")"

    java -javaagent:"$BASE/transmittable-thread-local-2.11.2.jar" -jar "$BASE/fat.jar"
    ```

## PS 

Fat Jar 与 Agent 的相关资源：

- Specify java agent inside 'fat jar'?
https://stackoverflow.com/questions/39033599/specify-java-agent-inside-fat-jar
- Including Java agent in standalone Spring Boot application
http://www.kubrynski.com/2014/12/include-java-agent-in-standalone-spring.html
- javaagent could not work normally when application is started as a uber executable jar
https://github.com/spring-projects/spring-boot/issues/4868
- https://github.com/sbt/sbt-javaagent
- Instrumentation Agent Setup
https://kamon.io/docs/v1/guides/setting-up-the-agent/

**Comment by Allurx** [comment]
@oldratlee 十分感谢你的回复，看来我只能通过脚本和ttl.jar来启动我的fat.jar了。
