### ISSUE TITLE
对Supplier方式提交的任务不友好

### ISSUE THREAD

**Issue by liuzhongkai** [alibaba/transmittable-thread-local#162]
需要将Supplier转换为Callable

**Comment by oldratlee** [comment]
- `Callable`/`Runnable`表义运行的任务，与`Executor`相关；`Suppiler`表义的数据源。
- 如果你用的`Java8`，`Suppiler`转成`Callable`半行代码完成，很简单：

    ```java
    executorService.Invoke(() -> supplier.get())
    ```

考虑上面2个原因，就像`ExecutorService`一样，不直接支持`Suppiler`： @liuzhongkai 

- 避免使用的`API`膨胀复杂，表义不清
- 需要的`Suppiler`转成`Callable`的地方，业务半行代码完成，很简单

**Comment by liuzhongkai** [comment]
使用java8中的CompletableFuture类对外接口并没有Callable类型的输入，取而代之的是Suppiler，Suppiler转换Callable很丑陋

        TtlCallable<Object> objectTtlCallable = TtlCallable.get(supplier::get);
        CompletableFuture.supplyAsync(() -> {
            try {
                return objectTtlCallable.call();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }, executor);

**Comment by oldratlee** [comment]
> 使用java8中的CompletableFuture类对外接口并没有Callable类型的输入

只通过上面的方法不能让`CompletableFuture`提供传递功能（`TransmittableThreadLocal`）。

**Comment by oldratlee** [comment]
发布了[`v2.11.4`](https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.11.4)，增加了对相关类型的`TTL Wrapper`工具方法，试试看 @liuzhongkai  😁

详见JavaDoc

- https://alibaba.github.io/transmittable-thread-local/apidocs/2.11.4/com/alibaba/ttl/TtlWrappers.html
- https://alibaba.github.io/transmittable-thread-local/apidocs/2.11.4/com/alibaba/ttl/TtlUnwrap.html
