### ISSUE TITLE
基于transmittable的logback-mdc-ttl在使用时线程之间值串了。

### ISSUE THREAD

**Issue by xiaolongzuo** [alibaba/transmittable-thread-local#165]
和logback的mdc集成使用时，引入了`logback-mdc-ttl:1.0.2`。

但是发现一个很奇怪的现象，在使用MDC打印traceId的时候，线程之间的traceId会串。

例如（PS：线程B请求的开始发生在线程A请求执行过程中）：

```java
线程A(http-nio-1)：
http请求（traceId为traceA）
   |
打印trace日志（transmittablethreadlocal记录的traceid）
   |
若干应用日志（mdc通过%X的方式打印，打印了线程B的traceId）
   |
http请求结束
线程B(http-nio-2)：
http请求（traceId为traceB）
   |
打印trace日志（transmittablethreadlocal记录的traceid）
   |
若干应用日志（mdc通过%X的方式打印）
   |
http请求结束
```

其中mdc是使用的logback-mdc-ttl，看了下logback-mdc-ttl是基于transmitable。
不知道有遇到过同样问题的没。

**Comment by xiaolongzuo** [comment]
补充下，transmittable使用的是2.11.0版本。

**Comment by xiaolongzuo** [comment]
再补充下，在http请求开始会执行mdc.put存放traceid，在http请求结束会mdc.clear清空。

**Comment by xiaolongzuo** [comment]
举个实际例子，假设请求A的traceid是traceA，请求A的线程是线程http-nio-1，请求B的traceid是traceB，请求B的线程是http-nio-2。我们现在会打印出如下日志（简单描述就是线程B的traceid串到线程A去了）：
00:00:00 http-nio-1 http-request-in,traceid=traceA (请求A，这种trace日志是用的tracecontext里的traceid)
00:00:01 http-nio-1 some_app_log_1,traceid=traceA(请求A，这种应用日志是用的mdc里的traceid，以下类似，不再重复)
00:00:02 http-nio-2 http-request-in,traceid=traceB (请求B)
00:00:03 http-nio-2 some_app_log_1,traceid=traceB (请求B)
00:00:04 http-nio-1 some_app_log_2,traceid=traceB (请求A)PS：正常这一条日志的traceid应该是traceA
00:00:05 http-nio-2 some_app_log_2,traceid=traceB (请求B)
00:00:06 http-nio-1 http_request_out,traceid=traceA (请求A)
00:00:07 http-nio-2 http_request_out,traceid=traceB (请求B)

**Comment by oldratlee** [comment]
@xiaolongzuo 

麻烦给 一个 极简的 可运行复现问题 的代码实现/Demo，这样可以

- 方便大家能排查分析
- 方便排除可以的业务实现问题

**Comment by werwolfGu** [comment]
我们工程也遇到类似问题，请问楼主这个问题解决了吗 ？

**Comment by master-starcloud** [comment]
> 我们工程也遇到类似问题，请问楼主这个问题解决了吗 ？

大佬解决了吗
