### ISSUE TITLE
是不是只能拷贝一次？

### ISSUE THREAD

**Issue by EmmaWang90** [alibaba/transmittable-thread-local#166]
我的应用场景是这样的，http-service线程池根据rest请求的内容设置ThreadLocal变量，然后需要使用线程池处理任务，这个时候使用TtlRunnable将http-service的ThreadLocal传入线程池中的线程中。由于rest请求的不同，ThreadLocal变量的内容也不同，但线程池的ThreadLocal没有变化，所以想确定一下，是不是只能拷贝一次？

**Comment by oldratlee** [comment]
在`TtlRunnable.get`方法会做拷贝操作，每次`TtlRunnable.get`操作都会拷贝。 @EmmaWang90 
（缺省只是传递引用，可通过`TransmittableThreadLocal.copy`方法定制）
