### ISSUE TITLE
框架层和业务层零代码改动的基础上，可否使用TTL

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/transmittable-thread-local#171]
关注`TTL`蛮久了，使用异步场景比较少，但还是存在，框架上已经存在若干个`Threadlocal`，在异步调用中会丢失。

需求是

- 不希望把`Threadlocal`改成`TTL Theadlocal`
- 也不能做到把其它任何`Threadlocal`对象改成对应的`TTL`对象
- 但希望能享受到`TTL`的便利

总而言之，

- 目前框架的一切现状保持不变
- 然后通过引入`TTL`的包，或者通过`Java Agent`方式也可
- 请问贵框架是否具备这个能力

在相关文档中并没有找到答案。不吝赐教，谢谢！

**Comment by HankDevelop** [comment]
参考Readme.md中2.3 使用Java Agent来修饰JDK线程池实现类，是可以实现的

**Comment by oldratlee** [comment]
> 框架层和业务层零代码改动的基础上，可否使用TTL 

分成2部分说明

## 关于不修改业务层代码

参见文档『2.3 使用Java Agent来修饰JDK线程池实现类』

**Comment by HaojunRen** [comment]
1.registerThreadLocal，即意味着agent端还是需要去知道sdk端有多少个threadlocal对象？预先无法全局探测？
2.registerThreadLocal结束后，通过java agent命令行启动ttl agent即可，就可以达到预期对吧？
3.sdk里的threadlocal对象在ttl agent跨线程复制后，在sdk使用完毕ttl agent是否做了清除的操作

**Comment by oldratlee** [comment]
> 1\. `registerThreadLocal`，即意味着`agent`端还是需要去知道`sdk`端有多少个`threadlocal`对象？预先无法全局探测？

全局探测，或说是自动加载完成`registerThreadLocal`，这是一个集成的问题（探测/自动加载）。
\# 就像`Spring`自动扫描`Spring`配置加载`Bean。

PS：

对于『自动』这样的事，不能做的太魔法，或说 一定要有个声明的步骤，比如：添加一个用于探测的自动加载的依赖/`Jar`

@HaojunRen 欢迎一起讨论 合适又方便的解决、实现方案。

> 2. `registerThreadLocal`结束后，通过`java agent`命令行启动`ttl agent`即可，就可以达到预期对吧？

 `registerThreadLocal`操作 与 `ttl agent`的使用 是正交的：

-  `registerThreadLocal`操作，指示要做跨线程的传递。使用`TransmittableThreadLocal`类型也是这个目的。
- 使用`ttl agent`，是为了简化传递过程，简化`TtlRunable`或线程池的修饰。
    详见文档里的说明：[2. 保证线程池中传递值](https://github.com/alibaba/transmittable-thread-local#2-%E4%BF%9D%E8%AF%81%E7%BA%BF%E7%A8%8B%E6%B1%A0%E4%B8%AD%E4%BC%A0%E9%80%92%E5%80%BC)

进一步系统了解，请看  @HaojunRen ❤️ 

- 项目文档，如 [Developer Guide - 框架/中间件集成TTL传递](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
- issues
    - #128 这个库带来怎样的好处和优势？ 
    - #123 小伙伴同学们写的 TTL使用场景 与 设计实现解析的文章（写得都很好！ ）
- 源码实现

> 3. `sdk`里的`threadlocal`对象在`ttl agent`跨线程复制后，在`sdk`使用完毕`ttl agent`是否做了清除的操作

简单的回答，『无需做清除的操作』，因为在子线程中的`TTL restore`的流程方法中完成了。

进一步系统了解，请看上面给的资料 @HaojunRen ❤️

**Comment by HaojunRen** [comment]
非常感谢耐心和专业的回答，进一步请教一下，例如，我的开源：
https://github.com/Nepxion/Discovery/blob/master/discovery-plugin-strategy-starter-zuul/src/main/java/com/nepxion/discovery/plugin/strategy/zuul/wrapper/DefaultCallableWrapper.java

RequestContext.getCurrentContext()里的上下文要复制到子线程的ZuulStrategyContext.getCurrentContext()，还有StrategyTracerContext也是类似逻辑，那么在main方法，应该如何注册registerThreadLocal？谢谢

**Comment by oldratlee** [comment]
关于『如何注册`registerThreadLocal`』，
可以看一下`registerThreadLocal`的文档（如[`javadoc`](https://alibaba.github.io/transmittable-thread-local/apidocs/2.11.4/com/alibaba/ttl/TransmittableThreadLocal.Transmitter.html#registerThreadLocal(java.lang.ThreadLocal,com.alibaba.ttl.TtlCopier))）或是[单元测试中的使用代码](https://github.com/alibaba/transmittable-thread-local/blob/59dd2395d989648a800638adcae3263e5f0d5903/src/test/java/com/alibaba/ttl/threadlocal_integration/ThreadLocalIntegrationTest.kt#L66)。

---------------

几次我想看理解你的项目实现，因为要一段时间被中断了。不好意思 😅 @HaojunRen
