### ISSUE TITLE
结合spingcloud alibaba fegin调用 如何使用呢？请问可以出些example吗？

### ISSUE THREAD

**Issue by yangsen198945** [alibaba/transmittable-thread-local#172]
结合spingcloud alibaba fegin调用 如何使用呢？请问可以出些example吗？

**Comment by oldratlee** [comment]
关于开发框架或中间件的`TTL`集成 与 使用可以看看 大家这方面的方案/实现，比如

- https://github.com/Nepxion/Discovery
- https://github.com/yinjihuan/spring-cloud
- https://github.com/liuweijw/fw-cloud-framework
- https://github.com/tonyscale/micro-starters
- https://github.com/liuht777/Taroco
- https://github.com/gavenwangcn/vole
- https://github.com/siaorg/sia-gateway
- ……
