### ISSUE TITLE
TTL支持Spring的ThreadPoolTaskExecutor，如提供getTtlAsyncTaskExecutor

### ISSUE THREAD

**Issue by liauraljl** [alibaba/transmittable-thread-local#173]
我们在通过`ThreadPoolTaskExecutor`定义线程池时，想省去每次`Runnable`和`Callable`传入线程池时的修饰。

能否提供类似`getTtlExecutorService`的`getTtlAsyncTaskExecutor`方法呢？

**Comment by oldratlee** [comment]
你说的是指[`org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.html)，是吧？

目前没有直接支持，可以考虑做这个功能，发一个新版本支持。 💕 @liauraljl 

--------------

先直接解决你问题的做法是，
你可以自己先模仿[`com.alibaba.ttl.threadpool.TtlExecutors`](https://github.com/alibaba/transmittable-thread-local/blob/dfca0564ae99b6d9a7f2ae5e24f5e627626e3c6b/library/src/main/java/com/alibaba/ttl/threadpool/TtlExecutors.java#L38)自己实现一个工具类。

**Comment by superbool** [comment]
如果通过agent来增强的，是否就无需“每次Runnable和Callable传入线程池时的修饰”以及“getTtlAsyncTaskExecutor()方法“了？
看Spring的ThreadPoolTaskExecutor代码，最终还是调用的是JDK的Executor.execute。

**Comment by oldratlee** [comment]
> 如果通过agent来增强的，是否就无需“每次Runnable和Callable传入线程池时的修饰”以及“getTtlAsyncTaskExecutor()方法“了？
> 看Spring的ThreadPoolTaskExecutor代码，最终还是调用的是JDK的Executor.execute。

我做了一些简单测试：

在Agent增强的使用方式下，Spring的ThreadPoolTaskExecutor 的TTL传递是 OK的。 @liauraljl 

原因就如 @superbool 所说，Spring的ThreadPoolTaskExecutor 是 JDK的Executor来实现的。

具体可以结合你的业务 测试一下。

**Comment by liauraljl** [comment]
@oldratlee 是的，一开始我们只用了api的方式，后面使用agent方式，是不需要改造的

**Comment by liauraljl** [comment]
@superbool 我说的这个问题就是在使用api的情况下，这个是前提哈；agent是兼容的，但是毕竟涉及到应用部署方式的改造，使用代价还是比较大的，可能有些开发人员希望仅通过引入依赖便可使用ttl的功能；

我们这边链路监控，灰度，服务治理等一些功能都是通过agent方式做的，已经有一个相对完善的agent管理系统了，所以已经弃用api方式

**Comment by StephenQi0217** [comment]
我之前在项目里也遇到了类似的问题，然后自己根据ThreadPoolTaskExecutor，实现了一个TtlThreadPoolTaskExecutor。一开始想对ThreadPoolTaskExecutor底层的executorService进行包装，后来发现它未对外暴露，这个想法不成立。那我们就着手在执行时进行包装，复写它的execute(),submit()等方法。具体如下，实现起来很简单：
``` java
public class TtlThreadPoolTaskExecutor extends ThreadPoolTaskExecutor {

    /**
     * 错误提示语
     */
    private static final String ERROR_MESSAGE = "task不能为空";

    @Override
    public void execute(Runnable task) {
        super.execute(Objects.requireNonNull(TtlRunnable.get(task), ERROR_MESSAGE));
    }

    @Override
    public void execute(Runnable task, long startTimeout) {
        super.execute(Objects.requireNonNull(TtlRunnable.get(task), ERROR_MESSAGE), startTimeout);
    }

    @Override
    public Future<?> submit(Runnable task) {
        return super.submit(Objects.requireNonNull(TtlRunnable.get(task), ERROR_MESSAGE));
    }

    @Override
    public <T> Future<T> submit(Callable<T> task) {
        return super.submit(Objects.requireNonNull(TtlCallable.get(task), ERROR_MESSAGE));
    }

    @Override
    public ListenableFuture<?> submitListenable(Runnable task) {
        return super.submitListenable(Objects.requireNonNull(TtlRunnable.get(task), ERROR_MESSAGE));
    }

    @Override
    public <T> ListenableFuture<T> submitListenable(Callable<T> task) {
        return super.submitListenable(Objects.requireNonNull(TtlCallable.get(task), ERROR_MESSAGE));
    }
}
```
@oldratlee @liauraljl

**Comment by oldratlee** [comment]
目前看来`Spring的ThreadPoolTaskExecutor`可以不用额外的支持：

- `API`方式 可以用有的`TTL ExecutorService Wrapper`方法
- `Agent`方式 可以正常工作。

这个 Issue 先 close 了。

**Comment by whaceyou** [comment]
如果ThreadPoolTaskExecutor  不支持的话   下面的这个配置   在spring注入的时候 如果使用  ThreadPoolTaskExecutor  来引用启动就会报类型不匹配
![image](https://user-images.githubusercontent.com/59213102/175766054-25ccb5f2-d08c-4d82-8ad2-1cf788e8c019.png)

**Comment by oldratlee** [comment]
@whaceyou 如果要注入`ThreadPoolTaskExecutor`

- 不能用`post processor`直接处理成`(ttl)Executor`，否则自然是类型不对。
- 可以用上面 @qipengfei0217 的做法。

`TTL`的`Spring`集成，可以考虑在注入时做`wrap`处理。

**Comment by f4cklangzi** [comment]
> 如果ThreadPoolTaskExecutor 不支持的话 下面的这个配置 在spring注入的时候 如果使用 ThreadPoolTaskExecutor 来引用启动就会报类型不匹配 ![image](https://user-images.githubusercontent.com/59213102/175766054-25ccb5f2-d08c-4d82-8ad2-1cf788e8c019.png)

我试了好像这样可以
`
if (bean instanceof ThreadPoolTaskExecutor && !(bean instanceof TtlEnhanced)) {
    ThreadPoolTaskExecutor poolTaskExecutor = (ThreadPoolTaskExecutor) bean;
    poolTaskExecutor.setTaskDecorator(TtlRunnable::get);
    poolTaskExecutor.initialize();
    return poolTaskExecutor;
}
`
