### ISSUE TITLE
如何在已有的javaagent加上TTL Agent的逻辑而不用配置-Xbootclasspath/a

### ISSUE THREAD

**Issue by superbool** [alibaba/transmittable-thread-local#174]
Hello, 我在使用pinpoint，想直接在pinpoint的agent直接集成TTL Agent的agent。

尝试通过`instrumentation.appendToBootstrapClassLoaderSearch()`把`transmittable-thread-local`的包加入"bootstrap class loader"，但不生效，必须要添加`-Xbootclasspath/a`配置才行。

看文档`-Xbootclasspath/a`和`instrumentation.appendToBootstrapClassLoaderSearch()`作用是类似的，
但为什么通过`instrumentation.appendToBootstrapClassLoaderSearch()`就不行呢？

以及有什么集成在一起，简化启动命令的方式吗？

**Comment by oldratlee** [comment]
这块具体要看官方资料，比如 [`Java Agent`规范 - `JavaDoc`](https://docs.oracle.com/javase/10/docs/api/java/lang/instrument/package-summary.html#package.description)。

`instrumentation.appendToBootstrapClassLoaderSearch()`我也没有直接用过/了解过，你再根据资料并自己尝试一下吧。 :")   @superbool

**Comment by oldratlee** [comment]
@superbool 

在 『Issue #158 Error when pinpoint integrate TtlAgent | pinpoint集成TtlAgent报错』中，
有集成使用`pinpoint`，使用的问题和方式也可以与 @nepoch 交流一下 💕

**Comment by nepoch** [comment]
pinpoint\bootstrap\pom.xml文件中修改maven-jar-plugin这个插件的配置，将Boot-Class-Path修改为`<Boot-Class-Path>${project.build.finalName}.jar  boot/transmittable-thread-local-2.11.1.jar</Boot-Class-Path>`，试试看行不行，`instrumentation.appendToBootstrapClassLoaderSearch()`我也没用过~

**Comment by superbool** [comment]
> * `pinpoint\bootstrap\pom.xml`文件中修改`maven-jar-plugin`这个插件的配置
> * 将`Boot-Class-Path`修改为
>   `<Boot-Class-Path>${project.build.finalName}.jar  boot/transmittable-thread-local-2.11.1.jar</Boot-Class-Path>`
> * `boot/transmittable-thread-local-2.11.1.jar`替换成你使用`ttl`的存放路径和对应版本
> 
> 试试看行不行 @superbool
> 
> `instrumentation.appendToBootstrapClassLoaderSearch()`我也没用过~

嗯，我试试。

**Comment by Yelijah** [comment]
instrumentation.appendToBootstrapClassLoaderSearch()可以用, 但是它有个bug, classLoader.getResource("")还是无法获取到资源, 导致javassist的classPool找不到, 
解决方式: Launcher.getBootstrapClassPath().addURL之后, Launcher.getBootstrapClassPath().addURL()手动加载下就行
