### ISSUE TITLE
TransmittableThreadLocal 是否线程安全

### ISSUE THREAD

**Issue by xingguang2013** [alibaba/transmittable-thread-local#175]
如题， TransmittableThreadLocal 类是否是线程安全的？查阅资料没有找到相关说明

**Comment by oldratlee** [comment]
### 简单地回答 

`TransmittableThreadLocal`是线程安全的。 @xingguang2013 
对于涉及多线程的库来（ThreadLocal），缺省就要是线程安全必须的（否则显式声明），否则就是_**`BUG`_**！

### 更完整的回答

库的线程安全的，是以正确使用为前提的。这还要加上使用者相关知识的了解：


- 对`ThreadLocal`的了解
- 对线程安全/并发（这个是主题学习）

比如 使用`ThreadLocal`时，你把`ThreadLocal`取出来值，传到其它线程，就要注意额外的线程安全问题了。

-------------------

**更多了解`TTL`**，看`TTL`的资料/文档：  @xingguang2013   ❤️ 

- 项目文档，如 [Developer Guide - 框架/中间件集成TTL传递](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
- issues
    - #123 小伙伴同学们写的 TTL使用场景 与 设计实现解析的文章（写得都很好！ ）
    - #128 这个库带来怎样的好处和优势？ 
- 源码实现

**Comment by xingguang2013** [comment]
感谢感谢
