### ISSUE TITLE
老项目使用TTL传递context，由于没整改Runnable为TtlRunnable，导致context无法更新的问题。

### ISSUE THREAD

**Issue by tensorZhang** [alibaba/transmittable-thread-local#176]
背景：
老项目使用异步线程池的地方比较多。
当没有整改`Runnable`为`TtlRunnable`的场景，异步线程的`context`将保持创建时父线程的值，后续异步线程池执行任务都无法更新`context`。

问题：
我们使用`TransmittableThreadLocal`来传递分布式跟踪信息，这样就会导致下游跟踪信息出错。

解决思路：
当`Runnable`没有整改为`TtlRunnable`时，不传递`context`到新线程。不传比传错好。

代码修改：
重写`TransmittableThreadLocal`的`childValue`方法，返回`null`。

-----------------

1. 提问：帮忙看下这样修改代码是否可行？
2. 建议：`TTL`可以提供一种不包括`InheritableThreadLocal`功能的纯池化复用线程值传递的实现。

**Comment by oldratlee** [comment]
> 问题：
> 我们使用`TransmittableThreadLocal`来传递分布式跟踪信息，这样就会导致下游跟踪信息出错。

问题能更展开来一些说明吗？
在什么场景，期望怎么的传递，实现什么地方不对。

> 解决思路：
> 当`Runnable`没有整改为`TtlRunnable`时，不传递`context`到新线程。不传比传错好。

如果你的问题/场景 期望的是：在 **_`new Thread`_** 时，不传递不传递`context`，
那么『重写`TransmittableThreadLocal`的`childValue`方法，返回`null`』是正解。

--------------------

问一下，为什么『**_`new Thread`_** 时，不传递不传递`context`』？

对于一个上下文，**_`new Thread`_** 也应该被带过去的，因为开线程 其实可以认为 是把一个业务逻辑通过线程来并发执行。

**Comment by tensorZhang** [comment]
> 问题能更展开来一些说明吗？ @tensorZhang
> 在什么场景，期望怎么的传递，实际什么地方不对。

我们现在的场景是，中间件团队使用TransmittableThreadLocal来传递分布式跟踪信息，并向业务团队提供对应的jar包；
业务团队引用jar包，并改造业务服务的线程池（如：getTtlExecutor修饰接口Executor）。当业务服务的个别线程池没改造完的情况下，就会
导致“初次创建线程后，线程池执行任务无法更新ttl context”的问题。
当然业务服务改造完所有线程池，就没有这样的问题了。只是我们的业务服务比较有历史，有时会没改造完。


> 问一下，为什么『new Thread 时，不传递context』？ @tensorZhang
> 
> 对于一个上下文，new Thread 也应该被带过去的，因为开线程 其实可以认为 是把一个业务逻辑通过线程来多段并发执行。

new Thread我们也是需要传递context的。只是为了规避上面提到的问题，让new Thread默认不传递。只有改造了new Thread的Runnable为TtlRunnable后才传递。
----------------------
综上：这样达到的效果就是，业务服务线程(池)被改造过后才传递context；没改造就不传递context。

**Comment by oldratlee** [comment]
明白你的（实施）问题了；你说明的很清楚 👍 @tensorZhang 

------------

> 当然业务服务改造完所有线程池，就没有这样的问题了。
> 只是我们的业务服务比较有历史，有时会没改造完。
> ...
> 只是为了规避上面提到的问题，让`new Thread`默认不传递。

关于要『业务改造线程池』这个实施上的痛点，
推荐  [2.3 使用`Java Agent`来修饰`JDK`线程池实现类](https://github.com/alibaba/transmittable-thread-local/#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB) 这个`TTL`使用方式 
来解决实施中『业务改造代码』的落地痛点/难点 问题。  

`TTL Agent`很成熟 & 稳定，广泛使用，
本质上就是为了解决 这个落地痛点/难点 问题。 😄 @tensorZhang 

---------------

当然另一个更折中些的方案（**个人很不推荐** 😂） 是，重写`copy`方法加开关逻辑：

```java
TransmittableThreadLocal<Data> context = new TransmittableThreadLocal<>() {
    @Override
    public Object copy(Object parentValue) {
        final String bizFinishedTtlExecutorRewrite = System.getProperty("KEY_BIZ_FINISHED_TTL_EXECUTOR_REWRITE");
        if ("true".equalsIgnoreCase(bizFinishedTtlExecutorRewrite)) {
            return parentValue;
        } else {
            return null;
        }
    }
};
```
