### ISSUE TITLE
use PriorityBlockingQueue occur java.lang.ClassCasetException :  com.alibaba.ttl.TtlRunnable canot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by wangchongya** [alibaba/transmittable-thread-local#178]
![image](https://user-images.githubusercontent.com/8991635/85523026-03b7f500-b639-11ea-87dc-e833e14873b4.png)

**Comment by oldratlee** [comment]
这个问题 是 `PriorityBlockingQueue`的使用要求，具体看 [`PriorityBlockingQueue`的JavaDoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/PriorityBlockingQueue.html)内容：

![image](https://user-images.githubusercontent.com/1063891/85696841-de47eb80-b70b-11ea-92c3-46192d2c3b64.png)

一般`Runnable`（与`TTL`无关），往往也没有实现`Comparable`接口。

-------------

如果`TTL`修饰的业务`Runnable`已经实现了`Comparable`接口，
避免与`TTL`配合使用抛出`ClassCasetException`的一个方法是：

通过[`PriorityBlockingQueue`构造函数](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/PriorityBlockingQueue.html#%3Cinit%3E(int,java.util.Comparator))显示设置`Comparator`，以代理回业务`Runnable`的`Comparable`实现。

你的问题具体解决看`PriorityBlockingQueue`、`Comparable`、`Comparator`的相关资料，
下面只是给个示意代码：

```java
package com.alibaba.demo;

import com.alibaba.ttl.TtlUnwrap;

import java.util.Comparator;
import java.util.concurrent.PriorityBlockingQueue;

class PriorityDemo {
    public static void main(String[] args) {
        PriorityBlockingQueue<Runnable> taskQueue = new PriorityBlockingQueue<>(
                128,
                Comparator.comparingInt(task -> {
                    // 确定Runnable 一定是 PriorityTask 类型
                    final PriorityTask t = (PriorityTask) TtlUnwrap.unwrap(task);
                    return t.getPriority();
                })
        );

        // 提交到PriorityBlockingQueue的任务 都是 PriorityTask 类型
        taskQueue.put(new PriorityTask(10));
        taskQueue.put(new PriorityTask(5));
        taskQueue.put(new PriorityTask(1));

        for (Runnable runnable : taskQueue) {
            runnable.run();
        }
        // 输出：1, 5, 10
    }

    static class PriorityTask implements Runnable {
        private final int priority;

        public PriorityTask(int priority) {
            this.priority = priority;
        }

        public int getPriority() {
            return priority;
        }

        @Override
        public void run() {
            System.out.println("priority: " + priority);
        }
    }
}
```

**Comment by wangchongya** [comment]
think you

**Comment by oldratlee** [comment]
`TTL`提供了通用实现，没有改`TTL`的核心类（如`TtlRunnable`）。发布了`v2.12.3-RC1`：  @wangchongya
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.3-RC1

------------

更多讨论 参见：

- #330
