### ISSUE TITLE
文档中的『JavaAgent加载机制分析』链接已失效

### ISSUE THREAD

**Issue by liauraljl** [alibaba/transmittable-thread-local#179]
`transmittable-thread-local/docs/developer-guide.md`页面底部 “JavaAgent加载机制分析”跳转内容有误，请核实

链接：
https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#java-agent%E6%96%B9%E5%BC%8F%E5%AF%B9%E5%BA%94%E7%94%A8%E4%BB%A3%E7%A0%81%E6%97%A0%E4%BE%B5%E5%85%A5

**Comment by liauraljl** [comment]
好的👌🏻




| |
李金雷
|
|
邮箱：liaura_ljl@163.com
|

签名由 网易邮箱大师 定制

在2020年06月25日 15:27，李鼎(哲良) 写道：

链接已经失效了：
http://alipaymiddleware.com/jvm/javaagent%E5%8A%A0%E8%BD%BD%E6%9C%BA%E5%88%B6%E5%88%86%E6%9E%90/

找了一下，这个链接是好的：
JavaAgent加载机制分析
https://www.iteye.com/blog/nijiaben-1847212

@liauraljl 方便给Pull Request 修复一下吗？ :")
这样大家 能直接从 工程的提交日志 中 看到你 ♥️

**Comment by oldratlee** [comment]
Fix in PR #180 From @liauraljl
