### ISSUE TITLE
请教2个问题。1.关于restore方法  2.关于Snapshot类

### ISSUE THREAD

**Issue by alexkuku** [alibaba/transmittable-thread-local#190]
问题一：
我们使用ttl的场景是用来做链路追踪，每个request都会在当前线程生成一个trace id，存放进ttl里，进而传递给子线程。这种情况下似乎restore操作没有什么意义，是否可以省略restore操作？

问题二：
TransmittableThreadLocal.Transmitter.Snapshot这个类里，有2个属性，分别是ttl2Value和 threadLocal2Value。使用ttl时，都是围绕着备份和传递ttl2Value这个属性。这个时候，threadLocal2Value存在的意义是什么呢？

**Comment by oldratlee** [comment]
> 问题一：
> 我们使用ttl的场景是用来做链路追踪，每个request都会在当前线程生成一个trace id，存放进ttl里，进而传递给子线程。这种情况下似乎restore操作没有什么意义，是否可以省略restore操作？

对于你这个具体场景是，『省略restore操作』不能有功能上的问题（或说`Bug`）。
当然从性能上来看，尽早的释放 对 内存/`GC`是更优的。

对于通用场景（比如不是每次都设置的场景）来说，如果不清理会上下文污染的问题了（这样的`Bug`）线上屡见不鲜。

PS: 相关/类似问题的Issue：
- #145 『把之前的 TransmittableThreadLocal restore回来有什么意义？』
- #134 关于clean extra TTL value的疑问 

----------------------

> 问题二：
> TransmittableThreadLocal.Transmitter.Snapshot这个类里，有2个属性，分别是ttl2Value和 threadLocal2Value。使用ttl时，都是围绕着备份和传递ttl2Value这个属性。这个时候，threadLocal2Value存在的意义是什么呢？

参见 Issue 
#155 Transmitter类中的一个WeakHashMap<ThreadLocal<Object>, TtlCopier<Object>>的变量threadLocalHolder有什么用 

> 用于功能『集成`ThreadLocal`』
> 
> 更多说明参见：
> 
> - `Transmitter`代码上的 Javadoc
> https://alibaba.github.io/transmittable-thread-local/apidocs/2.11.5/com/alibaba/ttl/TransmittableThreadLocal.Transmitter.html
> ![image](https://user-images.githubusercontent.com/1063891/69710907-29305f00-113b-11ea-9b62-48db104cfdcd.png)
> - Issue: ThreadLocal integration #130

-------------------

更多了解可以看一下`TTL`的资料/文档：  @alexkuku    ❤️ 

- 项目文档，如 [Developer Guide - 框架/中间件集成TTL传递](https://github.com/alibaba/transmittable-thread-local/blob/master/docs/developer-guide.md#-%E6%A1%86%E6%9E%B6%E4%B8%AD%E9%97%B4%E4%BB%B6%E9%9B%86%E6%88%90ttl%E4%BC%A0%E9%80%92)
- issues
    - #123 小伙伴同学们写的 TTL使用场景 与 设计实现解析的文章（写得都很好！ ）
    - #128 这个库带来怎样的好处和优势？ 
- 源码实现

**Comment by alexkuku** [comment]
好的，看明白了，多谢！
