### ISSUE TITLE
TtlExecutors怎么没有包装forkjoinpool的方法

### ISSUE THREAD

**Issue by wjk2018** [alibaba/transmittable-thread-local#200]

**Comment by oldratlee** [comment]
@wjk2018  `TransmittableThreadLocal`实现了对`ForkJoinPool`支持：

1. 通过包装`TtlRecursiveAction`与`TtlRecursiveTask`
  Demo代码参见 [`TtlForkJoinTaskDemo.kt`](https://github.com/alibaba/transmittable-thread-local/blob/4d8d31984e7c3a6bd9a34d967153a23824ba16bf/src/test/java/com/alibaba/demo/ttl/TtlForkJoinTaskDemo.kt#L16-L24)
2. 通过[使用`Java Agent`来修饰`JDK`线程池实现类](https://github.com/alibaba/transmittable-thread-local#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB)

### 为什么没有支持`ForkJoinPool`包装？

因为`ForkJoinPool`的功能不是以接口/语义方式提供的。
更多说明参见

- Issue #76 ：
    > ForkJoinTask.exec() 是抽象类方法，不好包装.
    > ForkJoinWorkerThread.afterTopLevelExec() 限制包内访问，而且runTask()没有类似beforeTopLevelExec()的方法和执行点。
以上是我分析过程的思路和遇到的问题记录下.
- PR #82
