### ISSUE TITLE
Java Agent 使用方式 与 显式的使用方式 混用时，会有问题吗？

### ISSUE THREAD

**Issue by goldpumpkin** [alibaba/transmittable-thread-local#202]

**Comment by oldratlee** [comment]
`TransmittableThreadLocal`的三类使用方式：

1. 修饰执行对象（如`Runnable`）
2. 修饰执行器（如线程池）
3. 使用`Java Agent`增强（透明修饰）的执行器（如线程池）

### 可以混用的，不会有问题。

####  不同使用方式的混用，在设计实现`TransmittableThreadLocal`之初就有关注的。

@goldpumpkin 有关注这个问题，COOL 👍     一般用户不会在意。

--------------------

简单说明一下实现『不同使用方式 **_协同_**』的思路（具体你可以看实现代码来深入了解）：

- 对于修饰过的 或 `Java Agent`增强的线程池：
    - 如果提交的`Runnable`已经修改过了，不会再去修改（因为是知道是`TtlRunnable`）。
    - 即 `3` 、`2` 对 `1` 做了 混用支持 
- 如果 开启了 `Java Agent`增强线程池：
    - 则 修饰线程池 的方法 不会再对线程池 做修饰
    - `2` 对 `3` 做了 混用支持

**Comment by goldpumpkin** [comment]
谢谢回复。但是如果 Agent方式 和 显示的版本不一致，应该会出现问题吧

**Comment by oldratlee** [comment]
`Java Agent`是加载在`JVM bootstrap classpath`上的，即应用里的不会生效。
\# 更多信息可以了解 `Classpath/ClasspLoader`。


### PS

版本不一致（`Java`里对应`Jar Hell`），是所有语言/技术栈依赖的公共问题，会潜在影响所有功能（不仅是`TransmittableThreadLocal`不同使用方式的问题）
