### ISSUE TITLE
关于TtlForkJoinTransformlet中直接修改ForkJoinTask的实现

### ISSUE THREAD

**Issue by Yelijah** [alibaba/transmittable-thread-local#205]
因为一些特殊原因, 必须要运行时动态`agent`，现已基本完成。

但是`java.lang.instrument.Instrumentation#retransformClasses`不支持在`transform`中为`ForkJoinTask`添加`fields`:

![image](https://user-images.githubusercontent.com/33784573/93425081-de5f1e00-f8eb-11ea-8e1b-82ca8acb199f.png)
![image](https://user-images.githubusercontent.com/33784573/93423471-9ee30280-f8e8-11ea-832d-ddc7745e2266.png)

----------------

Q1. 不知能否改写TtlForkJoinTransformlet, 使其不直接修改ForkjoinTask, 转而修改ForkJoinPool?
Q2. 并且TtlCallable和TtlRunnable都是通过包装类形式实现, 为何TtlRecursiveTask会是抽象类实现?

**Comment by oldratlee** [comment]
> 但是`java.lang.instrument.Instrumentation#retransformClasses`不支持在`transform`中为`ForkJoinTask`添加`fields`:

关于`retransformClasses`，我也没有使用过。

添加`fields`，可能和`Agent`的设置有关系。
你可以试试：改一下`TTL`并打包`TTL`  @Yelijah 

https://github.com/alibaba/transmittable-thread-local/blob/06ec7da538f5c0e909883f6f6d207d0dd35d2ad2/pom.xml#L268-L272

PS： 关于运行时动态加载`Agent`的Issue：支持运行时加载TTL agent #169

> 因为一些特殊原因, 必须要运行时动态`agent`

能展开来说一下你的需求场景、问题吗？
也能让更多的人了解到。

**Comment by Yelijah** [comment]
需要动态agent的场景是：
To B的web应用，需要适配多种web容器环境，让客户自行去加启动参数，比较不可控

**Comment by oldratlee** [comment]
> 需要动态agent的场景是：
> 
> * To B的web应用，需要适配多种web容器环境
> * 让客户自行去加启动参数，比较不可控

以避免业务代码的修改，让像中间件基础这类的解决方案对业务透明（如`Skywalking`、`Promethues`），
使用`Java Agent`类加强的方式，是业界 比较常见与主流的方式。

很难有其它更好的 透明技术方案，当然对应要做的是配置`JVM`的启动参数；
相对各个升级改动业务代码，`Agent`方案还相对实施成本还是比较低的。

也期望业界 能找到 更简单（如 无需`JVM`启动参数）的解决方式。 😁    @Yelijah

**Comment by Yelijah** [comment]
Thanks！
