### ISSUE TITLE
使用2.11.4版本依然存在线程池场景下ThreadLocal无法重新传递问题

### ISSUE THREAD

**Issue by liauraljl** [alibaba/transmittable-thread-local#208]
我们使用的是2.11.4版本，最近发现依然存在线程池场景下ThreadLocal无法重新传递问题，是否与WeakHashMap有关呢？是否需要升级到2.11.5版本呢？

**Comment by liauraljl** [comment]
问题已解决，主要原因是我们的javaagent和Tomcat应用中都引用到了ttl，而Tomcat的类加载器不遵循双亲委派，加载了两份ttl

**Comment by oldratlee** [comment]
> 是否需要升级到2.11.5版本呢？

要升级。 @liauraljl 

在Release Note 已说明：

> https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.11.5
>
> ## Bug Fix ‼️
>
> - fix bug: WeakHashMap in Snapshot led to captured values GCed before replay unexpectedly
>    - Rollback "use WeakHashMap instead of HashMap for capture/backup snapshot" in **_`v2.11.0`_**
>    - Affect versions **_`v2.11.0 ~ v2.11.4`_**, **DO NOT** use these versions‼️

**Comment by liauraljl** [comment]
> > 是否需要升级到2.11.5版本呢？
> 
> 要升级。 @liauraljl
> 
> 在Release Note有说明：
> 
> > https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.11.5
> > ## Bug Fix ‼️
> > 
> > * fix bug: WeakHashMap in Snapshot led to captured values GCed before replay unexpectedly
> >   
> >   * Rollback "use WeakHashMap instead of HashMap for capture/backup snapshot" in **_`v2.11.0`_**
> >   * Affect versions **_`v2.11.0 ~ v2.11.4`_**, **DO NOT** use these versions‼️
