### ISSUE TITLE
使用问题：线程池中使用parallelStream时，有时获取不到值出NPE

### ISSUE THREAD

**Issue by dalaoyang** [alibaba/transmittable-thread-local#216]
如题，有人遇到类似情况吗

**Comment by oldratlee** [comment]
首先，确认使用可用的版本，比如最新版本`2.11.5`，更多参见Release note https://github.com/alibaba/transmittable-thread-local/releases 。

给一下可运行极简复现的问题的UT单测/demo， @dalaoyang 可以fork工程加代码
这样可以分离是使用问题，还是TransmittableThreadLocal的问题。

**Comment by oldratlee** [comment]
首先，确认使用可用的版本，比如最新版本`2.11.5`，更多参见Release note https://github.com/alibaba/transmittable-thread-local/releases 。

给一下可运行极简复现的问题的UT单测/demo， @dalaoyang 可以fork工程加代码
这样可以分离是使用问题，还是TransmittableThreadLocal的问题。
