### ISSUE TITLE
请问此探针与 pinpoint 探针是否兼容?

### ISSUE THREAD

**Issue by DC-ET** [alibaba/transmittable-thread-local#225]
如题

**Comment by oldratlee** [comment]
`PinPoint`我这边没有使用。

有Issue提过，一起使用 `TransmittableThreadLocal`与`PinPoint`。
你可以 实际使用验证一下。

> Issue #158 ：Error when pinpoint integrate TtlAgent | pinpoint集成TtlAgent报错 
>
> nepoch commented on 12 Dec 2019
> 
> @nepoch 使用新版本测试一下，是不是 OK了？ 
>
> @oldratlee 更新后测试正常，谢谢啦。

另外，
 #174 如何在已有的javaagent加上TTL Agent的逻辑而不用配置-Xbootclasspath/a

**Comment by oldratlee** [comment]
2个`Agent`（`TTL Agent` + `PinPoint Agent`）应该是没有问题。  @DC-ET 

如果有问题，注意 https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-739469983 中所说的：
> ### 我们目前的解决方案是
> 把`TTL agent`放在最前位置，可以保证`TTL agent` 正常工作。
> 已在开发、测试环境得到验证。
