### ISSUE TITLE
Wrap线程池的使用方式会抛Already TtlCallable异常

### ISSUE THREAD

**Issue by 313598612** [alibaba/transmittable-thread-local#228]
Already TtlCallable线程池调用出现这个错误，怎么解决啊？

**Comment by oldratlee** [comment]
是这个问题吗？

> the wrapper Executor can be cooperated with the usage of "Decorate Runnable and Callable". 

用新版本： @313598612 😀
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.0

**Comment by 313598612** [comment]
<img width="1475" alt="微信图片_20201223195729" src="https://user-images.githubusercontent.com/39404386/102993980-2334c980-4559-11eb-90c9-fb7535b9ead2.png">
<img width="1128" alt="微信图片_20201223195720" src="https://user-images.githubusercontent.com/39404386/102993984-24fe8d00-4559-11eb-9650-c001bfe7df9d.png">

**Comment by 313598612** [comment]
上面是使用方式，包装后就按java普通的线程池使用了。
下面的TtlCallable这个类报的错误    这个怎么解决啊？还是说使用方式不正确

**Comment by oldratlee** [comment]
> 用新版本，你验证一下： @313598612 😀
> https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.0

升级到 `v2.12.0`版本，这个版本解决的是：
Wrap 线程池的使用方式（即你上面用的使用方式），抛`Already TtlCallable`异常的问题。

你升级版本到`v2.12.0`，验证一下 @313598612


---------------------

如果还有问题，给一下极简、可运行复现问题的Demo 🙏：

- 在Github建一个Demo Repo
- 方便我跟进排查

谢谢 😄
