### ISSUE TITLE
使用-javaagent，在直接使用new Thread(new Runnable() {……}).start();时， copy方法、beforeExecute/afterExecute方法将不会执行。

### ISSUE THREAD

**Issue by WYongLin** [alibaba/transmittable-thread-local#229]
使用`-javaagent`，在直接使用`new Thread(new Runnable() {……}).start();`时，
`copy`方法、`beforeExecute`/`afterExecute`方法将不会执行。

这个独立线程对这三个方法的支持，未来有计划支持吗？

**Comment by oldratlee** [comment]
说一下这样用法的实际需求场景吗？😀 @WYongLin

**Comment by oldratlee** [comment]
先 close 这个 issue。

如果 大家有场景/需求 ，欢迎继续 评论、讨论，并 reopen。
