### ISSUE TITLE
Java Agent 使用方式 与 显式的使用方式 混用时，在tomcat下出现失效情况

### ISSUE THREAD

**Issue by codingPao** [alibaba/transmittable-thread-local#231]
定位了一下发现原因是：

- `tomcat`的`WebappClassLoader`打破了双亲委托机制
- `com.alibaba.ttl.TransmittableThreadLocal.holder`会在`WebappClassLoader`中初始化一份；在做TTL操作时，TTL的引用由这个 **_`holder`_** 持有。
- 在`submit`时，`TtlRunnable`虽然走了增强，但是`copy`操作的是由`BootstrapClassLoader`初始化的`com.alibaba.ttl.TransmittableThreadLocal.holder`进行`copy`，没有`copy`到预期的TTL。

**Comment by codingPao** [comment]
tomcat版本是8.0.22

**Comment by codingPao** [comment]
private static final TransmittableThreadLocal<String> TRANSMITTABLE_CONTEXT = new TransmittableThreadLocal();

public void test() {
    TRANSMITTABLE_CONTEXT.set("Test");
    ExecutorService e = Executors.newFixedThreadPool(1);
    e.submit(() -> log.info("init thread"));
    e.submit(() -> {
        final String test = TRANSMITTABLE_CONTEXT.get();
        log.info("TTL:{}", test);
    });
}
这是我的demo

**Comment by oldratlee** [comment]
> `tomcat`的`WebappClassLoader`打破了双亲委托机制

`tomcat`的`WebappClassLoader`双亲委托机制应该是可以配置的，比如`JDK`标准类（如`String`）不会打破，否则也会有各种问题。

你找一下 `tomcat`的`WebappClassLoader`双亲委托的配置的方式，将TTL的包`com.alibaba.ttl`配置成走双亲委托，来解决问题。 @codingPao 
（Java Agent方式使用TTL时，TTL应该与`JDK`标准类是一样的ClassLoader方式）  

有了结果反馈一下 :")

**Comment by codingPao** [comment]
目前能想到得有两个解决方式：
* 调整`tomcat`配置
* 增强`tomcat`得`WebappClassLoader`

如果调整tomcat配置，可以参考https://tomcat.apache.org/tomcat-8.0-doc/class-loader-howto.html
If the web application class loader is configured with <Loader delegate="true"/> then the order becomes:
* Bootstrap classes of your JVM
* System class loader classes (described above)
* Common class loader classes (described above)
* /WEB-INF/classes of your web application
* /WEB-INF/lib/*.jar of your web application

但是这样调整得代价就是修改了整个`tomcat`得加载顺序，而`tomcat`目前也没有找到类似`jboss`得`Djboss.modules.system.pkgs`配置
于是我们翻阅了`tomcat`得`WebappClassLoader`源码，以下是`tomcat 8.5.30`版本
`org.apache.catalina.loader.WebappClassLoaderBase#loadClass(java.lang.String, boolean)`
`org.apache.catalina.loader.WebappClassLoaderBase#filter(java.lang.String, boolean)`
``` java
public Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
    /**
     * 忽略一部分
     */
      boolean delegateLoad = delegate || filter(name, true);
    /**
     * 忽略一部分
     */
}

protected boolean filter(String name, boolean isClassName) {

        if (name == null)
            return false;

        char ch;
        if (name.startsWith("javax")) {
            /* 5 == length("javax") */
            if (name.length() == 5) {
                return false;
            }
            ch = name.charAt(5);
            if (isClassName && ch == '.') {
                /* 6 == length("javax.") */
                if (name.startsWith("servlet.jsp.jstl.", 6)) {
                    return false;
                }
                if (name.startsWith("el.", 6) ||
                    name.startsWith("servlet.", 6) ||
                    name.startsWith("websocket.", 6) ||
                    name.startsWith("security.auth.message.", 6)) {
                    return true;
                }
            } else if (!isClassName && ch == '/') {
                /* 6 == length("javax/") */
                if (name.startsWith("servlet/jsp/jstl/", 6)) {
                    return false;
                }
                if (name.startsWith("el/", 6) ||
                    name.startsWith("servlet/", 6) ||
                    name.startsWith("websocket/", 6) ||
                    name.startsWith("security/auth/message/", 6)) {
                    return true;
                }
            }
        } else if (name.startsWith("org")) {
            /* 3 == length("org") */
            if (name.length() == 3) {
                return false;
            }
            ch = name.charAt(3);
            if (isClassName && ch == '.') {
                /* 4 == length("org.") */
                if (name.startsWith("apache.", 4)) {
                    /* 11 == length("org.apache.") */
                    if (name.startsWith("tomcat.jdbc.", 11)) {
                        return false;
                    }
                    if (name.startsWith("el.", 11) ||
                        name.startsWith("catalina.", 11) ||
                        name.startsWith("jasper.", 11) ||
                        name.startsWith("juli.", 11) ||
                        name.startsWith("tomcat.", 11) ||
                        name.startsWith("naming.", 11) ||
                        name.startsWith("coyote.", 11)) {
                        return true;
                    }
                }
            } else if (!isClassName && ch == '/') {
                /* 4 == length("org/") */
                if (name.startsWith("apache/", 4)) {
                    /* 11 == length("org/apache/") */
                    if (name.startsWith("tomcat/jdbc/", 11)) {
                        return false;
                    }
                    if (name.startsWith("el/", 11) ||
                        name.startsWith("catalina/", 11) ||
                        name.startsWith("jasper/", 11) ||
                        name.startsWith("juli/", 11) ||
                        name.startsWith("tomcat/", 11) ||
                        name.startsWith("naming/", 11) ||
                        name.startsWith("coyote/", 11)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }
```
基于以上可以看出`tomcat`对于例如`servlet-api.jar`等资源加载过滤逻辑。
因为我们目前研发了一个基于`agent`得插件平台，可以动态下发增强逻辑，所以我们增强了一下`org.apache.catalina.loader.WebappClassLoaderBase`得filter方法过滤逻辑，`name`以`com.alibaba.ttl`或`com/alibaba/ttl`开头得返回`true`，让`bootstrapclassloader`负责加载`TTL`相关类。这样子`JVM`中只会初始化一份`TTL`,解决了我们目前遇到得失效问题。

**Comment by oldratlee** [comment]
> 因为我们目前研发了一个基于`agent`得插件平台，可以动态下发增强逻辑，
> 所以我们增强了一下`org.apache.catalina.loader.WebappClassLoaderBase`得filter方法过滤逻辑，
> `name`以`com.alibaba.ttl`或`com/alibaba/ttl`开头得返回`true`，让`bootstrapclassloader`负责加载`TTL`相关类。
> 这样子`JVM`中只会初始化一份`TTL`，解决了我们目前遇到得失效问题。

@codingPao 那这个 Issue 先 close 了，后续有什么欢迎继续讨论。

**Comment by xingwenyang** [comment]
@oldratlee 能分享下这个修复方案的源码在哪个项目中能看到吗

**Comment by oldratlee** [comment]
> @oldratlee 能分享下这个修复方案的源码在哪个项目中能看到吗

`Tomcat`的修改与配置 @codingPao 的实现解决的。 @xingwenyang 

@codingPao 可以交流 回答一下 😃❤️
