### ISSUE TITLE
想在子线程中获取执行该子线程的父方法 transmittable-thread-local 有办法做到吗

### ISSUE THREAD

**Issue by scp114514810** [alibaba/transmittable-thread-local#244]
假设有两个方法被放在同一个循环体内：

```java
public void circleCreate(){
    for (int i=0;i<10000;i++){
        a();
        e();
    }
}

public void a(){
    executorService.execute(new Runnable() {
        @Override
        public void run() {
            B b = new B();
            b.b();
        }
    });
}

public void e(){
    executorService.execute(new Runnable() {
        @Override
        public void run() {
            B b = new B();
            b.b();
        }
    });
}
```

某一时刻想知道线程池中的某个线程是`a()`方法的还是`e()`方法的，该怎么办呢？

transmittable-thread-local 可以做到吗？

**Comment by oldratlee** [comment]
个人的第一感觉是：这种情况，推荐 在业务里逻辑的方式来表达，比如

- `run`不同的Task类型
- 用不同的方法（即有业务语义的API）来区分，而不是让使用方式直接调用`executorService.execute`
- 等等

不要通过下层技术的方式来猜，感觉总有一天会出错的（即**不安全**）。

---------------

当然你可以说明一下 更多的业务场景，可以：  @scp114514810 

- 结合业务场景，给出 通用安全的做法
- 结合业务场景，给出 面向业务语义 清楚简单的做法（即不需要通用）
