### ISSUE TITLE
异步线程中修改ThreadLocal值，主线程也会被修改？（DB Session传递场景）

### ISSUE THREAD

**Issue by wuwu20048** [alibaba/transmittable-thread-local#253]
在`DAO`层，我在`ThreadLocal`上下文中，会存放数据库`Session`。

发现替换为`TransmittableThreadLocal`后，使用`agent`方式。
在多线程场景下，对`session`的操作会影响到主线程，比如说取不到`session`，或者`session`已关闭。

请问支持这种场景吗，还是只能使用值传递，还不能对其进行修改操作？

**Comment by oldratlee** [comment]
## 关于 『维护传递对象有效』

> 发现替换为`TransmittableThreadLocal`后，使用`agent`方式。
> 在多线程场景下，对`session`的操作会影响到主线程，比如说取不到`session`，或者`session`已关闭。

`TransmittableThreadLocal`的完成功能的是，异步对象（或说上下文）的传递。

其中 传递对象（如`session`对象） 的生命周期，由 2个或多个协作线程的逻辑 来决定；
作为只传递对象的`TransmittableThreadLocal`并不能决定，在传递过程中，维护这个对象 是有效的。 @wuwu20048 
（因为没有维护传递有效性的逻辑，作为底层库也期望 耦合 『维护传递对象有效』这样的逻辑）

以`DB session`对象为例来说明，如果传递的`DB session`对象没有一些逻辑来维护是有效性，
那么在另一个线程使用`DB session`对象时，就可能是已经关闭了。这个情况与是否使用`TransmittableThreadLocal`无关。

## 关于『传递对象』是否可修改

如果传递是对象引用，是可以修改的。如果业务逻辑修改，则业务逻辑要注意传递对象的线程安全问题。 @wuwu20048 

这点在 [User Guide 文档](https://github.com/alibaba/transmittable-thread-local#-user-guide)中有说明：

> 1. `copy`方法  
>     用于定制 **任务提交给线程池时** 的`ThreadLocal`值传递到 **任务执行时** 的拷贝行为，缺省传递的是引用。  
>     注意：如果跨线程传递了对象引用因为不再有线程封闭，与`InheritableThreadLocal.childValue`一样，使用者/业务逻辑要注意传递对象的线程安全。
