### ISSUE TITLE
关于backup&restore的疑惑

### ISSUE THREAD

**Issue by zysaaa** [alibaba/transmittable-thread-local#256]
我使用的是`2.10.2`版本，在看这块代码以及看网上一些源码分析的文章，提到这一块是为了执行结束后重置这个线程原先的`TTL`值，避免丢失，我写了如下的测试代码:

```java
private static TransmittableThreadLocal<String> transmittableThreadLocal = new TransmittableThreadLocal();
private static ThreadLocal<String> threadLocal = new ThreadLocal();
private static ExecutorService executorService = TtlExecutors.getTtlExecutorService(Executors.newFixedThreadPool(1));

public static void main(String[] args) throws InterruptedException {
    executorService.submit(() -> {
        threadLocal.set("threadlocal");
        transmittableThreadLocal.set("transmittableThreadLocal");
    });
    executorService.submit(() -> {
        System.out.println(threadLocal.get());  // output threadlocal
        System.out.println(transmittableThreadLocal.get()); // output null
    });
}
```

线程池中只有一个`worker`，在`submit`第一个任务的时候往`transmittableThreadLocal` `set`了一个值，

- **在这个任务触发前**，显然，`backup`的值是一个空`map`，然后执行过程中塞了一个值到`transmittableThreadLocal`里。
- **任务执行结束后**，此时由于`restore`机制会将这个`worker`里的刚刚塞的值清空，导致`submit`第二个任务的时候`transmittableThreadLocal.get()`输出为空了，
   但是自始至终这是同一个`worker`线程，使用普通的`threadLocal`是能够打印出来第一次`submit`过程中设置的值的。

我有些不理解这个`backup & restore`机制，是我哪里理解错了吗? 
我也看到作者有提到这种一般适用于 线程池满了 且 线程池使用的是『`CallerRunsPolicy`』，方便能举个代码的例子吗？

**Comment by oldratlee** [comment]
> 线程池中只有一个`worker`，在`submit`第一个任务的时候往`transmittableThreadLocal` `set`了一个值，
> 
> * **在这个任务触发前**，显然，`backup`的值是一个空`map`，然后执行过程中塞了一个值到`transmittableThreadLocal`里。
> * **任务执行结束后**，此时由于`restore`机制会将这个`worker`里的刚刚塞的值清空，导致`submit`第二个任务的时候`transmittableThreadLocal.get()`输出为空了，
>   但是自始至终这是同一个`worker`线程，使用普通的`threadLocal`是能够打印出来第一次`submit`过程中设置的值的。

对你说的这个具体场景，有下面的约束：

1. 只有**一个**`Worker`线程的线程池
2. 业务逻辑 保证了 2个`Runnable`异步任务的时序
3. 且2个任务之间有**全局**交互
    - **全局**交互 是指：通过`ThreadLocal`在**一个**线程来全局读取，这是`ThreadLocal`的目标场景。

@zysaaa
如果你的业务场景满足上面约束是，是够用/合用的，
那么用`ThreadLocal`（而不是`TransmittableThreadLocal`）就好，而且可能更简单。

只用一个线程的线程池，对于很多场景是不够用的（比如，为了业务并发处理的扩展性/性能），这时可以使用`TransmittableThreadLocal`。

### 相关的Issue/文档

- #201 能在详细讲解一下replay、restore的设计理念吗？没有思考明白，为什么还需要有恢复步骤 
- #145 没有特别理解 capture replay restore 这样的方式的好处？
- 文档 [使用`TTL`的好处与必要性](https://github.com/alibaba/transmittable-thread-local#-%E4%BD%BF%E7%94%A8ttl%E7%9A%84%E5%A5%BD%E5%A4%84%E4%B8%8E%E5%BF%85%E8%A6%81%E6%80%A7)

这些Issue与文档中，有展开的说明。
