### ISSUE TITLE
TTL Agent使用方式下，业务代码是否需要依赖TTL Jar？

### ISSUE THREAD

**Issue by wuguanyu** [alibaba/transmittable-thread-local#258]
如果服务增加`agent`方式增加了`TTL`，那么业务代码是不是还是依赖`transmittable-thread-local`的`jar`吗？
因为需要使用`TransmittableThreadLocal`。

如果是，那么`ttl agent jar`的版本 和业务放自行依赖的`transmittable-thread-local jar`有什么要求是必须一致吗？

**Comment by wuguanyu** [comment]
好像因为 agent是在 bootstrap classloader先加载 自己服务依赖是不是不大重要

**Comment by oldratlee** [comment]
关于 
- `TTL Agent`使用方式下，应用是否还需要`TTL Jar`的问题
- 及其 版本问题

在『Issue  #202 Java Agent 使用方式 与 显式的使用方式 混用时，会有问题吗？』已经讨论与回答过了： @wuguanyu 

### 如果服务增加`agent`方式增加了`TTL`，那么业务代码是不是还是依赖`transmittable-thread-local`的`jar`吗？

`TTL Agent`使用方式下，应用可以不需要依赖`TTL Jar`了。

### `agent jar ttLagent`的版本 和业务放自行依赖的`transmittable-thread-local jar`有什么要求是必须一致吗？

`TTL Agent`使用方式下，生效的是 `JVM bootstrap classpath`/`TTL Agent`上 配置的 `TransmittableThreadLocal Jar`。

> ### 先说明基础的信息
> * 对于`Java Agent`的使用方式，
>   `TransmittableThreadLocal Jar`是加载在`JVM bootstrap classpath`上的：
>   
>   * 应用`classpath`的`TransmittableThreadLocal Jar`/依赖不会生效的。
>     （实际上，应用的运行依赖没有`TransmittableThreadLocal Jar`，也没有关系。）
>   * # 更多信息可以了解 `JVM ClassLoader`的资料，比如[`repo oldratlee/classloader-playground`](https://github.com/oldratlee/classloader-playground)
> * `TransmittableThreadLocal`设计实现之初，关注了 **_版本兼容性_**，即
>   即升级到高版本`TransmittableThreadLocal`时，使用低版本`TransmittableThreadLocal`的业务代码无需修改。
>
> https://github.com/alibaba/transmittable-thread-local/issues/202#issuecomment-689989679 ：

---------------

看看上面的说明清楚吗？欢迎继续讨论～

**Comment by wuguanyu** [comment]
![image](https://user-images.githubusercontent.com/24486917/112627607-cead2d00-8e6c-11eb-908d-9a396c50b246.png)
主要是看到这个文档 感觉业务放还需要 使用 TransmittableThreadLocal ,我需要进入看一下如何实现的 
感觉回答
@oldratlee

**Comment by wuguanyu** [comment]
@oldratlee 我感觉有个问题 特别傻 但是我还是多问一下 如果使用agent方式 注入ttl, 
业务不依赖TransmittableThreadLocal
因为我看流程上 业务放是要使用TransmittableThreadLocal 才能传递传递跨线程的上下文
![Uploading image.png…]()

**Comment by wuguanyu** [comment]
![image](https://user-images.githubusercontent.com/24486917/113094474-5061d980-9224-11eb-9ab4-9171354a2b09.png)
看这个demo 最起码 业务在编译阶段还是引入 ttlAgent jar报 因为要显示使用 TransmittableThreadLocal

**Comment by oldratlee** [comment]
> 看这个demo 最起码 业务在编译阶段还是引入 ttlAgent jar报 因为要显示使用 TransmittableThreadLocal

嗯，编译时 要的。

`TTL Agent`使用方式下，应用**运行时**可以不需要依赖`TTL Jar`了。
\# 应用代码**编译时**，肯定是要有依赖`TTL Jar`，否则编译过不了。

**Comment by wuguanyu** [comment]
@oldratlee 收到
