### ISSUE TITLE
Runnable->TtlRunnable使用问题（没有得到期望值）

### ISSUE THREAD

**Issue by xiaospace1028** [alibaba/transmittable-thread-local#259]
修改`Runnable`->`TtlRunnable`

```java
InheritableThreadLocal local = new InheritableThreadLocal();
TransmittableThreadLocal transLocal = new TransmittableThreadLocal();
ExecutorService fixedThreadPool = Executors.newFixedThreadPool(1);

local.set("local--初始化");
transLocal.set("transLocal--初始化");

String name = Thread.currentThread().getName();
Runnable task = () -> {
    String name1 = Thread.currentThread().getName();
    Object o = local.get();
    Object transO = transLocal.get();
    System.out.println(name1 + ":local" + o);
    System.out.println(name1 + ":transLocal" + transO);
};
TtlRunnable ttlRunnable = TtlRunnable.get(task);
fixedThreadPool.submit(ttlRunnable);

local.set("local--修改");
transLocal.set("transLocal--修改");
fixedThreadPool.submit(ttlRunnable);
```
结果：

```
pool-1-thread-1:locallocal--初始化
pool-1-thread-1:transLocaltransLocal--初始化
pool-1-thread-1:locallocal--初始化
pool-1-thread-1:transLocaltransLocal--初始化
```

------------------

修改线程池

```java
InheritableThreadLocal local = new InheritableThreadLocal();
TransmittableThreadLocal transLocal = new TransmittableThreadLocal();
ExecutorService fixedThreadPool = Executors.newFixedThreadPool(1);

local.set("local--初始化");
transLocal.set("transLocal--初始化");
fixedThreadPool = TtlExecutors.getTtlExecutorService(fixedThreadPool);

Runnable task = () -> {
    String name1 = Thread.currentThread().getName();
    Object o = local.get();
    Object transO = transLocal.get();
    System.out.println(name1 + ":local" + o);
    System.out.println(name1 + ":transLocal" + transO);
};
fixedThreadPool.submit(task);

local.set("local--修改");
transLocal.set("transLocal--修改");
fixedThreadPool.submit(task);
```

结果：

```
pool-1-thread-1:locallocal--初始化
pool-1-thread-1:transLocaltransLocal--初始化
pool-1-thread-1:locallocal--初始化
pool-1-thread-1:transLocaltransLocal--修改
```

看demo中说明修改`Runnable`也是生效的，但是实际是无效的不能得到第二种方法的结果

希望能够得到解答

**Comment by oldratlee** [comment]
> 修改`Runnable`->`TtlRunnable`
> 
> ```java
> // ... 示例代码行省略 ...
> TtlRunnable ttlRunnable = TtlRunnable.get(task);
> fixedThreadPool.submit(ttlRunnable);
> 
> local.set("local--修改");
> transLocal.set("transLocal--修改");
> fixedThreadPool.submit(ttlRunnable);
> ```
> 
> 结果：
> 
> ```
> pool-1-thread-1:locallocal--初始化
> pool-1-thread-1:transLocaltransLocal--初始化
> pool-1-thread-1:locallocal--初始化
> pool-1-thread-1:transLocaltransLocal--初始化
> ```
> -----------------------------
>
> 看demo中说明修改`Runnable`也是生效的，但是实际是无效的不能得到第二种方法的结果

修改`Runnable`的使用方式，每次提交线程池时都需要生成`TtlRunnable` Wrapper。
即加一行代码就好了： @xiaospace1028 

```java
// ... 示例代码行省略 ...
TtlRunnable ttlRunnable = TtlRunnable.get(task);
fixedThreadPool.submit(ttlRunnable);

local.set("local--修改");
transLocal.set("transLocal--修改");
ttlRunnable = TtlRunnable.get(task); // !!生成`TtlRunnable` Wrapper!!
fixedThreadPool.submit(ttlRunnable);
```

------------------------

这个在[用户文档 - 修饰线程池](https://github.com/alibaba/transmittable-thread-local#22-%E4%BF%AE%E9%A5%B0%E7%BA%BF%E7%A8%8B%E6%B1%A0)有提到，但说得不明显，我优化一下文档：

![image](https://user-images.githubusercontent.com/1063891/113974352-56813700-9870-11eb-923e-c13020079271.png)

**Comment by xiaospace1028** [comment]
多谢，原因还是我没有去阅读一下源码，我去拜读一下。

**Comment by oldratlee** [comment]
> 这一点 在[用户文档 - 修饰线程池](https://github.com/alibaba/transmittable-thread-local#22-%E4%BF%AE%E9%A5%B0%E7%BA%BF%E7%A8%8B%E6%B1%A0)有提到，但说得不明显，我优化一下用户文档：  


@xiaospace1028 更新了用户文档，添加了相应的说明：

![image](https://user-images.githubusercontent.com/1063891/114269990-82511800-9a3c-11eb-9f24-be08973359ab.png)
