### ISSUE TITLE
在parallelStream().forEach()并行获取TransmittableThreadLocal时，一部分取不到值

### ISSUE THREAD

**Issue by miaoj0620** [alibaba/transmittable-thread-local#266]
![image](https://user-images.githubusercontent.com/19304073/116645307-1d883e00-a9a8-11eb-88f4-f2934516ac26.png)
![image](https://user-images.githubusercontent.com/19304073/116645321-2a0c9680-a9a8-11eb-8a7e-a188a8bc8a7f.png)

**Comment by oldratlee** [comment]
@miaoj0620 你的使用方式是什么？

需要通过[2.3 使用`Java Agent`来修饰`JDK`线程池实现类](https://github.com/alibaba/transmittable-thread-local/#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB) 使用方式 支持`parallelStream`。  
上面的文档链接包含了使用方式。

---------------

如果还有问题，需要分离整理 一个 可以复现问题的极简Demo工程：  @miaoj0620 
  - 作为一个`github`工程，这样大家可以用来排查
  - 就像这个Issue https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-739314037 给的[`liauraljl/ttl-agent-demo`](https://github.com/liauraljl/ttl-agent-demo)这个工程

否则涉及大量你的业务代码与流程，不能分析完整，完成排查。
