### ISSUE TITLE
关于多个agent冲突的解决方法

### ISSUE THREAD

**Issue by Leonardawp** [alibaba/transmittable-thread-local#268]
1. 手动触发类重新加载 
2. 使用 retransformClasses 

为什么不用这两种方法呢？

把agent放在第一位感觉治标不治本

**Comment by Leonardawp** [comment]
1、手动触发类重新加载 2、使用 retransformClasses
为什么不用这两种方法呢？把agent放在第一位感觉治标不治本

**Comment by oldratlee** [comment]
> 1. 手动触发类重新加载
> 2. 使用 retransformClasses
> 
> 为什么不用这两种方法呢？

可以考虑的，保证实现是可靠性。
有实现成本，以及后续一段实现的稳定时间。

关于『使用 retransformClasses』
https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-761840749
这里也有讨论，也有一些实现尝试。

@Leonardawp 可以一起来尝试实现～ 😄


> 把agent放在第一位感觉治标不治本

『放在第一位』的做法，验证是OK的。因为`TTL`实现没有调整，功能也自然是很稳定的。

但有配置注意的成本。

-----------------

相关有讨论Issue

- #169 支持运行时加载TTL agent 
- #226 TTL agent 与 其他agent的兼容性问题
