### ISSUE TITLE
CompltetableFuture结合Ttl 未使用agent方式 也拿到了ttl中的value

### ISSUE THREAD

**Issue by biuabiu** [alibaba/transmittable-thread-local#279]
### 使用方式/环境信息：
- jdk 1.8 
- 未使用agent 
- 需要依赖lombok、ttl
- 仅使用了CompltetableFuture 和 ttl
 
### 源码

![20210609145410](https://user-images.githubusercontent.com/38499411/121307396-86ad8a80-c932-11eb-976f-dc515adae7a2.png)

[CompletableFutureTest2.zip](https://github.com/alibaba/transmittable-thread-local/files/6621634/CompletableFutureTest2.zip)

### 问题说明：

看日志跨线程怎么还是拿到了数据？

**Comment by oldratlee** [comment]
> ### 问题说明：
> 看日志跨线程怎么还是拿到了数据？

@biuabiu 

原因是：

`TransmittableThreadLocal`本身也是`InheritableThreadLocal`，`Inheritable`能力：
可以在新建线程时，传递父子的`ThreadLocal`值。

具体上面运行的例子：

`check`操作的线程（上面运行对应`test-business-4`）由`cache`线程（上面运行对应`test-business-1`）创建的。
\# `Executors.newFixedThreadPool`的`ThreadPoolExecutor`的线程创建是`Lazy`的。
