### ISSUE TITLE
transmittable-thread-local会不会有内存泄漏的风险？

### ISSUE THREAD

**Issue by yexuerui** [alibaba/transmittable-thread-local#281]
- 声明的`TransmittableThreadLocal`一般为静态变量。
- 或者在`Spring`的`bean`中声明（单例模式），
`TransmittableThreadLocal`一直被强引用持有。

那么 `holder`即使设计的为`InheritableThreadLocal<WeakHashMap<TransmittableThreadLocal<Object>, ?>>`，
若不在子线程显式调用`remove()`方法，也不会被`GC`回收吧。

**Comment by oldratlee** [comment]
> ……
> 那么 `holder`即使设计的为`InheritableThreadLocal<WeakHashMap<TransmittableThreadLocal<Object>, ?>>`，
若不在子线程显式调用`remove()`方法，也不会被`GC`回收吧。

显式调用`remove()`方法，不被`GC`回收，是正确的功能。

如果 不调`remove()`方法，`ThreadLocal`持有的对象被`GC`回收， 则是`Bug`。
（无故消失，不能正确持有！）

> ### PS
>
> 与 下面的Issue 类似/重复：
> - #160
> - https://github.com/alibaba/transmittable-thread-local/issues/140#issuecomment-494767649
> - https://github.com/alibaba/transmittable-thread-local/issues/96#issuecomment-402594013

---------------

## 关于内存泄漏

任何持有的内存的字段或功能都会有内存泄漏的风险，需要正确使用。

`TransmittableThreadLocal`功能本身没有内存泄漏的问题。 @yexuerui 
即 `TransmittableThreadLocal`在正确使用的前提下，不会内存泄漏。

## 相关Issue

- #175

**Comment by oldratlee** [comment]
@yexuerui 

有涉及出现内存泄漏，更具体的问题吗？

**Comment by yexuerui** [comment]
因为transmittable-thread-local继承的是InheritableThreadLocal，在某个线程池第一次创建线程的时候，执行Thread的init方法，完成的数据的跨线程传递(即子线程的InheritableThreadLocal的inheritableThreadLocals会存储值)。而holder也是InheritableThreadLocal变量，在子线程创建时，执行init方法。子线程的holder也会继承父线程的值。

前提：
1. 线程池的线程第一次被创建；
2. 在创建子线程前，主线程中调用了transmittable-thread-local的set方法；
3. 主线程结束后，调用remove方法；
4. 请求再次进来，调用同一个线程池，发现子线程的inheritableThreadLocals依旧存在步骤2存入的值；

**代码验证：**

![image](https://user-images.githubusercontent.com/47298440/123512395-cf4a9f00-d6b9-11eb-807f-29bb0a089ca4.png)
local/t4的dubug效果：
![image](https://user-images.githubusercontent.com/47298440/123511974-4fbbd080-d6b7-11eb-8dc2-2af81ba68665.png)

也就是在第一次创建Thread时，会有些对象无法回收。

那么上述，如何清除泄漏的对象呢？

---
我理解transmittable-thread-local做出来努力，在`restoreTtlValues`方法中，会清除子线程设置的holder和transmittable-thread-local值（用户无需调用remove方法），但是我想问的是，在线程第一次创建的holder如何被清除？
---
我个人理解，普通线程池（非ForkJoinPool），且不是`CallerRunsPolicy`拒绝策略。子线程调用remove()方法，父线程的transmittable-thread-local不会被remove吧？？？

**Comment by oldratlee** [comment]
> ……
> 4\. 请求再次进来，调用同一个线程池，发现子线程的`InheritableThreadLocal`依旧存在步骤2存入的值。
>
> ……
>
> 也就是在第一次创建`Thread`时，会有些对象无法回收。
> 那么上述，如何清除泄漏的对象呢？

上面你讨论的是：`Inheritable`能力/功能 （即第一次创建`Thread`时的上下文传递）引起的问题与解决。

参见 https://github.com/alibaba/transmittable-thread-local/issues/279#issuecomment-860649758 ： @yexuerui 

> TTL提供了 关闭 `Inheritable`能力的解法：
> （可能要理解一下 这个解法及其背景原因，有些复杂性。 😄  ）
> 
> - 参见主类的 javadoc 说明：
> https://alibaba.github.io/transmittable-thread-local/apidocs/2.13.0-Beta1/com/alibaba/ttl/TransmittableThreadLocal.html
> - 对于线程池 TTL提供的DisableInheritable 支持
> https://alibaba.github.io/transmittable-thread-local/apidocs/2.13.0-Beta1/com/alibaba/ttl/threadpool/DisableInheritableThreadFactory.html
> - ISSUE #100 中解释了 为什么要做关闭`Inheritable`能力的原因
