### ISSUE TITLE
SpringBoot启动时，调用TTL的get方法造成线程不安全

### ISSUE THREAD

**Issue by yexuerui** [alibaba/transmittable-thread-local#282]
因为`TTL`底层使用`ITL`，会导致在`new`线程的时候，父子线程的数据传递，且无法销毁。

背景：
1. 项目启动的时候，存在`TTL`的`get`操作，于是`main`线程存在`TTL`的`value`；
2. 当请求进入时，`Tomcat`线程池（不会被`TtlExecutors`装饰）会开启子线程来执行业务逻辑；
3. `main`线程会将`TTL`(此时仅可看做`ITL`)的值传递到子线程；
4. 子线程修改`TTL`的引用时，会造成内存不安全；

代码如下：

```java
@Slf4j
@RestController
public class ThreadLocalController {

    ExecutorService executorService =
            TtlExecutors.getTtlExecutorService(new ThreadPoolExecutor(1, 1,
                    0L, TimeUnit.MILLISECONDS,
                    new LinkedBlockingQueue<>()));

    public static TransmittableThreadLocal<Map<String, String>> l2 = new TransmittableThreadLocal<Map<String, String>>() {
        @Override
        protected Map<String, String> initialValue() {
            return new HashMap<>();
        }
    };

    /**
     * 项目启动的时候，会调用TTL的get方法，这里使用static模拟；
     */
    static {
        l2.get();
        log.info("项目启动时加载配置");
    }


    @RequestMapping("/local/t1")
    public void t1() throws InterruptedException {
        Map<String, String> mc = l2.get();
        mc.put("t1", "t1v");
        log.info("【/local/t1】主线程打印：" + l2.get());
        executorService.execute(() -> {
            log.info("【/local/t1】子线程2map{}", l2.get());
        });
        Thread.sleep(1000);
        l2.remove();
    }

    @RequestMapping("/local/t4")
    public void t4() {
        log.info("【/local/t4】主线程打印：" + l2.get());
        executorService.execute(() -> {
            log.info("【/local/t4】子线程打印数据{}", l2.get());
        });
        Map<String, String> cache = l2.get();
        cache.put("l4", "l4v");
        l2.remove();
    }

}
```

疑问：此时由于是普通的线程池，即使`TTL`重写`copy`方法也会造成线程不安全；

解决方法只有去重写`childValue`方法，来解决`ITL`传递到子线程吗？：

```java
    public static TransmittableThreadLocal<Map<String, String>> l2 = new TransmittableThreadLocal<Map<String, String>>() {
        @Override
        protected Map<String, String> initialValue() {
            return new HashMap<>();
        }

        @Override
        protected Map<String, String> childValue(Map<String, String> parentValue) {
            return initialValue();
        }
    };
```

**Comment by oldratlee** [comment]
@yexuerui 

> 因为`TTL`底层使用`ITL`，会导致在`new`线程的时候，父子线程的数据传递，且无法销毁。
> 
> 背景：
> 
> 1. 项目启动的时候，存在`TTL`的`get`操作，于是`main`线程存在`TTL`的`value`；
> 2. 当请求进入时，`Tomcat`线程池（不会被`TtlExecutors`装饰）会开启子线程来执行业务逻辑；
> 3. `main`线程会将`TTL`(此时仅可看做`ITL`)的值传递到子线程；
> 4. 子线程修改`TTL`的引用时，会造成内存不安全；


## 解决`Inheritable`能力/功能 引发的问题

其中，`ITL`（`InheritableThreadLocal`）引发的问题 在 前一个你的Issue中，说明问题与解法：
https://github.com/alibaba/transmittable-thread-local/issues/281#issuecomment-869000689

解决方法可以是：
通过设置线程池的`ThreadFactory`成`DisableInheritableThreadFactory`，disable Inheritable。 

对应你的示例代码的修改如下： @yexuerui 

```java
public class ThreadLocalController {
    ExecutorService executorService =
        TtlExecutors.getTtlExecutorService(new ThreadPoolExecutor(1, 1,
            0L, TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<>(),
            // *disable Inheritable*
            // 通过设置线程池的ThreadFactory成DisableInheritableThreadFactory
            TtlExecutors.getDefaultDisableInheritableThreadFactory()
            )
        );
}
```

## 线程安全问题

**Comment by yexuerui** [comment]
您好。我明白可以装饰ThreadFactory来解决ITL的问题，但是我重点强调的是：请求进来时。是tomcat开启一个线程处理，但是tomcat的线程池没有使用ttl的包装的线程池。也就无法使用您说的上面的方法。

**Comment by oldratlee** [comment]
> 我重点强调的是：请求进来时。是tomcat开启一个线程处理，但是tomcat的线程池没有使用ttl的包装的线程池。也就无法使用您说的上面的方法。

用覆盖`childValue`方法也可以线程安全，
你再看一下上面的回复。

**Comment by yexuerui** [comment]
好的，我理解您的意思了

**Comment by oldratlee** [comment]
> 好的，我理解您的意思了

带上并发维度，要解释清楚，
真有点让人心力憔悴 🤣  @yexuerui 

之前的Issue，涉及并发时，
我一般都简单说明与`TTL`独立正交，避免展开去解释的。 😅

**Comment by HuangDayu** [comment]
```java
    public static final TransmittableThreadLocal<ConcurrentMap<String, Object>> THREAD_CONTEXT = TransmittableThreadLocal.withInitial(() -> {
        return  new ConcurrentHashMap<>();;
    });
```
@oldratlee 你好，我将`TTL`作为一个公共静态常量使用，应用全局使用该常量，然后也将线程池的ThreadFactory 设置为了`TtlExecutors.getDefaultDisableInheritableThreadFactory()`，但是依然存在线程安全问题。

问题表现为，在Spring EventBus的使用中，高并情况下，事件发布者（A线程池）设置TTL的值，事件消费者（B线程池）消费新事件时，常出现TTL获取到了旧事件的值，事件并发越高，问题越严重，如果不是高并发则不出现该问题。尝试过-javaagent装饰线程池的方式，也与手动装饰的方式一同使用，但是依然存在该问题。

问题是否跟`static`和`final`的线程安全性有关？ConcurrentMap应该是安全的。

由于业务相对复杂，但是我尝试用测试用例复现，缺没能复现出来   😭 ，所以暂时没有示例，不知我表达清楚没有，还望答疑解惑一下，谢谢。

**Comment by oldratlee** [comment]
@HuangDayu 独立的问题，请开个独立的 issue。

------------------

上面你列的这些前提，如

- 将`TTL`作为一个公共静态常量使用
- 将线程池的ThreadFactory 设置为了`TtlExecutors.getDefaultDisableInheritableThreadFactory()`
- `-javaagent`装饰线程池的方式 or 手动装饰的方式
- `ConcurrentMap` 是安全的
- ...

并不能保证，你在业务中取得独立在业务中你认为 新值或旧值。

『并不能保证』的 其中一个简单示例说明 就是，

- `TTL`值被一段不在你意料中的逻辑 改写了。
- 如果不能排除『`TTL`值会被一段不在你意料中的逻辑改写』，因为逻辑不完整，不能得到结论。 @HuangDayu

**Comment by HuangDayu** [comment]
@oldratlee 你好，我已参照[TtlMDCAdapter](https://github.com/ofpay/logback-mdc-ttl/blob/master/src/main/java/org/slf4j/TtlMDCAdapter.java) 解决了该问题，非常感谢你的解答，谢谢。
