### ISSUE TITLE
TtlRunnable是否实现Comparable来实现Runnable在队列中的优先级排序？

### ISSUE THREAD

**Issue by KevinQian** [alibaba/transmittable-thread-local#290]
场景：
1、自定一个Task实现Runnable和Comparable接口。
2、创建ThreadPoolExecutor时，绑定一个PriorityBlockingQueue来实现任务按优先级执行。

**Comment by oldratlee** [comment]
@KevinQian  需求合理 💕

我也想一下 设计实现的方式。

-------------------

目前，个人觉得，
像`TtlRunnable`实现`Comparable`的方式，`TTL`核心没有做到关注点分离。
（可以假想会有各种各样不同的接口，以附加像优先级`Comparable`这样附加能力）

**Comment by oldratlee** [comment]
@KevinQian 

不使用`TTL`的情况下，`ThreadPoolExecutor`通过`PriorityBlockingQueue`来实现任务按优先级执行，
这个 你能给一个 演示可运行的`Demo`吗？

---------------

我试了一下，好像并不是简单直接的做法。

初步实现并`Debug`发现，`ThreadPoolExecutor`发现提到`PriorityBlockingQueue`的是`FutureTask`：

![image](https://user-images.githubusercontent.com/1063891/132814668-99f9d575-c1e4-471c-8389-b458e066a178.png)

**Comment by KevinQian** [comment]
> @KevinQian 需求合理 💕
> 
> 我也想一下 设计实现的方式。
> 
> 目前，个人觉得，
> 像`TtlRunnable`实现`Comparable` 这样简单的方式，`TTL`核心没有做到关注点分离：
> 
> * 可以假想会有各种各样不同的接口，以附加上像优先级`Comparable`这样的能力。
> * 另外，优化级是怎样的 由业务来决定，`TtlRunnable`实例的优先级 应该要代理回 用户的`Runnable`实例。
> 
> @KevinQian 设计实现的方式 你有什么想法吗？欢迎讨论～ 💕
> 
> 如果你碰到了问题，急着要解决，可以通过使用[`PriorityBlockingQueue​(int initialCapacity, Comparator<? super E> comparator)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/PriorityBlockingQueue.html#%3Cinit%3E(int,java.util.Comparator))这个构造函数 先解决问题。

我想法跟你差不多，是想让TtlRunnable实现Comparable接口，ttl源码还没深入研究。只是初步的想法，不知道有没有其他问题。
我自己写了一个简单的场景。
`java`
package com.kevin.netty.server;

import java.util.concurrent.*;

/**
 * @author qian.zhi
 */
public class TestQueue {
    public static void main(String[] args) {
        BlockingQueue queue = new PriorityBlockingQueue();
        Task task1 = new Task(2);
        Task task2 = new Task(1);
        Task task3 = new Task(3);
        // 模拟任务提交速度大于线程处理速度
        queue.add(task1);
        queue.add(task2);
        queue.add(task3);

        ThreadPoolExecutor executor = new ThreadPoolExecutor(1, 1, 0L, TimeUnit.MILLISECONDS, queue);
        executor.execute(task1);
    }

    static class Task implements Runnable, Comparable<Task>{
        int priority;
        public Task(int priority) {
            this.priority = priority;
        }

        @Override
        public int compareTo(Task o) {
            return this.priority - o.priority;
        }

        @Override
        public String toString() {
            return "Task{" +
                    "priority=" + priority +
                    '}';
        }

        @Override
        public void run() {
            try {
                TimeUnit.SECONDS.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(this.toString());
        }
    }
}

**Comment by KevinQian** [comment]
> @KevinQian 需求合理 💕
> 
> 我也想一下 设计实现的方式。
> 
> 目前，个人觉得，
> 像`TtlRunnable`实现`Comparable` 这样简单的方式，`TTL`核心没有做到关注点分离：
> 
> * 可以假想会有各种各样不同的接口，以附加上像优先级`Comparable`这样的能力。
> * 另外，优化级是怎样的 由业务来决定，`TtlRunnable`实例的优先级 应该要代理回 用户的`Runnable`实例。
> 
> @KevinQian 设计实现的方式 你有什么想法吗？欢迎讨论～ 💕
> 
> 如果你碰到了问题，急着要解决，可以通过使用[`PriorityBlockingQueue​(int initialCapacity, Comparator<? super E> comparator)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/PriorityBlockingQueue.html#%3Cinit%3E(int,java.util.Comparator))这个构造函数 先解决问题。

我想法跟你差不多，是想让TtlRunnable实现Comparable接口，ttl源码还没深入研究。只是初步的想法，不知道有没有其他问题。
我自己写了一个简单的场景。
`java`
package com.kevin.netty.server;

import java.util.concurrent.*;

/**
 * @author qian.zhi
 */
public class TestQueue {
    public static void main(String[] args) {
        BlockingQueue queue = new PriorityBlockingQueue();
        Task task1 = new Task(2);
        Task task2 = new Task(1);
        Task task3 = new Task(3);
        // 模拟任务提交速度大于线程处理速度
        queue.add(task1);
        queue.add(task2);
        queue.add(task3);

        ThreadPoolExecutor executor = new ThreadPoolExecutor(1, 1, 0L, TimeUnit.MILLISECONDS, queue);
        executor.execute(task1);
    }

    static class Task implements Runnable, Comparable<Task>{
        int priority;
        public Task(int priority) {
            this.priority = priority;
        }

        @Override
        public int compareTo(Task o) {
            return this.priority - o.priority;
        }

        @Override
        public String toString() {
            return "Task{" +
                    "priority=" + priority +
                    '}';
        }

        @Override
        public void run() {
            try {
                TimeUnit.SECONDS.sleep(10);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(this.toString());
        }
    }
}

**Comment by oldratlee** [comment]
`TTL`提供了通用实现，没有改`TTL`的核心类（如`TtlRunnable`）。发布了`v2.12.3-RC1`：  @KevinQian
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.3-RC1

------------

更多讨论 参见：

- #330
