### ISSUE TITLE
项目中增加ttl以后，我的项目启动耗时增加将近20%

### ISSUE THREAD

**Issue by qianxun-jay** [alibaba/transmittable-thread-local#292]
不带ttl
验证次数 | 启动结果
第一轮    | Started ApiService in 25.349 seconds (JVM running for 26.404)
第二轮    | Started ApiService in 25.129 seconds (JVM running for 26.252)
第三轮    | Started ApiService in 25.87 seconds (JVM running for 26.978)

带ttl
验证次数 | 启动结果
第一轮 | Started ApiService in 30.301 seconds (JVM running for 32.121)
第二轮 | Started ApiService in 30.404 seconds (JVM running for 32.225)
第三轮 | Started ApiService in 28.981 seconds (JVM running for 30.865)

**Comment by oldratlee** [comment]
首先，你的`TTL`使用方式是  [2.3 使用Java Agent来修饰JDK线程池实现类](https://github.com/alibaba/transmittable-thread-local#23-%E4%BD%BF%E7%94%A8java-agent%E6%9D%A5%E4%BF%AE%E9%A5%B0jdk%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AE%9E%E7%8E%B0%E7%B1%BB) 吗？ @qianxun-jay 
如果不使用`TTL Agent`，应该不会这么长的启动时长增加。

另外，你的数据说明有偏差。整理如下：

![image](https://user-images.githubusercontent.com/1063891/133581791-47c397ee-1d94-4b33-be6f-d68f192ff424.png)

[启动时长增加数据.xlsx](https://github.com/alibaba/transmittable-thread-local/files/7176330/default.xlsx)

---------------

对于`TTL Agent`要加载、分析和处理`JVM`加载的类，启动时间增加。
要看看如何优化，能优化多少。
