### ISSUE TITLE
是否能支持对原生ThreadLocal的全量捕获？

### ISSUE THREAD

**Issue by JasonMing** [alibaba/transmittable-thread-local#314]
TTL当前实现是通过侵入用户代码，让用户通过 `TransmittableThreadLocal` 类将上下文全部设置到TTL内的`ThreadLocal`，从而实现对特定的`ThreadLocal`进行单点捕获。

有没有可能直接对 [`Thread`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/Thread.java) 对象内的 [`threadLocals`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/Thread.java#L181-L183)/[`inheritableThreadLocals`](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/Thread.java#L185-L189) 直接进行全量捕获。
反正都上Agent了，加点反射访问也没太大影响。

这样可以直接支持所有使用原生 ThreadLocal API 的用户。

**Comment by oldratlee** [comment]
`Agent`的实现方式确实可以做得更进一步。 @JasonMing

我先想一下，
全量捕获/直接支持所有使用原生 ThreadLocal API，
可能有风险（毕竟是全量修改） 和 解决方法。

**Comment by oldratlee** [comment]
上面一条评论给了说明。这个 Issue 先 Close 了。
