### ISSUE TITLE
TransmittableThreadLocal override static java.lang.ThreadLocal#withInitial method

### ISSUE THREAD

**Issue by Razor0719** [alibaba/transmittable-thread-local#315]
when I use the TransmittableThreadLocal first, I use it with code below:

```java
TransmittableThreadLocal.withInitial(() -> "A");
```

and then I use ttl javaangent with the program, and found the value in ttl was never transfer into the sub thread,
suddenly, I find the method 'withInitial()' is not override in TransmittableThreadLocal but construct a SuppliedThreadLocal which is extended from ThreadLocal

can TransmittableThreadLocal override this method and then avoid my mistake

**Comment by oldratlee** [comment]
Good point!

I add the `TransmittableThreadLocal.withInitial()` method and release a new version these days.

Thanks for your professional suggestion. @Razor0719

**Comment by oldratlee** [comment]
@Razor0719 released `v2.12.2`

https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.2

**Comment by Razor0719** [comment]
> @Razor0719 released `v2.12.2`
> 
> https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.2

thanks a lot!
