### ISSUE TITLE
v2.13.0-Beta1: TtlExtensionTransformletManager中collectedClassLoaderHistory所对应的WeakHashMap会因为gc导致死循环造成cpu空转100%

### ISSUE THREAD

**Issue by Aresxue** [alibaba/transmittable-thread-local#320]
应用接口使用了`jackson`的`ObjectMapper`，其内部序列化使用了反射机制：

![image](https://user-images.githubusercontent.com/22526463/137422404-0677b9c9-3f07-4fdc-869d-75c8dddd57aa.png)

反射时`jvm`会创建`sun.reflect.DelegatingClassLoader`。

在流量高峰时，
![image](https://user-images.githubusercontent.com/22526463/137422524-b17f64f8-0059-4a83-9e42-9e5873e0bf22.png)
![image](https://user-images.githubusercontent.com/22526463/137422542-8ea986a7-0014-444f-be36-c06e682100d6.png)

大量的`sun.reflect.DelegatingClassLoader`实例涌入， 因为流量较大内存较小流量刚接进来时即发生了`gc`。
![image](https://user-images.githubusercontent.com/22526463/137422711-629ecaaa-8e09-4806-9bc4-f228cb82c474.png)

因为`gc`会把对象给清理掉，然后`get`方法内的`while`循环一直找不到`eq`的对象，循环出不来，
最终形成了死循环逐渐耗尽`CPU`。

现场最后形成这样的堆栈信息：
![image](https://user-images.githubusercontent.com/22526463/137422818-f1efc9aa-e66e-465a-9016-18cf39d80b51.png)

**Comment by oldratlee** [comment]
问题收到。

`TtlExtensionTransformletManager` 是 `v2.13.0-Beta1`这个**测试**版本的内容，还在实现中，。
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.13.0-Beta1

使用正式版本：`v2.12.2`，尤其线上环境。  @Aresxue 
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.2

---------

你有需要`v2.13.0-Beta1`才有功能的需求吗？ @Aresxue

**Comment by Aresxue** [comment]
> 问题收到。
> 
> `TtlExtensionTransformletManager` 是 `v2.13.0-Beta1`这个**测试**版本的内容，还在实现中。 https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.13.0-Beta1
> 
> 使用正式版本：`v2.12.2`，尤其线上环境。 @Aresxue https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.2
> 
> 对于`v2.13.0-Beta1`版本才有的功能，你有什么需求？ @Aresxue
> 
> > 在流量高峰时， 大量的`sun.reflect.DelegatingClassLoader`实例涌入， 因为流量较大内存较小流量刚接进来时即发生了`gc`。
> > 因为`gc`会把对象给清理掉，然后`get`方法内的`while`循环一直找不到`eq`的对象，循环出不来， 最终形成了死循环逐渐耗尽`CPU`。
> 
> 有问题分析 👍 @Aresxue

没有高级功能的需求，这边后续会回退到v2.12.2

**Comment by miniyk2012** [comment]
妹子挺美的

**Comment by oldratlee** [comment]
fixed by 0ec1ea1b187e4531866f466e0d99cfede3650dee
