### ISSUE TITLE
TransmittableThreadLocal.Transmitter#restore 方法是否会导致内存泄漏？

### ISSUE THREAD

**Issue by StrongBanana** [alibaba/transmittable-thread-local#321]
`restore`方法最终会调用到`ThreadLocal.set()`，之后没有主动调用`remove`；是否会因此产生内存泄漏？

**Comment by StrongBanana** [comment]
![image](https://user-images.githubusercontent.com/19589503/137711085-987f0831-fc1b-4fcd-bca6-7a3714ee8c6e.png)
如图，restoreTtlValues方法remove的是当前线程基于backup新增的变量，对于backup的变量会和当前线程进行绑定（setTtlValuesTo）；那么在执行完setTtlValuesTo后，如果当前线程和调用线程并不是同一线程（因为使用CallerRunsPolicy拒绝策略或ForkJoinPool导致调用线程和被调用线程数同一个）的情况下，那么会发生内存泄漏吗？

**Comment by oldratlee** [comment]
内存可以测试到；当然测试 不能替代 基于代码的分析。

你继续完成 基于的代码分析，最后形成结论？ @StrongBanana 💕  💪

你的这个问题，可能分析完代码是一个最可信的方式，用文字表述出来变成文字或文章，要不少时间～ 😸

--------------

如果分析过程有困难，可以看看 [小伙伴同学们写的 设计实现解析文章（写得都很好！ ）❤️ #123](https://github.com/alibaba/transmittable-thread-local/issues/123#issuecomment-476709456)。  @StrongBanana 

其中涉及设计与实现分析的，已经有几十篇文章了。

**Comment by nicky1** [comment]
你好，项目中需要在线程池中传递上下文，正要引入TTL来解决这个问题。
有个疑问，麻烦帮忙解疑下。
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/6406742/199766116-3e2f27df-6e4b-43e2-b103-e545cf64aaad.png">

1. restoreTtlValues(),  会有清理调用线程的时机吗
2. 不清理 调用线程持有的上下文变量，不会内存溢出吗

**Comment by oldratlee** [comment]
> 1. TransmittableThreadLocal 类的 restoreTtlValues(),  会有清理调用线程的时机吗

不会。因为这样的使用方式在调用线程这一级没有`restore`操作。

如果使用`pipeline`式拦截，再通过`runSupplierWithCaptured`就可以，并且是针对所有的`TTL`实例：


```java
public Object invoke(...) {
  final Object captured = TransmittableThreadLocal.Transmitter.capture();
  return TransmittableThreadLocal.Transmitter.runSupplierWithCaptured(captured, () -> pipeline.invoke(...));
}
```

**Comment by nicky1** [comment]
pre/post式拦截

类似的示例代码，使用spring 拦截器：
`@Component
public class UserInterceptor extends HandlerInterceptorAdapter {


    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        String userId = request.getParameter("userId");
        if (StringUtils.isNotBlank(userId)) {
            UserInfo userInfo = new UserInfo();
            userInfo.setUserId(Integer.valueOf(userId));
            ThreadContext.bindUser(userInfo);
        }
        return true;
    }

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) throws Exception {
//        TimeUnit.SECONDS.sleep(2);
        ThreadContext.unBindUser();
        super.afterCompletion(request, response, handler, ex);
    }
}`

**Comment by oldratlee** [comment]
> 猜测是 因为拦截器中先执行了清理，等到线程异步执行时，主线程中的threadlocal 已经被清理掉了。

关于`Spring`的拦截器及其执行方式，你了解一下`Spring`的调研方式。

与`TTL`关联不大 & 我没有了解过，这个 `TTL` issue 就不再继续讨论了。 @nicky1
