### ISSUE TITLE
TTL与ThreadPoolTaskExecutor的setTaskDecorator区别

### ISSUE THREAD

**Issue by wpstan** [alibaba/transmittable-thread-local#327]
spring线程池ThreadPoolTaskExecutor的setTaskDecorator方法可以对runnable进行装饰，也可以进行异步上下文数据传递。

请问一下，TTL相比ThreadPoolTaskExecutor的优点。

**Comment by oldratlee** [comment]
你看看 文档 [使用TTL的好处与必要性](https://github.com/alibaba/transmittable-thread-local#-%E4%BD%BF%E7%94%A8ttl%E7%9A%84%E5%A5%BD%E5%A4%84%E4%B8%8E%E5%BF%85%E8%A6%81%E6%80%A7) ，是不是有回答你想问的。
