### ISSUE TITLE
可不可对原生的ThreadLocal起作用？

### ISSUE THREAD

**Issue by kaneg** [alibaba/transmittable-thread-local#329]
项目负责人你好：
我有一个项目，我能控制线程池和Runnable的创建，但我没法让其他人把ThreadLocal替换为TransmittableThreadLocal，请问有没有办法可以用你们的方案来达到效果？谢谢。

**Comment by oldratlee** [comment]
`TTL`提供了`Transmitter.registerThreadLocal*`方法用于让`ThreadLocal`支持`Transmittable`能力。

@kaneg 你可以了解一下。

[`Transmitter JavaDoc`](https://alibaba.github.io/transmittable-thread-local/apidocs/2.12.2/com/alibaba/ttl/TransmittableThreadLocal.Transmitter.html)：

![image](https://user-images.githubusercontent.com/1063891/143732048-e912fc13-5600-4971-a733-c33f38a90667.png)

**Comment by kaneg** [comment]
@oldratlee 谢谢你的快速回应。
用Transmitter的register的确可以达到我期望的效果。不过有一点缺憾，就是thread local变量被别人封装为private了，目前在没有更好的方案之前，我用反射也是可以拿到的。

**Comment by oldratlee** [comment]
> @oldratlee 谢谢你的快速回应。 用Transmitter的register的确可以达到我期望的效果。不过有一点缺憾，就是thread local变量被别人封装为private了，目前在没有更好的方案之前，我用反射也是可以拿到的。

『thread local变量封装为private』，所以自然需用hack的方式获取。
反射应该是最简单的获取方法了。  @kaneg

**Comment by oldratlee** [comment]
@kaneg 可以介绍一下你的场景、需求、问题吗？ ❤️
方便大家可以了解学习。

**Comment by kaneg** [comment]
@oldratlee 我们的项目是一个基于Spring Boot的微服务。我们使用了其他部门的一些依赖库，这些依赖库中大量使用了ThreadLocal来传递参数，例如用户的id，http 的请求参数等等。但是我们在自己的代码中用了CompletableFuture来异步调用后台的API, 就导致在子线程中没法拿到用户id等信息. 你们这个库恰恰就解决了我们的痛点.

**Comment by oldratlee** [comment]
> 『thread local变量封装为private』（这往往是合理的做法），所以自然需用hack的方式获取。
> 
> 反射应该是最简单直接的获取方式了（三五行代码） 😄 @kaneg

@kaneg 

在`registerThreadLocal*`的 JavaDoc 加了 通过反射来获取`private static ThreadLocal`实例的简单说明：


> The fields stored the `ThreadLocal` instances are generally `private static`, so the `ThreadLocal` instances need be got by reflection, for example:
> 
> ```java
> Field field = TheClassStoredThreadLocal.class.getDeclaredField(staticFieldName);
> field.setAccessible(true);
> @SuppressWarnings("unchecked")
> ThreadLocal<T> threadLocal = (ThreadLocal<T>) field.get(null);
> ```


提交： 9d40c2eff4dfa966194dd6dd095122ea93220edb
