### ISSUE TITLE
ClassCastException(TtlRunnable cannot be cast to Comparable) when use PriorityBlockingQueue with ThreadPoolExecutor

### ISSUE THREAD

**Issue by outh0527** [alibaba/transmittable-thread-local#330]
### 问题：

使用TTL，异常：`com.alibaba.ttl.TtlRunnable cannot be cast to java.lang.Comparable`

### 场景：

1. 业务代码：

    ```java
    final ThreadPoolExecutor executor = new ThreadPoolExecutor(5, 5, 1, TimeUnit.SECONDS,  new PriorityBlockingQueue<Runnable>(1000));
    ```
2. 使用`TtlAgent`的方法来修饰jdk线程池。

### 描述：

`TtlRunnable`没有实现`Comparable`接口，当业务代码中在初始化线程池时，使用的是`PriorityBlockingQueue`优先级队列，业务`task`也实现了`Comparable`接口。

当线程池往阻塞队列里面放任务时，会调用`java.util.concurrent.PriorityBlockingQueue#siftUpComparable`方法，`Comparable<? super T> key = (Comparable<? super T>) x;`导致类型转换异常。

**Comment by oldratlee** [comment]
简单的回答：线程池与PriorityBlockingQueue配合的使用时，要注意wrap任务的操作。比如要重写PriorityBlockingQueue的比较逻辑。@outh0527

线程池自己的submit方法（wrap成FutureTask）、TTL线程池方法（wrapp成TtlRunnable），都不能直接使用。

已有的Issue:

- #290 
- #178

**Comment by outh0527** [comment]
嗯嗯，明白你的意思，业务在线程池与PriorityBlockingQueue配合的使用时，提交的任务是已经重写PriorityBlockingQueue的比较逻辑，如果不接入agent，业务是没有问题的，而我们在agent中使用到了TTL Agent，对业务是无感知，加入agent后，业务的runnable被wrap成了TtlRunnable，就会抛ClassCastException，这对业务方来说是不可接受的，不能要求他们去改业务代码，这样推广难度比较大，可否在TtlRunnable和TtlCallable中实现Comparable接口呢，比较的逻辑还是业务自己实现。
![image](https://user-images.githubusercontent.com/86814310/143823078-2243c206-2a02-4a8a-a671-93da177e8956.png)
我在本地试了一下貌似可以。

**Comment by oldratlee** [comment]
> 可否在TtlRunnable和TtlCallable中实现Comparable接口呢，比较的逻辑还是业务自己实现。
> 我在本地试了一下貌似可以。

这个做法 在方案上 不少不完备的地方。即潜在的坑。

----------

当然，你可以 拉`TTL`的代码 Build 一个`TTL Jar`（`mvn install`），用你这个方法，快速解决你的问题。 @outh0527

注意：基于稳定版本的Tag `v2.12.2`。

**Comment by oldratlee** [comment]
> 这个做法 在系统方案设计上 不少不完备的地方，即作为通用做法可能有坑。
> 怎么改`TTL`要再想一下。

`TTL`提供了通用实现。没有改`TTL`的核心类（如`TtlRunnable`）。

发布了`v2.12.3-RC1`：  @outh0527 
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.3-RC1

**Comment by oldratlee** [comment]
发布了 `v2.12.3` @outh0527

https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.3
