### ISSUE TITLE
agent模式添加启动

### ISSUE THREAD

**Issue by yangzhiw** [alibaba/transmittable-thread-local#331]
agent,在启动项中添加了
`-javaagent:/path/to/transmittable-thread-local-2.12.2.jar`

然后启动错误

```java
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : /path/to/transmittable-thread-local-2.12.2.jar
```

**Comment by oldratlee** [comment]
给一下可以复现问题的github repo，方便大家排查 @yangzhiw

**Comment by yangzhiw** [comment]
> 给一下可以复现问题的github repo 工程，方便大家排查 @yangzhiw

我把 -javaagent:/path/to/transmittable-thread-local-2.12.2.jar 路径换成绝对路径就好了，/path/to就是是要引入这个jar的觉得路径的意思么？

**Comment by oldratlee** [comment]
> > 给一下可以复现问题的github repo 工程，方便大家排查 @yangzhiw
> 
> 我把 -javaagent:/path/to/transmittable-thread-local-2.12.2.jar 路径换成绝对路径就好了，/path/to就是是要引入这个jar的觉得路径的意思么？

问题解决就好～  @yangzhiw 

如何配置`javaagent`，你找一下资料，比如看官方文档：

- [`Java Agent`规范 - `JavaDoc`](https://docs.oracle.com/javase/10/docs/api/java/lang/instrument/package-summary.html#package.description)
- [JAR File Specification - JAR Manifest](https://docs.oracle.com/javase/10/docs/specs/jar/jar.html#jar-manifest)
- [Working with Manifest Files - The Java™ Tutorials](https://docs.oracle.com/javase/tutorial/deployment/jar/manifestindex.html)
