### ISSUE TITLE
2.12.1版本   NPE 在父子线程情况下 ThreadLocal<Map<String, String>> holder = new TransmittableThreadLocal<>() 新增map中的key值 会导致原有key对应的value值为null,一定概率出现空指针

### ISSUE THREAD

**Issue by chen-shu-hao** [alibaba/transmittable-thread-local#333]
NPE 在父子线程情况下 ThreadLocal<Map<String, String>> holder = new TransmittableThreadLocal<>() 新增map中的key值 会导致原有key对应的value值一定概率丢失为null,出现空指针

**Comment by oldratlee** [comment]
@chen-shu-hao 请给一下

- 问题的信息：如NPE的栈、你的使用方式 等等
- 复现问题（概率）的Git代码Repo

方便大家跟进与排查。

**Comment by chen-shu-hao** [comment]
1.是第一种,holder是我们项目里的context,不是您说的TransmittableThreadLocal.holder
2.确实我使用的是hashmap,没有使用线程安全的map,在主线程中给holder中的map赋完值后,去子线程中给map put了新值（这个值是我想往下传递的值,但是每个线程里生成的value不一致,所以我给一个固定的key值前面加了当前线程名称作为前缀,企图在接下来的流程中,每个线程取到自己的value值,然而在每个线程中put了多次这个key值后,map中原有的key值就出现了value为null的情况）
3.现在我解决了这个问题,重新定义了一个新的TransmittableThreadLocal,没有使用主线程的TransmittableThreadLocal

**Comment by oldratlee** [comment]
@chen-shu-hao 解决了问题就好。❤️

这个 Issue 先 Close 了。如果问题可以继续讨论。

**Comment by liuyq913** [comment]
private static TransmittableThreadLocal<Map<String, String>> transmittableThreadLocal = new TransmittableThreadLocal();
子线程修改了transmittableThreadLocal里面某个值， 会透传到主线程里面

**Comment by oldratlee** [comment]
> private static TransmittableThreadLocal<Map<String, String>> transmittableThreadLocal = new TransmittableThreadLocal(); 子线程修改了transmittableThreadLocal里面某个值， 会透传到主线程里面

是的。缺省传递引用。

可以定制传递方式，参见文档。 @liuyq913
