### ISSUE TITLE
使用jrebel -javaagent方式启动，在stream().parallel()无法正确获取内容

### ISSUE THREAD

**Issue by aeroyu** [alibaba/transmittable-thread-local#338]
如题

**Comment by oldratlee** [comment]
首先，配置`TTL Agent`在最前的位置，可以避免与其它其它`Agent`配合使用时，`TTL Agent`可能的不生效问题。  @aeroyu 


> 参见文档 [FAQ](https://github.com/alibaba/transmittable-thread-local/blob/34717a20a3587b1955e40215c17bde6a258377e6/README.md#-faq)：
>
> **_Q1. `TTL Agent`与其它`Agent`（如`Skywalking`、`Promethues`）配合使用时不生效？_**
> 
> 配置`TTL Agent`在最前的位置，可以避免与其它其它`Agent`配合使用时，`TTL Agent`可能的不生效问题。配置示例：
> 
> ```bash
> java -javaagent:path/to/transmittable-thread-local-2.x.y.jar \
>      -javaagent:path/to/skywalking-agent.jar \
>      -jar your-app.jar
> ```

-------------

另外，给一个可以说明/复现问题的、极简可运行的Demo工程 ❤️；推荐：

- 提交成一个`github repo`，方便大家运行以了解、重现问题与排查解决
- 就像这个Issue https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-739314037 给的工程 [`liauraljl/ttl-agent-demo`](https://github.com/liauraljl/ttl-agent-demo)

有一个可以说明/复现问题的、极简可运行的Demo工程，也可以排除可能的使用问题，

**Comment by oldratlee** [comment]
@aeroyu
这个 Issue 先 close；如果有了复现的 demo，随时 reopen 继续讨论。

**Comment by aeroyu** [comment]
重现了
重现条件：在spring初始化前，调用parallelStream，比如
<img width="767" alt="image" src="https://github.com/alibaba/transmittable-thread-local/assets/5063734/5ff4adc6-5ce5-4d11-832b-cdccc4345d22">
后续的parallelStream都不能正确获取

需要使用jrebel启动，使用普通启动则没有问题
[ttl_jrebel_demo.zip](https://github.com/alibaba/transmittable-thread-local/files/13839020/ttl_jrebel_demo.zip)
