### ISSUE TITLE
如果 用户重写阻塞队列 offer方法，这种情况能够兼容么

### ISSUE THREAD

**Issue by simake2017** [alibaba/transmittable-thread-local#340]
![image](https://user-images.githubusercontent.com/31234273/147518765-3cdc28ad-91de-4114-bfa0-e6609801eb65.png)

这里用户重写了一个阻塞队列，然后重写了put和offer方法，里面进行了强制转换，这种现在能兼容么

**Comment by oldratlee** [comment]
@simake2017 给一个可以说明/复现问题的、极简可运行的Demo工程：❤️

- 作为一个`github`工程，方便大家了解问题与排查解决
- 推荐 就像这个Issue https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-739314037 给的工程 [`liauraljl/ttl-agent-demo`](https://github.com/liauraljl/ttl-agent-demo)

----------------

类似的类型问题，在`PriorityBlockingQueue`中解决过：

- https://github.com/alibaba/transmittable-thread-local/issues/330
- 发布在版本 v2.12.3：
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.3

**Comment by simake2017** [comment]
是这样的，用户自己写了一个阻塞队列，然后在创建 ThreadPoolExecutor 的时候，使用了自己的阻塞队列，阻塞队列中，又重写了 put以及offer方法，方法内容如上图，里面会进行强转，也就是将TtlRunnable 转为自己的Runnable子类，就会爆出 ClassCastException , 可运行demo，稍后给出，问题应该比较清楚地。

**Comment by oldratlee** [comment]
编码的解决方法，已经有的：

先对`Runnable`参数做`TtlRunnable.unwrap(runnable)`。

写了一个说明问题的、极简可运行的Demo：

https://github.com/alibaba/transmittable-thread-local/blob/0f9bff4e53c3c9463e1a5514b3ee21433139ca74/src/test/java/com/alibaba/demo/ttl/CustomizedBlockingQueueWithTtl.java#L45-L75

**Comment by oldratlee** [comment]
@simake2017 这个 Issue 先 close。如果还有问题，可以继续讨论。
