### ISSUE TITLE
v2.12.2 Already TtlCallable异常

### ISSUE THREAD

**Issue by chenqiaole** [alibaba/transmittable-thread-local#341]
![image](https://user-images.githubusercontent.com/48151459/147525191-8e7a4875-ae28-4481-90d5-c7069895d8fa.png)
版本号v2.12.2 
使用方式  
![image](https://user-images.githubusercontent.com/48151459/147525632-89516c4f-aaa4-417d-a633-00d7c5f719be.png)
![image](https://user-images.githubusercontent.com/48151459/147525654-16f511bc-94f8-413b-ad11-c1e32bc3a00e.png)
会一直报 Already TtlCallable异常  能不能帮忙看看这个是什么问题 看了下  默认幂等都是设置true的

**Comment by oldratlee** [comment]
@chenqiaole 给一个可以说明/复现问题的、极简可运行的Demo工程；推荐 ❤️

- 作为提交成一个`github repo`，方便大家运行以了解、重现问题与排查解决
- 就像这个Issue https://github.com/alibaba/transmittable-thread-local/issues/226#issuecomment-739314037 给的工程 [`liauraljl/ttl-agent-demo`](https://github.com/liauraljl/ttl-agent-demo)

**Comment by chenqiaole** [comment]
> 

后面我看看能不能提个复现的demo出来   但是抛这个异常可能是什么原因导致的呢   TtlExecutors.getTtlExecutor我看idempotent幂等的默认值都是true 
![image](https://user-images.githubusercontent.com/48151459/147562084-5b7a0791-2b40-410b-ba43-3734443e88b9.png)
这个值可能是哪里被改了吗

**Comment by xuyikai1** [comment]
我前阵子也碰到了，大佬有思路嘛，这几天瞅瞅能不能复现

**Comment by oldratlee** [comment]
> 后面我看看能不能提个复现的demo出来。
> 
> 但是抛这个异常可能是什么原因导致的呢？ `TtlExecutors.getTtlExecutor`我看`idempotent`幂等的默认值都是`true`
> 
> ![image](https://user-images.githubusercontent.com/48151459/147562084-5b7a0791-2b40-410b-ba43-3734443e88b9.png)
> 
> 这个值可能是哪里被改了吗？

可以看代码。

代码是没有 直接改的地方的。   @chenqiaole 
（非直接改的方式，是指 比如 反射）

**Comment by xuyikai1** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by oldratlee** [comment]
> 我前阵子也碰到了，大佬有思路嘛，这几天瞅瞅能不能复现

@xuyikai1 @chenqiaole 

个人觉得，如果是`TTL Agent`的使用方式，一个比较可能的原因是：

生效的`TTL`的版本

- 是由`-javaagent:path/to/transmittable-thread-local-2.x.y.jar` 指定`TTL Jar`的版本
- 而不是应用中使用`TTL Jar`的版本

**Comment by oldratlee** [comment]
@xuyikai1 @chenqiaole 这个 Issue 先 close。如果有了复现的 demo，随时 reopen 继续讨论。
