### ISSUE TITLE
ttl attach咨询

### ISSUE THREAD

**Issue by ocean-wll** [alibaba/transmittable-thread-local#364]
我们是做压测产品，需要使用ttl对线程池中的数据进行传标。

我们想把我们的产品封装成一个jar包，可以像arthas-boot那样去动态attach agent。

对ttl的处理方式是通过手动调用 TtlAgent.premain() ，但是发现不会对已经创建了的Runnable进行增强了。

所以对这一块的处理有什么好的建议吗？

**Comment by oldratlee** [comment]
目前没有支持『对已加载的类做增强』。 @ocean-wll 

相关Issue

- #169
- #380

-------------

attach的功能 讨论与进展 在下面 issue 中跟进

- #169
