### ISSUE TITLE
replay 在遍历holder的过程中，什么情况下会出现 !captured.containsKey(threadLocal)为true

### ISSUE THREAD

**Issue by 1000-7** [alibaba/transmittable-thread-local#369]
我理解holder是维护父线程传递给子线程的threadLocal的值，
而captured快照中的ttl2Value也是将父线程传递给子线程的threadLocal的值保存起来
只是holder比较隐性，captured是显式的保存，但是他们俩的keySet应该是一致的，那什么情况下代码 `!captured.containsKey(threadLocal)`会为true呢

**Comment by 1000-7** [comment]
自己给自己答一波，
!captured.containsKey(threadLocal)为true
=> 子线程默认会得到将父线程传递过来的值放到holder里，
=> captured默认快照来源是父线程的holder
=> 此时run的时候立刻replay(captured)肯定是一致的，毫无疑问
=> 因此像TtlRunnable、TtlCallable的run方法实现，永远都是一致的。

but
=> holder中多了一些父线程快照中没有的ttl变量；
=> holder在子线程增加了一些或者capture变少了
=> 那就是你不用TtlRunnable那种标准的使用方式（继承改写或者直接调用ttl的方法），自己capture之后，子线程replay之前，又增加了一个ttl变量，这时会加到holder

这应该是算一种防御性设计，毕竟你用标准的TtlRunnable、TtlCallable是不会为true的

**Comment by oldratlee** [comment]
> => 那就是你不用TtlRunnable那种标准的使用方式（继承改写或者直接调用ttl的方法），自己capture之后，子线程replay之前，又增加了一个ttl变量，这时会加到holder
> 
> 这应该是算一种防御性设计，毕竟你用标准的TtlRunnable、TtlCallable是不会为true的

在子线程中的回放之前，业务也可能改了已有`TTL`的值，这是很常见的业务使用方式。

毕竟，如果能保证`TTL`实例且其值都是一致（没有变化），就没必要用`TTL`。@1000-7
