### ISSUE TITLE
建议afterExecute()扩展点添加Runable和Throwable参数

### ISSUE THREAD

**Issue by wuaping** [alibaba/transmittable-thread-local#377]
由于`replay`和`restore`都是在`run`方法里，所以`ThreadPoolExecutor`里的`afterExecute()`扩展点就无法继承`TTL`
<img width="623" alt="image" src="https://user-images.githubusercontent.com/27723280/164967913-470bb1ed-0cb5-404f-be0d-b445a2fbfbb4.png">

**Comment by oldratlee** [comment]
看起来挺好。

你有什么实际的需求场景吗？ @wuaping 

PS：

这个扩展点，用的很少。
自己几个之前碰到的使用场景，有更好的设计实现方式。
即我认为这个扩展点有些过度设计了，所以不想更复杂化了。
（现在因为兼容性也不能删除了）

**Comment by wuaping** [comment]
我现在遇到的场景：
我在打印日志时会有个traceId，使用TTL保存。
当在线程池里出现exception时，我实现了ThreadPoolExecutor里的afterExecute()方法来打印异常日志。但是发现此时的TTL已经被restore了。
我发现了TTL也有afterExecute()的扩展点，但是没有入参，所以这个扩展点无法实现相关业务。

我现在的解决方案是：只能是实现spi里的

**Comment by oldratlee** [comment]
线程池执行的看起来，应该在线程池的扩展方法中解决。

`TTL`与执行的任务 是 多对一 的关系，生命周期/职责也不对。

**Comment by wuaping** [comment]
谢谢指导🙏，不过这个场景与我的不太一样，我的目的是为了监控线程池的异常，线程池异常如果不进行异常打印的话，堆栈信息无法被ELK收集

**Comment by wuaping** [comment]
我理解并认同您说的职责，我在思考因为TTL是在Runnable上实现数据的复制和restore，但是在数据方面牺牲了线程池的afterExecute()扩展点，是否考虑在TtlRunnable上新增afterExecute()扩展点

**Comment by oldratlee** [comment]
> 我在思考因为TTL是在Runnable上实现数据的复制和restore，但是在数据方面牺牲了线程池的afterExecute()扩展点，是否考虑在TtlRunnable上新增afterExecute()扩展点

为什么『在Runnable上实现数据的复制和restore，在数据方面，会牺牲了 线程池的afterExecute()扩展点』？ @wuaping 

线程池的`afterExecute()`扩展点 与 `Runnable` 应该是正交的。

在线程池看来，都是 普通的`Runnable`。
（不关心具体的实现是什么，`TtlRunnable` or 其它）

**Comment by wuaping** [comment]
『在TtlRunnable上实现数据的复制和restore，在数据方面，会牺牲了 线程池的afterExecute()扩展点』
--- 从使用者角度觉得，在使用TTL后，线程池的afterExecute()里无法使用TTL的数据业务，而且还是同一个线程

我能理解您想表达TTL的职责边界就是Runnable，所以我才会想在Runnable去添加一些扩展点来弥补这种使用场景

**Comment by oldratlee** [comment]
> 从使用者角度觉得，在使用TTL后，线程池的`afterExecute()`里无法使用TTL的数据业务，而且还是同一个线程

明白你说的了 😅

---------

- 对于`TTL Agent`的使用方式
    - 线程池的`afterExecute()`回调收到的`Runnable`是 没有`TtlRunnable Wrap`过的。
    （即业务的`Runnable`）。
- 如果使用`TTL API`（如`TtlExecutors#getTtlExecutorService()`，

    ```java
    protected void afterExecute(Runnable r, Throwable t) {
        // unwrap TtlRunnable first
        r = TtlRunnable.unwrap(runnable);

        // biz code

    }
    ```

**Comment by wuaping** [comment]
👍十分感谢
