### ISSUE TITLE
已经加载到jvm的ForkJoinTask如何做ttl增强？

### ISSUE THREAD

**Issue by DockerFan** [alibaba/transmittable-thread-local#380]
目前在基于阿里开源的sandbox-repeater做录制回放，录制的业务本身使用了ForkJoinPool，业务本身使用的时候并没有继承TtlRecursiveTask重写compute方法，没开启ttl。

但是sandbox-repeter需要对这块进行开启跟踪，不然会影响上下文信息的拷贝，
并且sandbox-repeter本身是基于before、return等event事件的又没法通过反射增加新的继承类和重写方法。

这种有什么思路可以解决吗？期待回复。

**Comment by oldratlee** [comment]
目前没有支持。 @DockerFan 

相关Issue

- #169
- #364

**Comment by DockerFan** [comment]
debug看业务代码ForkJoinPool的execute方法里的传参是个runnable类型，那可以把一个ForkJoinTask的任务强转成一个runnable，然后处理成ttlRunnable类型这样来开启ttl吗？

**Comment by DockerFan** [comment]
> debug看业务代码ForkJoinPool的execute方法里的传参是个runnable类型，那可以把一个ForkJoinTask的任务强转成一个runnable，然后处理成ttlRunnable类型这样来开启ttl吗？
