### ISSUE TITLE
如何实现完成线程传递后的初始化操作

### ISSUE THREAD

**Issue by fengzidk** [alibaba/transmittable-thread-local#383]
根据业务场景,在线程传递完成后需要进行一些默认的初始化操作
例如: 根据传递的ThreadLocal值 初始化子线程的数据源信息

目前`TransmittableThreadLocal.set()`方法不允许被重写,如何在不修改源码的前提下实现?

**Comment by oldratlee** [comment]
`ThreadLocal`（`TransmittableThreadLocal`是`Thread`，子类）的初始化 

- 通过直接语义对应的扩展`protected`方法 [`initialValue`](https://docs.oracle.com/javase/10/docs/api/java/lang/ThreadLocal.html#initialValue())（不需要用户使用时来调用）
- 而不是通过 要用户调用 语义不对应的 `set`方法。

@fengzidk
