### ISSUE TITLE
ForkJoinPool提交的任务是一个runnable类型的，请问这种可以直接把runnable转成ttlRunnable来达到开启ttl的目的吗？

### ISSUE THREAD

**Issue by DockerFan** [alibaba/transmittable-thread-local#384]
debug看业务代码ForkJoinPool的execute方法里的传参是个runnable类型，那可以把一个ForkJoinTask的任务强转成一个runnable，然后处理成ttlRunnable类型这样来开启ttl吗？

**Comment by oldratlee** [comment]
@DockerFan

1. 你可以测试一下，验证效果。
1. 要给一下完整的代码（以确认具体的使用方式） 并 说明你的运行效果期望。

**Comment by DockerFan** [comment]
> 先介绍下背景：有个被测服务里面使用了CompletableFuture.supplyAsync提交了一个Runnable任务到ForkJoinPool，然后sandbox-repeater绑定到被测服务以后需要把每个主请求下面的所有子请求根据traceId进行关联(所谓主请求就类似是浏览器发送的http请求，子请求就是处理这个http请求所涉及到的中间件的交互)，所以会涉及到线程池上下文拷贝的问题，但是sandbox-repeater处理的是加载到jvm后的处理。
目前解决方案：一.将ttl-agent绑定到被测服务，这样对于ForkJoinPool所有线程池方法都进行了增强，理论上是不是就可以通过sandbox-repeater从TransmittableThreadLocal拿到正确的上下文拷贝结果呢？
二.通过反射机制，将ForkJoinPool 的execute(Runnable task) 如下方法的runnable转成ttlRunnable
`public void execute(Runnable task) {
        if (task == null)
            throw new NullPointerException();
        ForkJoinTask<?> job;
        if (task instanceof ForkJoinTask<?>) // avoid re-wrap
            job = (ForkJoinTask<?>) task;
        else
            job = new ForkJoinTask.RunnableExecuteAction(task);
        externalPush(job);
    }`
目前看两种方式都没成功，不知道是哪块理解和使用不到位，期待您的回复。

**Comment by oldratlee** [comment]
> * 然后`sandbox-repeater`绑定到被测服务以后需要把每个主请求下面的所有子请求根据`traceId`进行关联
>   （所谓主请求就类似是浏览器发送的`http`请求，子请求就是处理这个`http`请求所涉及到的中间件的交互）
> * 所以会涉及到线程池上下文拷贝的问题，但是`sandbox-repeater`处理的是加载到`jvm`后的处理

@DockerFan 目前`TTL`没有支持 Attach方式『对已加载的类做增强』。 更多说明参见 已有的 issue：

- #380

**Comment by oldratlee** [comment]
https://zhuanlan.zhihu.com/p/503149395

这篇提到：解决了 `TTL`运行时生效增强 的问题；并给了代码实现库。

具体解决的情况，你可以看看。 @DockerFan

**Comment by oldratlee** [comment]
先 close 了；有进一步问题可以继续讨论。

**Comment by JasonMing** [comment]
@DockerFan 之前我自己做了一个方案，分两步

1. `ForkJoinTask` 里面插入字段 `private final Object captured = capture();`
2. 在 `doExec()` 中插入包装 `Object backup; try { backup = replay(captured); <...原有代码...>} finally { restore(backup); } `

这步由于涉及到添加字段，如果类已加载则会失效，必须保障在类初始化之前进行增强。
