### ISSUE TITLE
探讨线程池子线程变量是否需要去掉

### ISSUE THREAD

**Issue by dajitui** [alibaba/transmittable-thread-local#394]
![a](https://user-images.githubusercontent.com/30230907/178236891-dcd5c29e-a424-40bf-b19b-959ecb3b93bf.jpg)

我们可以看到线程池单个线程的话，子线程set变量会透传到下次，我想探讨下这样做是否合理？
因为线程池虽然是复用，但是我们实际每次都是新的任务，不能说上次set的东西污染到下次的任务。

而且如果说透传嘛，线程池里面其他线程又拿不到这个值

![image](https://user-images.githubusercontent.com/30230907/178239504-572f1043-dbb1-4b0a-b4e5-f77ad1a8b5b2.png)

我们再来看下这个，如果说子线程可以透传的话，线程之间又是隔离的

**Comment by dajitui** [comment]
@oldratlee 大佬，我提了个想法，期待一起讨论~

**Comment by yungyu16** [comment]
这种属于 业务上自己没有清理吧

**Comment by dajitui** [comment]
> @dajitui 上面你给的代码里的使用方式，是当作`InheritableThreadLocal`在使用，所以是你示例中所描述的效果。
> 
> 如果要使用成`TransmittableThreadLocal`，需要`wrap`线程池或`Runnable`。
> 
> 上面这些使用方式在[用户文档](https://github.com/alibaba/transmittable-thread-local/blob/bc91c14be8e73a22be20cd5eb74a6a8bb560183a/README.md#2-%E4%BF%9D%E8%AF%81%E7%BA%BF%E7%A8%8B%E6%B1%A0%E4%B8%AD%E4%BC%A0%E9%80%92%E5%80%BC)中有说明，你可以看一下 ❤️
> 
> 示例代码修改如下：
> 
> ## Demo Code 1
> 输出：`print null`，预期。
> 
> ```java
> import com.alibaba.ttl.TransmittableThreadLocal;
> import com.alibaba.ttl.threadpool.TtlExecutors;
> 
> import java.util.concurrent.ExecutorService;
> import java.util.concurrent.Executors;
> 
> public class Demo {
>     public static void main(String[] args) throws Exception {
>         // wrap `ExecutorService` by `TtlExecutors.getTtlExecutorService`
>         ExecutorService executorService = TtlExecutors.getTtlExecutorService(Executors.newFixedThreadPool(1));
>         TransmittableThreadLocal<Integer> context = new TransmittableThreadLocal<>();
> 
>         executorService.execute(() -> context.set(1));
> 
>         executorService.execute(() -> System.out.println("print " + context.get()));
>     }
> }
> 
> /*
> 
> An output:
> 
> print null
> 
>  */
> ```

是的，原来是我使用错了方法，尴尬哈哈
我觉得这样是合理的，线程池即使复用也不应该变量互相污染，感谢大佬的解答

**Comment by oldratlee** [comment]
先 close 了。有问题可以继续讨论。
