### ISSUE TITLE
本地DEBUG进不到JdkExecutorTtlTransformlet里面

### ISSUE THREAD

**Issue by MentosL** [alibaba/transmittable-thread-local#408]
env：macos，jdk8

1. 本地项目里通过`new ThreadPoolExecutor`方式创建线程池。
2. 项目里通过`@Bean`方式注入对应ThreadPoolExecutor到容器里。

通过-javaagent的方式进行启动项目，发现在对应启动过程中，并没进入到JdkExecutorTtlTransformlet中进行增强线程的使用，想请问下当前不生效的原因有哪些（通过arthas查看对应的class文件，发现并没有`TtlTransformletHelper`类的加载）

**Comment by oldratlee** [comment]
关于agent的debug要查一下资料，我自己也没去debug过（写通过单元测试验证）。 @MentosL 



> 没进入到JdkExecutorTtlTransformlet中进行增强线程的使用

可能和你的运行方式相关，如果要大家来给排查需要提供一个简单可运行复现问题的demo
（方便排查的人能运行起来）

**Comment by MentosL** [comment]
谢谢回复。

我本地是通过IDEA debug形式进行查看的，同时服务启动之后，也通过arthas工具查看当前classloader装载情况，发现没有生效的情况。

好的，我晚一点提供一个简单的demo放到这边。

**Comment by MentosL** [comment]
提供了一个简易版本的 [Demo](https://github.com/MentosL/ttl-demo),辛苦大佬麻烦查看下，本地是通过arthas进行查看字节码增强的

**Comment by OrezzerO** [comment]
分享一下我的 DEBUG agent 的方案: 

1. 应用程序启动时添加 debug 参数: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 (如果是用 IDE 启动, 请使用正常运行模式启动,而不是debug 模式)
2. 在 Agent 项目中, 新建远程DEBUG , 连接到本地 5005 端口.


![image](https://user-images.githubusercontent.com/13081689/208363991-88624f61-7de8-4b75-9e7b-5d84e0756382.png)


这样就能debug agent 了

**Comment by jiangyunpeng** [comment]
把  agent 项目源码作为module
