### ISSUE TITLE
Tocmat8.0.26Version,transmittable2.13.2Version,SpringAsyncRequest时会丢失数据

### ISSUE THREAD

**Issue by simonHome** [alibaba/transmittable-thread-local#409]
Tocmat=8.0.26V

transmittable=2.13.2V

Spring Async Request时,在Filter中设置ThreadLocal数据,但在Deferredresult.SetResult()后,在filter中HttpServletResponse重写OutStream方法时已经无法从ThreadLocal中获取数据,但在Tocmat=8.044版本中没有发现这个问题.

```java
public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) {
 set ThreadLocal
 HttpServletResponse resWrapper = new HttpServletResponseWrapper(servletResponse) {
            @Override
            public ServletOutputStream getOutputStream() throws IOException {
                get ThreadLocal (8.0.26版本tomcat会丢失,8.0.44版本不会丢失)
            }
}
```

**Comment by simonHome** [comment]
又再次验证了一下，只要Tocmat>8.0.26V 版本就可以

**Comment by oldratlee** [comment]
关于 Tomcat 可以看一下 相关的 issue：

- #231

作为`TTL`的使用（在`Tomcat`下），这些差异具体要结合`Tomcat`的实现与`TTL`的使用方式排查一下使用了。  @simonHome  `Tomcat`我也不熟悉。

-----



这个 issue 先 close 了。
