### ISSUE TITLE
二方包兼容ThreadLocal

### ISSUE THREAD

**Issue by Gs1mpleL** [alibaba/transmittable-thread-local#412]
有什么方式一次性把所有的ThreadLocal全部注册么，目前看见公司代码是for遍历注册的，但是看registerThreadLocal（）这个方法需要不断new新的map，还要数据转移

**Comment by oldratlee** [comment]
> 有什么方式一次性把所有的ThreadLocal全部注册么

这个问题在下面的 issue 中有讨论过了：  @Gs1mpleL 

- https://github.com/alibaba/transmittable-thread-local/issues/171#issuecomment-611331743

这个 先 close 了。

**Comment by oldratlee** [comment]
> `registerThreadLocal()`这个方法需要不断new新的map，还要数据转移

如果你觉得
- 这个实现 不优 
- 或是 可以结合你自己的业务场景

`TTL 2.14.0`提供了 可以自己实现集成的扩展入口。
https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.14.0

即不用`TTL`提供的实现方式，改成自己的实现。  @Gs1mpleL
