### ISSUE TITLE
TtlWrapper#unwrap 访问级别为何用 default

### ISSUE THREAD

**Issue by HessTina-YuI** [alibaba/transmittable-thread-local#415]
请问 com.alibaba.ttl.spi.TtlWrapper#unwrap 这个方法为何不设置为 public，我想要获取到我注册进去的 ThreadPoolExecutor 对象的一些信息。虽然我能通过反射调用这个方法，但是我很好奇为什么要这么设计。

**Comment by oldratlee** [comment]
com.alibaba.ttl.spi.TtlWrapper 是 Java 接口，接口的声明的方法（只能）是`public`的。即 `TtlWrapper#unwrap`是 public 的。

提供了通用的unwrap方法实现:`com.alibaba.ttl.TtlUnwrap#TtlUnwrap`: @HessTina-YuI 

https://github.com/alibaba/transmittable-thread-local/blob/2.x/src/main/java/com/alibaba/ttl/TtlUnwrap.java

**Comment by Throbing** [comment]
我想通过他拿到线程池里的当前活动线程数

**Comment by Throbing** [comment]
im sorry,通过调用TtlExecutors.unwrap(yourExecutorService)之后，会被解封装为ThreadPoolExecutor，强转直接调用getActiveCount()即可

**Comment by oldratlee** [comment]
@Throbing 好的。

这个先close了，有问题可以继续讨论。

**Comment by HessTina-YuI** [comment]
好的，谢谢解答

**Comment by HessTina-YuI** [comment]
> 很有用，谢谢

**Comment by HessTina-YuI** [comment]
> `com.alibaba.ttl.spi.TtlWrapper`是`Java`接口，接口中的声明的方法（只能）是`public`的。即 `TtlWrapper#unwrap`是`public`的，而不是`default`。
> 
> @HessTina-YuI 提供了通用的`unwrap`方法实现 `com.alibaba.ttl.TtlUnwrap#TtlUnwrap`（使用和实现不需要反射）:
> 
> https://github.com/alibaba/transmittable-thread-local/blob/2.x/src/main/java/com/alibaba/ttl/TtlUnwrap.java

很有用，谢谢
