### ISSUE TITLE
将TTL注册到IOC容器中时，能否通过ApplicationContext获取到TTL包装的真正执行任务的线程池？主要是想要检测线程池的运行状态

### ISSUE THREAD

**Issue by hubingkuan** [alibaba/transmittable-thread-local#416]
比如getPoolSize()  getCompletedTaskCount()  getActiveCount() getQueue().size()  等等

**Comment by oldratlee** [comment]
获取到TTL包装的真正执行任务的线程池，参见 issue:  @hubingkuan 

- #415

**Comment by hubingkuan** [comment]
感谢解答
