### ISSUE TITLE
不修饰Runnable也能传参？

### ISSUE THREAD

**Issue by Dreamroute** [alibaba/transmittable-thread-local#434]
看到使用说明中说，需要修改`Runnable`和`Callable`方能传参，那么我这种使用，是不是意味着不修饰也能传？
还是说我理解有问题？

```java
class TtlTest {

    private static final ThreadLocal<String> TL = new TransmittableThreadLocal<>();
    private static final ExecutorService pool = Executors.newFixedThreadPool(10);

    @Test
    void ttl() throws Exception {
        TL.set("Jay");
        pool.submit(() -> {
            String name = TL.get();
            System.err.println(name);
            // 也能获取到参数
        });
        SECONDS.sleep(2000);
    }

}
```

**Comment by oldratlee** [comment]
> 看到使用说明中说，需要修改`Runnable`和`Callable`方能传参，那么我这种使用，是不是意味着不修饰也能传？

如果不修饰，`TransmittableThreadLocal `的效果就退化成是 `JDK`的[`InheritableThreadLocal`](https://docs.oracle.com/javase/10/docs/api/java/lang/InheritableThreadLocal.html)。 @Dreamroute

**Comment by Dreamroute** [comment]
果然，如果提前为线程池预热，比如执行若干次pool.submit(() -> {}); 那么就无法获取到值了。
