### ISSUE TITLE
为什么默认ttl线程不会释放父线程传递下来的参数呢

### ISSUE THREAD

**Issue by 985177520** [alibaba/transmittable-thread-local#446]
![image](https://user-images.githubusercontent.com/43394661/203576150-3e2ba987-fa17-4137-9c71-0f559bfd54f8.png)
我使用ttl，传递变量，结果这个变量不会自动清空，为什么默认设置为false，需要解答下感恩

**Comment by oldratlee** [comment]
- 这个做法对于业务使用更方便，支持可能运行多次
- 正常情况下（合理设计、无`TtlRunnable`泄露），`TtlRunnable`不做清空几乎没有影响
- `TtlRunnable`泄露时，可以通过这个参数多一层控制机会

**Comment by oldratlee** [comment]
- 这个做法对于业务使用更方便，支持可能运行多次
- 正常情况下（合理设计、无`TtlRunnable`泄露），`TtlRunnable`不做清空几乎没有影响

设置这个参数的好处（要用户多一些注意）：

- 对于运行一次的`TtlRunnable` 可以作为一个断言或说防御式编程
- 对于`TtlRunnable`泄露时，可以用这个参数可以多一层控制机会

**Comment by 985177520** [comment]
> 这个做法（缺省值`false`）:
> 
> * 支持运行多次的情况，于业务使用更简单方便
> * 正常情况下（合理设计、无`TtlRunnable`泄露），`TtlRunnable`不做清空几乎没有影响
> 
> 设置这个参数成`true`的好处（要用户多一些注意）：
> 
> * 对于运行一次的`TtlRunnable` 可以作为一个断言或说防御式编程
> * 对于`TtlRunnable`泄露时，可以用这个参数可以多一层控制机会

可是我现在在线程池使用这个东西，蛮容易造成泄露的，因为这个线程创建后有存活时间。所以就会觉得蛮奇怪的

**Comment by 985177520** [comment]
> 这个做法（缺省值`false`）:
> 
> * 支持运行多次的情况，于业务使用更简单方便
> * 正常情况下（合理设计、无`TtlRunnable`泄露），`TtlRunnable`不做清空几乎没有影响
> 
> 设置这个参数成`true`的好处（要用户多一些注意）：
> 
> * 对于运行一次的`TtlRunnable` 可以作为一个断言或说防御式编程
> * 对于`TtlRunnable`泄露时，可以用这个参数可以多一层控制机会

大佬再问个事情，我现在用美团动态线程池启用ttl，因为默认这个参数为false。我第一个主线程给某个参数设置A，子线程可以正确拿到A。但是我另外一个主线程，从线程池拿线程也拿到了A，此时没有创建新的子线程（此时主线程应该参数应该是B的），是因为线程复用导致的这个问题吗。

**Comment by 985177520** [comment]
这就导致了另外一个疑问了，如果我设置为true，我2主线程下次进入到同一个子线程时，只要这个子线程参数正确清空，就会正确把上下文往下传递咯，但是如果我不清空就不会咯。

**Comment by 985177520** [comment]
这就导致了另外一个疑问了，如果我设置为true，我2主线程下次进入到同一个子线程时，只要这个子线程参数正确清空，就会正确把上下文往下传递咯，但是如果我不清空就不会咯。感谢大佬解答一下，最近用这个东西有点困惑
