### ISSUE TITLE
主线程的值如果再次被设置，子线程获取的值是第二次设置的值

### ISSUE THREAD

**Issue by qijun4tian** [alibaba/transmittable-thread-local#465]
场景是这样的，我们是异步导出的。第一个http请求过来会把用户信息存在threadlocal中，tomcat请求本生也是线程池，并发量大的时候，第二个请求再进来的时候会复用线程，重新设置父线程的值，而第一个请求线程开启的异步线程获取的用户信息就变成第二个请求的用户信息。这时候就发生了错误

**Comment by oldratlee** [comment]
> 第二个请求再进来的时候会复用线程，重新设置父线程的值，而第一个线程开启的异步线程获取的用户信息就变成第一个。

虽然你没有给代码，猜测你的实现传递是一个上下文对象的引用。

即两次传递的值（传递的是引用）一样的，两次请求共享了上下文对象，自然第一次请求会被第二次的修改影响。
（传递是`TTL`的功能，传递什么值 是你业务的设计。）

-----

这是并发设计。推荐调整一下设计，比如可以： @qijun4tian 

传递的不同的上下文对象（不要共享），自然没有被修改的问题。

**Comment by qijun4tian** [comment]
> > 第二个请求再进来的时候会复用线程，重新设置父线程的值，而第一个线程开启的异步线程获取的用户信息就变成第一个。
> 
> 虽然你没有给代码， 猜测你的业务实现所传递的是 同一上下文对象（包含用户信息）的引用。 @qijun4tian
> 
> 即两个请求`TTL`传递的值（上下文对象的引用）一样的， 两个请求共享了同一个上下文对象， 自然 第二个请求的修改 会影响 第一个请求处理过程中读到的。
> 
> 传递是`TTL`的功能； 传递什么值、有没有共享，这是使用方的业务设计。
> 
> 可以试试调整一下设计，比如： @qijun4tian
> 
> 传递新的不同上下文对象（的引用）； 没有共享，自然没有 被其它请求处理过程修改的问题。

`
// WebContext.java
ThreadLocal<Map<String, Object>> context;
TransmittableThreadLocal<Map<String, Object>> transmitContext;
public Object get(Object key) {
        Object o = context.get().get(key);
        if(o != null) {
            return o;
        }
        return transmitContext.get().get(key);

    }

// ExportAspectJ.java
CompletableFuture.supplyAsync(() -> {
                try {
                    
                    String ossUrl = (String) pjp.proceed();
                    long endTime = System.currentTimeMillis();
                    return ossUrl;
                } catch (BusinessException e) {
                    throw e;
                } catch (Throwable throwable) {
                    throw new BusinessException("execute export method failed", throwable);
                }


// 在pjp.proceed() 中会去使用WebContext 去获取从ExportAspectJ通过TTL 传递的值
WebContext 每次http请求过来都会重新设置。
`

**Comment by qijun4tian** [comment]
我知道了。只能是值传递

**Comment by oldratlee** [comment]
> 我知道了。是因为我用的map。

👍 发现并能解决问题就好。

> ```java
> // WebContext.java
> 
> ThreadLocal<Map<String, Object>> context;
> 
> TransmittableThreadLocal<Map<String, Object>> transmitContext;
> 
> public Object get(Object key) {
>     Object o = context.get().get(key);
>     if(o != null) {
>         return o;
>     }
>     return transmitContext.get().get(key);
> }
> ```

另外，

这个`get`的实现，先读`ThreadLocal context`（无传递功能），再读`transmitContext`，有潜在问题；
具体引发的问题要看你的业务场景。

**Comment by qijun4tian** [comment]
> > 我知道了。是因为我用的map。
> 
> 👍 发现并能解决问题就好。
> 
> > ```java
> > // WebContext.java
> > 
> > ThreadLocal<Map<String, Object>> context;
> > 
> > TransmittableThreadLocal<Map<String, Object>> transmitContext;
> > 
> > public Object get(Object key) {
> >     Object o = context.get().get(key);
> >     if(o != null) {
> >         return o;
> >     }
> >     return transmitContext.get().get(key);
> > }
> > ```
> 
> 另外，
> 
> * 这个`get`的实现
>   
>   * 先读`ThreadLocal context`（无传递功能）
>   * 再读`transmitContext`
>   * 感觉容易踩坑；具体引发的问题要你看业务场景。
> * 因为有多线程共享，还要注意线程安全、同步，如
>   
>   * 使用`ConcurrentMap`，而不能简单地使用`HashMap`

```
    private static TransmittableThreadLocal<Map<String, Object>> transmitContext =
            TransmittableThreadLocal.withInitialAndCopier(HashMap::new, e->{
                String s = JSONObject.toJSONString(e);
                return (Map<String,Object>) JSONObject.parseObject(s,Map.class);
            });
```

默认是引用传递而不是深拷贝，深拷贝了应该就没有线程安全问题。

> 使用ConcurrentMap，而不能简单地使用HashMap
这个应该没关系吧。

**Comment by oldratlee** [comment]
> **TransmittableThreadLocal.withInitialAndCopier** 可以使用手册中感觉可以突出下，不然很多人使用了没有注意到其中可能隐藏的线程安全问题

关于线程安全的问题，文档中用户使用开篇就有说明： @qijun4tian   
(如果不理解并发，简单几行文档也解决不了问题；所以文档中点到即止）

![image](https://user-images.githubusercontent.com/1063891/218420335-834cc922-cf30-480d-8d22-466d7b354b08.png)

-------

> 默认是引用传递而不是深拷贝，深拷贝了应该就没有线程安全问题。
> `ConcurrentMap，而不能简单地使用HashMap`
> 这个应该没关系吧。

并发的设计与分析，你自己看吧 💗 
也和你的具体业务实现逻辑相关～

**Comment by qijun4tian** [comment]
> 你自己看一下吧

感谢大佬，还是我太菜了。感谢！！！
