### ISSUE TITLE
复现TransmittableThreadLocal数据在「不用TtlExecutors包裹的线程池」中概率丢失。

### ISSUE THREAD

**Issue by Webgasd** [alibaba/transmittable-thread-local#485]
TransmittableThreadLocal数据在「不用TtlExecutors包裹的线程池」中概率丢失。
请问能介绍下在什么情况下会丢失呢？目前无法复现出这个问题。

**Comment by oldratlee** [comment]
> 请问能介绍下在什么情况下会丢失呢？目前无法复现出这个问题。

@Webgasd 正确使用`TransmittableThreadLocal`的情况下，不应该有`TransmittableThreadLocal`数据概率丢失，否则是`TransmittableThreadLocal`的**Bug**。

所以，问题可以转成了，不正确使用`TransmittableThreadLocal`的方式有哪些？

这个问题比较开放 & 猜测碰运气，相比而言还是检查实现保证正确使用来的简单 🤣

-----

推荐了解一下`TransmittableThreadLocal`的使用方式（比如看一下文档），把正常的使用改正确就好了。比如

- 使用`TtlExecutors` wrapper
- 或者使用像`TtlRunnable` wrapper
- 或者使用`TTL Agent`

具体看一下 TTL的使用文档～ ❤️  @Webgasd
