### ISSUE TITLE
agent中对普通Thread场景进行包装，来触发copy方法

### ISSUE THREAD

**Issue by songxiaosheng** [alibaba/transmittable-thread-local#517]
### 描述
使用TransmittableThreadLocal时候对普通的Thread会实现自动拷贝线程数据，如果是ThreadLocal中的数据是对象只能进行深拷贝，无法触发重写的copy方法，如果是否agent中可以增加对普通线程的处理为Runnable增加包装让普通线程传递数据时候也触发copy方法
### 期望
期望普通线程的传递也能触发重写的copy方法，这样可以统一管控对象传递过程中的数据内容

### 样例代码

测试代码如下：
```java
public class ObjectCopyInThreadDemo {

    private final TransmittableThreadLocal<TtlObject> ttlObjectThreadLocal = new TransmittableThreadLocal<TtlObject>() {
        @Override
        public TtlObject copy(TtlObject parentValue) {
            if(parentValue != null){
                try {
                    return (TtlObject) parentValue.clone();
                } catch (CloneNotSupportedException e) {
                    throw new RuntimeException(e);
                }
            }
            return super.copy(parentValue);
        }
    };
    public static void main(String[] args) {
        ThreadDemo a = new ThreadDemo();
        a.doBussiness();
    }
    public void doBussiness() {

        TtlObject value = new TtlObject();
        System.out.println(value);
        ttlObjectThreadLocal.set(value);

// 未使用TtlRunnable类型时候不会走重写的copy方法，默认情况是会共享对象
//        (new Thread(TtlRunnable.get(new Runnable() {
        (new Thread((new Runnable() {

            @Override
            public void run() {
                System.out.println("子线程启动");
                TtlObject ttlObject = ttlObjectThreadLocal.get();
                System.out.println(ttlObject);
            }
        }))).start();
    }
}
```

```java
public class TtlObject {

    private String name;

    @Override
    protected Object clone() throws CloneNotSupportedException {
        TtlObject ttlObject = new TtlObject();
        ttlObject.setName(this.name);
        return ttlObject;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

**Comment by oldratlee** [comment]
`copy`方法 与 `Agent`使用方式 是独立正交的。
\# 在使用上，`Agent`方式只是省去`API`方式要写的代码行（如调用`TtlRunnable.get()`、`TtlExecutors.getTtlExecutorService()`）。

`copy()`触发有确定的时机。

你这里说的时机（`new Thread`时），应该的是`InheritableThreadLocal.childValue()`。你可以重写`InheritableThreadLocal.childValue()`： @songxiaosheng 

```java
protected T childValue​(T parentValue) {
  return copy(parentValue);
}
```

在这个已有 Issue 中有展示讨论： 

- https://github.com/alibaba/transmittable-thread-local/issues/383#issuecomment-1139382259

摘一下内容如下：

> ## 关于初始化方法
> 
> 相关的初始化方法还有 [`ThreadLocal#initialValue()`](https://docs.oracle.com/javase/10/docs/api/java/lang/ThreadLocal.html#initialValue())。
> 
> 这3个初始化方法 的区别是 做初始化操作的 生命周期时间点/触发时间 不同：
> 
> 1. **`ThreadLocal#initialValue()`**
>     - `ThreadLocal`没有值时，取值（`ThreadLocal#get()`方法）触发初始化。
>     - 下面是一些**注意点**：
>     - `ThreadLocal#initialValue()`是 **Lazy**的；
>       即创建`ThreadLocal`实例时，并不会触发`ThreadLocal#initialValue()`调用。
>     - 先设置值（`ThreadLocal#set(T)`）再取值，则不会触发调用`ThreadLocal#initialValue()`；因为已经有值了。
>       即使设置的是`null`，也不会触发。
>     - 调用`ThreadLocal#remove()`再取值，会触发调用`ThreadLocal#initialValue()`；因为没有值了。
> 1. **`InheritableThreadLocal#childValue(T)`**
>     - 创建新线程时，用于初始化子线程的`InheritableThreadLocal`值。
> 1. **`TransmittableThreadLocal#copy(T)`**
>     - 传递时，用于初始化 在任务（如`TtlRunnable`）执行中的`TransmittableThreadLocal`值。
> 
> ### 不同初始化方法是独立正交的
> 
> 这里可能值得强调一下这3个初始化方法的**容易被忽视**的地方：**3个方法是独立正交的。**
> （好的系统设计应该这样，不同功能独立正交；系统大的功能 是通过 方便地组合/使用更小的功能 来实现。）
> 
> 展开一些的说明如下：
> 
> - 因为生命周期时间点/触发时间 不同，各自独立发挥作用。
> - 子类包含进来的父类初始化方法，功能不变。
>     - `InheritableThreadLocal`是`ThreadLocal`的子类，包含的`ThreadLocal#initialValue()`功能不变。
>     - `TransmittableThreadLocal`是`InheritableThreadLocal`的子类，包含的`ThreadLocal#initialValue()`、`InheritableThreadLocal#childValue(T)`功能不变。

**Comment by songxiaosheng** [comment]
感谢回复我研究下
