### ISSUE TITLE
“业务项目”在通过bytebuddy增强后，TTL+CompletableFuture无法再正常地进行上下文传递。

### ISSUE THREAD

**Issue by Nietzschecat** [alibaba/transmittable-thread-local#519]
## 1、问题简述

在开发「流量回放工具」时，「流量回放工具」内部通过使用`bytebuddy`，在不侵入“业务项目”的情况下，对“业务项目”的各种外部调用进行数据`Mock`。

在“业务项目”中通过`Maven`引入「流量回放工具」的`jar`包，且在“业务项目”启动时对特定的类做字节码增强（未增强`CompletableFuture`等并发类）后，`TTL+CompletableFuture`无法再正常进行上下文数据传递。

简言之：“业务项目”在通过`bytebuddy`增强后，`TTL`+`CompletableFuture`无法再正常地进行上下文传递。

## 2、测试代码

```java
public static ThreadLocal<String> ttlA = new TransmittableThreadLocal<>();
public static ThreadLocal<String> ttlB = new TransmittableThreadLocal<>();
public static ThreadLocal<String> ttlC = new TransmittableThreadLocal<>();
// 使用单个线程进行测试
public static ExecutorService executorService = TtlExecutors.getTtlExecutorService(Executors.newFixedThreadPool(1));

public void testCompletableFutureTTL() {
    ttlA.set("111");
    ttlB.set("222");
    ttlC.set("333");

    CompletableFuture.supplyAsync(() -> {
        System.out.println(ttlA.get());
        System.out.println(ttlB.get());
        System.out.println(ttlC.get());
        return null;
    }, executorService);

    // 变更了ttlA的值为“888”，理论上子线程也会变更
    ttlA.set("888");
    // 删除了ttlB，理论上子线程ttlB会变为null
    ttlB.remove();

    CompletableFuture.supplyAsync(() -> {
        System.out.println(ttlA.get());
        System.out.println(ttlB.get());
        System.out.println(ttlC.get());
        return null;
    }, executorService);
}
```

## 3、问题复现

`transmittable-thread-local`版本：2.12.2

### 情况一：未通过`bytebuddy`增强

（1）执行结果（符合预期）：

![fffbab7a649e4cd79b55357c572c8e19](https://github.com/alibaba/transmittable-thread-local/assets/16161913/4fcd1e14-3df6-48ac-9ee1-e51303a5f9c2)

（2）debug过程（符合预期）：

![0d9136484d10601990958c270ef31f88](https://github.com/alibaba/transmittable-thread-local/assets/16161913/1259302c-bb33-4ae1-8ab7-f11f9d8504bf)

![c6943cf2db0b4595fe72466c102f624f](https://github.com/alibaba/transmittable-thread-local/assets/16161913/165c6343-e892-4a44-9b08-7dbb825660ef)

### 情况二：使用`bytebuddy`进行增强

（1）执行结果（不符合预期）：

![image](https://github.com/alibaba/transmittable-thread-local/assets/16161913/00e8b18b-ca66-4754-b46c-46440a2391cc)

（2）`debug`过程：

![image](https://github.com/alibaba/transmittable-thread-local/assets/16161913/83f920d4-a7a5-45ff-91a8-e6a3096c05c2)

最奇怪的地方：执行到`supplyAsync`时，仍是主线程，但是`TransmittableThreadLocal`却生成了新的`holder`，仿佛有切面逻辑，但是我在`TTL`源码中没找到切面逻辑。

![image](https://github.com/alibaba/transmittable-thread-local/assets/16161913/98c649d5-29fd-4930-baa4-ba12e90a7125)

主线程的`ttlA.set("888"); ttlB.remove();`操作没生效。子线程内的数据仿佛快照一样，定格在了第一次执行时的上下文，数据不再发生任何变化。

![image](https://github.com/alibaba/transmittable-thread-local/assets/16161913/277f4a25-c3f2-4e0e-b2bc-e3ca78ede8b7)

**Comment by oldratlee** [comment]
> 在开发「流量回放工具」时，「流量回放工具」内部通过使用`bytebuddy`，在不侵入“业务项目”的情况下，对“业务项目”的各种外部调用进行数据`Mock`。

你提到的「流量回放工具」也是基于`Java Agent`实现的吧？

如果是，下面是 继续的内容。


> 在“业务项目”中通过`Maven`引入「流量回放工具」的`jar`包，且在“业务项目”启动时对特定的类做字节码增强（未增强`CompletableFuture`等并发类）后，`TTL+CompletableFuture`无法再正常进行上下文数据传递。

「流量回放工具」与 `TTL` 2个`Java Agent`之间的影响，要具体了解2者代码实现与设计才能确定。

仅通过上面的结果无法排查。 @Nietzschecat
