### ISSUE TITLE
关于registerThreadLocal方法加锁和copy on write疑问

### ISSUE THREAD

**Issue by xxd137494375** [alibaba/transmittable-thread-local#528]
在看`2.14.2`版本的源码中，发现`registerThreadLocal`函数在处理`threadLocalHolder`并发修改问题时，即加了锁，又使用了`copy on write`思想。

对于这里有个疑问，加了锁，已经保证了线程安全，为何还要使用`copy on write`？

是在考虑什么隐藏问题吗？

https://github.com/alibaba/transmittable-thread-local/blob/d91853ea3d3501e913f7ac9b35053cc514a86aee/src/main/java/com/alibaba/ttl/TransmittableThreadLocal.java#L1013-L1027

**Comment by oldratlee** [comment]
@xxd137494375 好问题 👍 其实这个在小伙伴写的文章或评论中多次看到了～

- #123 

----

> 对于这里有个疑问，加了锁，已经保证了线程安全，为何还要使用`copy on write`？

### 简单说明

> 这里我自己只做一些简单说明；并发相关的问题要真正解释清楚，可能要带来太多内容。

- 加锁是为了「并发」更新的线程安全（如加锁可以避免更新数据的丢失）
  - 注意，实现上只对写操作加锁了，读操作没有加锁。
- `COW`是因为
  - 读操作通过`threadLocalHolder`的`volatile`来发布安全引用
  - `volatile`并不保证引用修改时的原子性，通过`COW`再更新`volatile`来保证安全发布引用对象的内容。
  - https://github.com/alibaba/transmittable-thread-local/blob/d91853ea3d3501e913f7ac9b35053cc514a86aee/src/main/java/com/alibaba/ttl/TransmittableThreadLocal.java#L939-L941

### 更多相关的可以看看

单例的`Double Check`实现方式，有很多讨论，涉及相同的关注点。

### 系统了解

力荐研读《[Java并发编程实战](https://book.douban.com/subject/10484692/)》。
上面的问题及其要注意的，只是基本内容。
