### ISSUE TITLE
有必要关闭Inheritable能力么

### ISSUE THREAD

**Issue by songxiaosheng** [alibaba/transmittable-thread-local#531]
多线程场景存在new Thread的场景，对于这种场景如果关闭Inheritable能力意味着，无法传递数据 ，当前版本的agent并有去处理这种场景，如果不关闭的话所有子线程（包含框架内部的很多线程都会触发clone方法进行无意义的clone), 如果关闭了Inheritable能力该如何在new Thread场景下自动传递，而无需改动现有代码
https://github.com/alibaba/transmittable-thread-local/issues/100
这个Issue中解释了 为什么要做关闭Inheritable能力的原因

**Comment by oldratlee** [comment]
`TTL`直接提供了「关闭`线程池中线程`的`inheritable`能力」的功能： @songxiaosheng 
`getDisableInheritableThreadFactory()`。

不是关闭`所有`线程的`inheritable`能力。
（当然也可实现，见`TransmittableThreadLocal`的javadoc）

- https://github.com/alibaba/transmittable-thread-local/issues/488#issuecomment-1490321767
- #100

**Comment by songxiaosheng** [comment]
是否考虑后续new Thread场景 通过agent方式修改Runnable类型为TtlRunnable类型

**Comment by oldratlee** [comment]
> 有必要关闭Inheritable能力么

由你应用场景、需求决定。 @songxiaosheng 

`TTL`提供了关闭`Inheritable`的一些方法，具体参见`TransmitableThreadLocal`的JavaDoc。

**Comment by oldratlee** [comment]
> 是否考虑后续new Thread场景 通过agent方式修改Runnable类型为TtlRunnable类型

看起来没有必要。
