### ISSUE TITLE
TTL使用完成后需要remove掉当前线程的值吗？如果不删除会不会引发OOM？

### ISSUE THREAD

**Issue by mingyang66** [alibaba/transmittable-thread-local#532]
场景描述：
1.控制器接口A有一个统一的拦截器B,在B中会统一创建TTL对象，设置需传递的值C;
2.控制器接口A中有一个异步线程池，线程池中调用D方法，D方法上有一个拦截器E，在E中会使用传递进来的值C；
3.如果在B中先移除调值C；
那么对于E中使用的值C会不会有问题？测试下来好像没啥问题，但是逻辑上说不通，请帮忙解答下这个问题，谢谢！

**Comment by mingyang66** [comment]
我又认真研究了下TTL，其实主线程将值或者引用传递给子线程之后，两个线程之间其实已经是相对独立的状态，主线程清除当前线程的值或引用，不影响子线程的值或引用； 
     我先在有个问题，如果线程使用过值或引用后不进行remove操作会不会引发OOM？或者引发其它问题？或者是TTL已经帮助做了回收操作？

**Comment by mingyang66** [comment]
父线程已经执行完了，已经将上下文值引用删除，子线程执行完成后又将父线程的值恢复了，这样会不会造成OOM?

**Comment by oldratlee** [comment]
> 父线程已经执行完了，已经将上下文值引用删除，子线程执行完成后又将父线程的值恢复了，这样会不会造成OOM?

因为「恢复」操作，所以不会因为这个传递过程而引入内存泄露。
