### ISSUE TITLE
使用Java agent不生效，通过arthas jad看对应的类，均已被transform，但是trace不到TtlRunnable和TransmittableThreadLocal的执行记录

### ISSUE THREAD

**Issue by AlbertGithubAI** [alibaba/transmittable-thread-local#535]
使用Java agent不生效，通过arthas jad看对应的类，均已被transform，但是trace不到TtlRunnable和TransmittableThreadLocal的执行记录。

运行环境为Tomcat容器，没有使用其它agent。还有没有其它方法来排查？

**Comment by oldratlee** [comment]
> 通过arthas jad看对应的类，均已被transform

运行的业务逻辑上，`TTL Agent`是不是已经生效？ @AlbertGithubAI 

如果`TTL Agent`已经运行时已生效，则可能要看看

- 工具（`arthas`）的使用 
- 或是`trace`是位置是否正确

**Comment by AlbertGithubAI** [comment]
> > 通过arthas jad看对应的类，均已被transform
> 
> 运行的业务逻辑上，`TTL Agent`是不是已经生效？ @AlbertGithubAI
> 
> 如果`TTL Agent`已经运行时已生效，则可能要看看
> 
> * 工具（`arthas`）的使用
> * 或是`trace`是位置是否正确

业务不生效，所以来排查具体的问题，使用agent版本为2.14.2。

**Comment by AlbertGithubAI** [comment]
另外单独使用ExecutorServiceTtlWrapper是可以的，但是加上agent就会有问题。

**Comment by oldratlee** [comment]
> 业务不生效，所以来排查具体的问题，使用agent版本为2.14.2。

关于`Tomcat`下`TTL Agent`的使用，有相关的 issue讨论：

- #231
- #226
- #409
- #516

**Comment by AlbertGithubAI** [comment]
arthas的jad是否会触发ThreadPoolExecutor类的retransform，通过打印Stack Trace发现在jad ThreadPoolExecutor之前没有TtlRunnable的堆栈，但是jad之后就有了，并且jad的结果显示已经被增强了。

**Comment by AlbertGithubAI** [comment]
看了一下arthas jad的原理，发现在排查java agent失效原因的时候不能使用jad命令，因为jad命令会重新触发retransform。

https://github.com/alibaba/arthas/issues/763
