### ISSUE TITLE
CompletableFuture 指定执行器不生效

### ISSUE THREAD

**Issue by guofeiwu** [alibaba/transmittable-thread-local#544]
```java
public class MyThreadPoolExecutor extends ThreadPoolExecutor {
    public MyThreadPoolExecutor(int corePoolSize,
                                 int maximumPoolSize,
                                 long keepAliveTime,
                                 int queueCapacity,
                                 String threadNamePrefix) {
        super(corePoolSize,
        maximumPoolSize,
        keepAliveTime,
        TimeUnit.SECONDS,
        new LinkedBlockingQueue<>(queueCapacity),
        new NamedThreadFactory(threadNamePrefix),
        new ThreadPoolRejectPolicy());
    }
}
```

`@Autowired MyThreadPoolExecutor threadPoolExecutor;`
指定执行器,打印的trace不正常

```java
CompletableFuture.runAsync(() -> {
    log.info(new XXLog()
            .op("TestTraceController")
            .kv("threadname", Thread.currentThread().getName())
            .kv("testtrace","CompletableFuturegetRpcExecutor线程池执行2")
            .toString());
}, threadPoolExecutor);
```

不指定执行器,打印的trace正常

```java
CompletableFuture.runAsync(() -> {
    log.info(new XXLog()
            .op("TestTraceController")
            .kv("threadname", Thread.currentThread().getName())
            .kv("testtrace","CompletableFuturegetRpcExecutor线程池执行2")
            .toString());
});
		
```

采用了TTL agent的方式

**Comment by guofeiwu** [comment]
@abcdea @driventokill

**Comment by guofeiwu** [comment]
# 这种方式子线程也无法获取到父线程的值，是我TTL agent的方式的方式增强失败了吗？

threadPoolExecutor.execute(new MyRun());

public static class MyRun implements Runnable {

		@Override
		public void run() {
			log.info(new XXLog()
					.op("TestTraceController")
					.kv("threadname", Thread.currentThread().getName())
					.kv("testtrace","getRpcExecutor线程池执行")
					.toString());
		}
	}



谢谢！期待回复一下！首次使用TTL

**Comment by oldratlee** [comment]
请提供一个 极简的 可运行复现问题 的代码Demo工程。 @guofeiwu 

推荐提供成一个单独的工程（Github repo），或是 一个运行出的问题的UT（可以Fork TTL加一个UT）。

这样可以

- 方便大家能排查分析（只提供运行结果，排查信息不足）
- 方便分离不相关的业务实现内容，以及排除可能的业务使用问题

**Comment by guofeiwu** [comment]
非常感谢回复！昨天晚上通过debug的方式问题已经找到了，我没有复写以下两个方法
 
public class MyThreadPoolExecutor extends ThreadPoolExecutor


    @Override
    protected void beforeExecute(Thread t, Runnable r) {
        super.beforeExecute(t, r);
    }

    @Override
    protected void afterExecute(Runnable r, Throwable t) {
        super.afterExecute(r, t);
    }
	
不方便用电脑回复，手机回复格式有点乱，等我周末用电脑整理一下，然后在编辑一次，给大家提供思路；

**Comment by oldratlee** [comment]
> 等我周末用电脑整理一下，然后在编辑一次，给大家提供思路；

期待整理 ❤️ @guofeiwu

**Comment by guofeiwu** [comment]
请求到nioEventLoopGroup-8-1线程中执行MyThreadPoolExecutor.execute(new MyRun());
	
	
public static class MyRun implements Runnable {

		@Override
		public void run() {
			log.info(new XXLog()
					.op("TestTraceController")
					.kv("threadname", Thread.currentThread().getName())
					.kv("testtrace","getRpcExecutor线程池执行")
					.toString());
		}
	}
在MyRun线程中，获取不到nioEventLoopGroup-8-1线程中设置的值，nioEventLoopGroup-8-1线程中执行MyThreadPoolExecutor的已经被agent增强过，debug看是增强的。
	
请问一下nioEventLoopGroup线程中的值可以透传到ThreadPoolExecutor的线程池中的线程里吗？

**Comment by oldratlee** [comment]
> 请问一下nioEventLoopGroup线程中的值可以透传到ThreadPoolExecutor的线程池中的线程里吗？

这个是`TTL`的使用，具体我没有了解研究。

**Comment by guofeiwu** [comment]
@oldratlee 你好！

我今天写了一个agent，项目中使用TTL，发现是可以增强的，应该是公司的agent哪里有问题，没增强成功，下周我在公司，替换一个agent试一试，谢谢！

**Comment by oldratlee** [comment]
> @oldratlee 你好！
> 
> 我今天写了一个agent，自己写了新demo中使用TTL，发现是可以增强的，应该是公司的agent哪里有问题，没增强成功，下周我在公司，替换一个agent试一试，谢谢！

好的， issue 先 close 了。
