### ISSUE TITLE
TTL-agent修饰后的ScheduledThreadPoolExecutor的调度任务在取消时，无法从workQueue中清除

### ISSUE THREAD

**Issue by robin-g-20230331** [alibaba/transmittable-thread-local#547]
## 问题及其示例代码

```java
ScheduledThreadPoolExecutor scheduledThreadPoolExecutor = new ScheduledThreadPoolExecutor(1);
scheduledThreadPoolExecutor.setRemoveOnCancelPolicy(true);
Future<?> future = scheduledThreadPoolExecutor.schedule(new Runnable() {
    @Override
    public void run() {
        // do something
    }
}, 100, TimeUnit.SECONDS);
future.cancel(false);
```

<img width="928" alt="image" src="https://github.com/alibaba/transmittable-thread-local/assets/129507601/545c9ef2-2b7f-4615-8483-9819dedbf8fe">

调度线程池设置了任务`cancel`后清理队列的策略；但是任务取消后，队列任务并没有清除。

## 原因

在调度池里，任务都会被修饰为`ScheduledFutureTask`放入队列，并返回`ScheduledFutureTask`类型的`future`，`ScheduledFutureTask`在`cancel`时，会调用`ThreadPoolExecutor`的`remove`方法，而`TTL Agent`会将`ScheduledFutureTask`重新装饰为`TtlRunnable`。

`ScheduledThreadPoolExecutor`中的队列清理方法中的定位逻辑如下，可以明显看到，该方法只会返回`-1`。

<img width="507" alt="image" src="https://github.com/alibaba/transmittable-thread-local/assets/129507601/99a30330-c567-429e-9118-a07cfd5ef15d">

并且，如果这个队列很长，会导致性能非常差。

## 修复建议

`remove`方法不增强。或者判断下类型，如果是`ScheduledFutureTask`类型，就不增强。

**Comment by oldratlee** [comment]
@robin-g-20230331 收到。我确认一下，然后再想想如何修改好。

**Comment by oldratlee** [comment]
@robin-g-20230331 

- reproduce the bug at commit 4b7771f5461d12d976f15121664d6802549feeb3
  - more info see the related CI jobs
- fix the bug at commit 8ca0f9a112fe3210051918eb472973356dcf9e90
  - your solution is teriffic: 👍
  - bypass the enhancement if the runnable argument is type `ScheduledFutureTask`)
- released in `v2.14.4`:
  https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.14.4

------------

Thanks for your professional issue and solution 💗  @robin-g-20230331
