### ISSUE TITLE
java.lang.IllegalStateException: TTL logger implementation type is NOT set!

### ISSUE THREAD

**Issue by tarcyxin** [alibaba/transmittable-thread-local#552]
版本:transmittable-thread-local-2.12.1
问题:项目依赖了ttl,同时启动时-javaagent加载ttl,两者版本都是2.12.1，发现启动时会报java.lang.IllegalStateException: TTL logger implementation type is NOT set! ，移除-agent就没问题

**Comment by oldratlee** [comment]
@tarcyxin 已有 同问题 issue 

- https://github.com/alibaba/transmittable-thread-local/issues/550#issuecomment-1725056609

请提供一个 极简、可运行、复现问题的 代码Demo工程。

推荐提供成一个单独的工程（Github repo）。这样可以：

- 方便大家能排查分析（只提供片段代码、运行结果，排查信息不足）
- 方便分离不相关的业务实现内容，以及排除可能的业务使用问题
  如使用配置问题、其它业务代码的意外影响
