### ISSUE TITLE
-javaagent:D:\jar\transmittable-thread-local-2.14.0.jar 必须使用带版本号的名称，去除版本号会报错

### ISSUE THREAD

**Issue by CleverScarecrow** [alibaba/transmittable-thread-local#562]
![image](https://github.com/alibaba/transmittable-thread-local/assets/31497396/69894460-455a-42a5-8ee5-78c669b60e77)

**Comment by oldratlee** [comment]
@CleverScarecrow 文档有说明和解法：
https://github.com/alibaba/transmittable-thread-local/tree/2.x#java-agent%E7%9A%84%E5%90%AF%E5%8A%A8%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE

![Screenshot_2023-10-19-21-09-47-603_com opera browser-edit](https://github.com/alibaba/transmittable-thread-local/assets/1063891/761fe6fa-892b-419d-a5e9-c0abc89e1180)
