### ISSUE TITLE
k8s环境下CPU调整>2数量后线程上下文传递失效

### ISSUE THREAD

**Issue by llm163520** [alibaba/transmittable-thread-local#579]
代码示例：
<img width="541" alt="e866b2aacd4586cca6bc257e48c3aaf" src="https://github.com/alibaba/transmittable-thread-local/assets/22343834/ea6a59eb-526b-47cd-b443-4f08dde9fdf7">

K8S配置：
<img width="358" alt="4ad5cd0862abf5dee3ec50e166858de" src="https://github.com/alibaba/transmittable-thread-local/assets/22343834/dd717699-acbf-4a0e-b235-fbe6fca1174c">
代码：
`
final  ThreadLocal<Object> key = new TransmittableThreadLocal<>();
key.set("key");
CompletableFuture.runAsync(ThrowingRunnable.throwing(() ->
    System.out.println("key: "+key.get())
)).get();
`

**Comment by oldratlee** [comment]
需要修饰操作，解决方法如下： @llm163520 
（更多具体内容及其使用方式，请查看文档 [👥 User Guide](https://github.com/alibaba/transmittable-thread-local/tree/2.x#-user-guide)）

```java
final ThreadLocal<Object> key = new TransmittableThreadLocal<>();
key.set("key");

final Runnable bizRunnable = ThrowingRunnable.throwing(() ->
  System.out.println("key: "+key•get())
)
// 修饰输入的Runnable
CompletableFuture.runAsync(TtlRunnable.get(bizRunnable)).get()
```
