### ISSUE TITLE
官方maven仓库的版本没有同步

### ISSUE THREAD

**Issue by youngledo** [alibaba/transmittable-thread-local#583]
<img width="941" alt="image" src="https://github.com/alibaba/transmittable-thread-local/assets/68590897/51ccec5d-e139-4cd4-80da-211e0f7935de">
请问还能在哪里能拿到最新版本，同时同步版本到maven仓库。

**Comment by oldratlee** [comment]
@youngledo 更新了文档中 `Maven`依赖版本相关的链接到：
https://repo1.maven.org/maven2/com/alibaba/transmittable-thread-local/maven-metadata.xml

<a href="#dummy"><img src="https://github.com/alibaba/transmittable-thread-local/assets/1063891/31e6d6f1-a118-4267-a19a-0a52941b0a16" width="50%" alt="Screenshot" /></a>
