### ISSUE TITLE
ListenableFuture添加了监听回调，回调线程获取不到正确的值？

### ISSUE THREAD

**Issue by estiag** [alibaba/transmittable-thread-local#584]
当一个ListenableFuture添加了监听的时候，即使使用了TtlExecutors也没有获取到父进程的ThreadLocal
代码示例：
```java
//创建线程池，pool大小设为1以便造成线程复用
private ExecutorService ttllisteningDecorator = TtlExecutors.getTtlExecutorService(MoreExecutors.listeningDecorator(Executors.newFixedThreadPool(1)));
//Threadlocal set设置过程省略
ListenableFuture<String> submit = (ListenableFuture<String>) ttllisteningDecorator.submit(() -> {  
	//可以正常获取  
	return tl.get();  
});  
submit.addListener(()->{
	//获取到的和上面不一致  
	tl.get()
},ttlExecutorService);
```
用两个线程依次执行上面的代码，期待的结果是每个线程get到自己设置的值，但实际上，submit提交的线程获取结果没问题，但是addListener里的线程获取结果是第一个线程设置的值。

我追了一下代码，发现是主任务执行完后TransmittableThreadLocal的restore函数把ThreadLocal值恢复了，请问这个是bug吗

**Comment by oldratlee** [comment]
@estiag 你这个里的`ListenableFuture`是`guava`库的，是吧？
https://github.com/google/guava/wiki/ListenableFutureExplained#listenablefuture

一个快速的解决方法是修饰传入`addListener`方法的`Runnable`对象。

```java
//Threadlocal set设置过程省略
ListenableFuture<String> listenableFuture = ...
submit.addListener(TtlRunnable.get(() -> {
	tl.get()
}), ttlExecutorService);
```


-----


进一步排查，要了解`addListener`方法使用入参`Executor`的方式。

**Comment by estiag** [comment]
@oldratlee 是的，我用的`ListenableFuture`是`guava`库的，我试了一下传入修饰后的`Runnable listener`是可以正常工作的。
谢谢解答

**Comment by oldratlee** [comment]
> 我试了一下传入修饰后的`Runnable listener`是可以正常工作的。

@estiag 好的。这个 issue 先 close 了。
