### ISSUE TITLE
配合线程池使用时，remove了之后，下一个任务还是能拿到上一个任务设置的值

### ISSUE THREAD

**Issue by ChidoriZZ** [alibaba/transmittable-thread-local#585]
AbstractMsgJob
<img width="999" alt="image" src="https://github.com/alibaba/transmittable-thread-local/assets/49048553/494f95ed-3dfd-4b48-969b-5c9b6b1d97f1">
ThirdThreadLocalCacheUtil
<img width="1095" alt="image" src="https://github.com/alibaba/transmittable-thread-local/assets/49048553/540d6105-76a0-4936-b504-506e47f4b61a">

这两个任务都继承自这个抽象方法，并且使用同一个线程池。我在任务开始前后都进行了remove。这两个任务是串行执行的，第二个任务还是能拿到第一个任务的参数。能帮忙看看是哪里有问题么

**Comment by oldratlee** [comment]
@ChidoriZZ 

请提供一个 极简、可运行、复现问题的 代码Demo工程。

推荐提供成一个单独的工程（Github repo）。这样可以：

- 方便大家能排查分析（只提供片段代码、运行结果，排查信息不足）
- 方便分离不相关的业务实现内容，以及排除可能的业务使用问题
  如使用配置问题、其它业务代码的意外影响
