### ISSUE TITLE
在Java21的虚拟线程中使用这个会有问题吗？

### ISSUE THREAD

**Issue by bigbaldy1128** [alibaba/transmittable-thread-local#599]
如题，不知道这个TransmittableThreadLocal在虚拟线程中使用会不会出问题，我自己测试了各种场景目前都没问题，但是还是有点担心。而且我发现我不用TtlExecutors.getTtlExecutorService去包装ExecutorService，使用起来也是好的，这个是否正常，希望有大佬能解答！

**Comment by oldratlee** [comment]
> ...使用起来也是好的，...

@bigbaldy1128 做好测试与分析。如果你确定不用是OK的则不要用。

----

虚拟线程的设计实现是期望和线程是一样的。（有的细节差异，可以自己调研了解这方面）

即线程池中，因为创建/复用线程带来的问题，虚拟线程也一样存在。
具体可以查看了解`TTL`的资料，如要解决的问题、设计与实现机制。@bigbaldy1128
