### ISSUE TITLE
TtlRunnable是否可以支持PriorityQueue和DelayQueue

### ISSUE THREAD

**Issue by simonHome** [alibaba/transmittable-thread-local#605]
`TtlRunnable`是否可以支持`PriorityQueue`和`DelayQueue`的`Comparable task`接口？

举个例子：

线程池使用`PriorityQueue`队列，然后`execute(new PriorityTask())`。

如果这个时候插桩是在`execute`时，`PriorityTask`将包装成`TtlRunnable`后`offer`到队列中基于`PriorityQueue`底层的`Compare`机制会将`Runnable`强转成`Comparable`接口进而出现异常。

是否有考虑过支持这种场景？

```java
public static class PriorityTask implements Runnable, Comparable<PriorityTask> {
    private final int order;
    public PriorityTask(int order) {
        this.order = order;
    }

    @Override
    public int compareTo(PriorityTask o) {
        return Integer.compare(this.order, o.order);
    }

    @Overrid
    public void run() {
        System.out.println("测试执行" + order);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
        }
    }
}
```

**Comment by oldratlee** [comment]
@simonHome  

- [`TTL v2.12.3`](https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.3)已支持了`PriorityQueue`。（[`v2.12.5`](https://github.com/alibaba/transmittable-thread-local/releases/tag/v2.12.5)有相关的Bug Fix）
  - <a href="#dummy"><img src="https://github.com/alibaba/transmittable-thread-local/assets/1063891/a72ccfeb-d163-414b-8bb2-9424d5c96eda" width="50%" /></a>

- `DelayQueue`还没有做过支持。

**Comment by oldratlee** [comment]
@simonHome issue 先 close 了，有问题可以继续讨论～
