### ISSUE TITLE
TTL是否支持调用中包含多种协议场景情况下的上下文传递

### ISSUE THREAD

**Issue by xucw** [alibaba/transmittable-thread-local#626]
在微服务架构中，假如有这的链路：网关->A->B->C->D->E。其中，网关到A服务是http调用，A服务到B服务是通过RocketMQ协议，即A是生产者，B是消费者。B服务到C服务是http调用，C服务到D服务也是通过RocketMQ协议，即C是生产者，D是消费者。D服务到E服务是http调用。
TTL在类似这种场景下，从网关传递的上下文是否支持全链路传递？

**Comment by oldratlee** [comment]
你提到「从网关传递的上下文是否支持全链路传递」是 分布式追踪方案/领域所关注与解决的问题，很重要。 👍 ♥️

分布式追踪，业界已经有很多很好的实现。下文有一些介绍：

- [分布式服务调用链路追踪——方案选型](https://www.cnblogs.com/caoweixiong/p/14475815.html)

分布式追踪关注的内容 应该比`TTL`复杂得多大得多；实现上可以使用到`TTL`，下文有些介绍：

- [自实现分布式链路追踪 方案&实践](https://juejin.cn/post/7205777393453891644)

对于`TTL`的使用场景，分布式追踪（涉及各个 设施/中间件集成 相比其它场景 大家也聊得比较多。

其它的`TTL`使用场景（如DB的事务管理，看起来在场景上和分布式追踪关联很远），下面的issue中有一些说明：

- #123

------------

> TTL在类似这种场景下，从网关传递的上下文是否支持全链路传递？

回到你提的问题上：

`TTL`功能/职责/定位 只是 简单的`ThreadLocal`库，不会扩展到（成熟繁荣的）「分布式追踪」上。

> a missing Java std lib(simple & 0-dependency) for framework/middleware, provide an enhanced InheritableThreadLocal that transmits values between threads even using thread pooling components.

关于（`TTL`）的职责/分工，在下面这个Issue中也有一些讨论与说明：

- #509
