### ISSUE TITLE
请问下，在spring boot 场景下，filter 中进入时set ，但是业务中异步线程还未执行完，filter 请求已经finally remove了，这时获取到的值为null， 这种情况如何保证正确性

### ISSUE THREAD

**Issue by freshgeek** [alibaba/transmittable-thread-local#641]
请问下，在spring boot 场景下，filter 中进入时set ，但是业务中异步线程还未执行完，filter 请求已经finally remove了，这时获取到的值为null， 这种情况如何保证正确性

**Comment by oldratlee** [comment]
`TTL`本身，主线程的操作（filter请求的remove）不会影响 子线程任务（在运行完成前）传递的值。

一般是因为使用共享的Map，所以子线程可见：


- [ThreadLocal变量变成线程共享了？难道是TransmittableThreadLocal的bug？](https://juejin.cn/post/6859012589792428046)


解决方法，可以看看

- https://github.com/alibaba/transmittable-thread-local/issues/383#issuecomment-1139382259

**Comment by freshgeek** [comment]
https://juejin.cn/post/7311500203432575026

**Comment by oldratlee** [comment]
> TransmittableThreadLocal数据丢失问题 https://juejin.cn/post/7311500203432575026


```java
executor.setTaskDecorator(runnable -> TtlRunnable.get(runnable, true));

// 改成

executor.setTaskDecorator(TtlRunnable::get);

// 以避免任务不能（可能的）再次运行
```
