### ISSUE TITLE
是否支持下module-info.java模块权限

### ISSUE THREAD

**Issue by mingyang66** [alibaba/transmittable-thread-local#667]
是否支持下module-info.java模块权限 @oldratlee

**Comment by oldratlee** [comment]
不知道会不会影响`Java Agent`使用方式，一直还没加。

**Comment by mingyang66** [comment]
> 不知道会不会影响`Java Agent`使用方式，一直还没加。 @mingyang66

应该不会吧，可以修改一版验证下

**Comment by mingyang66** [comment]
```
[WARNING] *************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [transmittable-thread-local-2.14.5.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] *************************************************************************************************************************************************************
```
每次打包编译都会有这种警告，看着很不舒服

**Comment by oldratlee** [comment]
> ```
> [WARNING] *************************************************************************************************************************************************************
> [WARNING] * Required filename-based automodules detected: [transmittable-thread-local-2.14.5.jar]. Please don't publish this project to a public artifact repository! *
> [WARNING] *************************************************************************************************************************************************************
> ```
> 
> 每次打包编译都会有这种警告，看着很不舒服

收到，懂 😄

**Comment by mingyang66** [comment]
可以的，你发布Alpha版本的包吗
