### ISSUE TITLE
backupAndSet和restore里面对于holder的迭代操作

### ISSUE THREAD

**Issue by edwinmin** [alibaba/transmittable-thread-local#67]
请问`Transmittablethreadlocal` 中`backupAndSet`和`restore`方法对`holder`的迭代操作的主要目的是什么

**Comment by oldratlee** [comment]
就着代码加上注释来解释吧

```java
// backupAndSet是在执行任务（Runnable/Callable）的时候
// 1. 本线程当前的Transmittablethreadlocal值备份起来
// 2. Transmittablethreadlocal值设置成从任务提交线程传过来的值（copied）
static Map<TransmittableThreadLocal<?>, Object> backupAndSet(Map<TransmittableThreadLocal<?>, Object> copied) {
    Map<TransmittableThreadLocal<?>, Object> backup = new HashMap<TransmittableThreadLocal<?>, Object>();

    for (Iterator<? extends Map.Entry<TransmittableThreadLocal<?>, ?>> iterator = holder.get().entrySet().iterator();
         iterator.hasNext(); ) {
        Map.Entry<TransmittableThreadLocal<?>, ?> next = iterator.next();
        TransmittableThreadLocal<?> threadLocal = next.getKey();

        // 备份
        backup.put(threadLocal, threadLocal.get());

        // 如果传递过来值不包含这个ThreadLocal值，就清理掉
        // 免得调用在执行任务时，有copied中不包含的多余的值
        if (!copied.containsKey(threadLocal)) {
            iterator.remove();
            threadLocal.superRemove();
        }
    }

    // 设置成copied的值
    for (Map.Entry<TransmittableThreadLocal<?>, Object> entry : copied.entrySet()) {
        @SuppressWarnings("unchecked")
        TransmittableThreadLocal<Object> threadLocal = (TransmittableThreadLocal<Object>) entry.getKey();
        threadLocal.set(entry.getValue());
    }

    // call beforeExecute callback
    doExecuteCallback(true);

    return backup;
}
```

**Comment by edwinmin** [comment]
多谢@oldratlee的解答
task线程即使设置ThreadLocal: B C 也是在backAndSet后执行，下面是TtlRunnable中的代码
Map< TransmittableThreadLocal <?>, Object> backup = TransmittableThreadLocal.backupAndSet(copied);
        try {
            runnable.run();
        } finally {
            TransmittableThreadLocal.restore(backup);
        }
backAndSet中holder.get()是肯定取不到的，也就是说只要在子线程中执行backAndSet里面的holder.get()都是拿不到值的，理论上这段迭代复制操作在新的子线程中运行时是执行不到的，这里这么写是为了线程池中线程复用的情况吗？
另外TransmittableThreadLocal继承自InheritableThreadLocal，不需要设置copied值也能在子线程中get到，这里的设置copied的值是为了在holder中写入吗？

**Comment by oldratlee** [comment]
>  这里这么写是为了线程池中线程复用的情况吗？

是的。`backAndSet` 和 `store` 是保证 运行时任务是copied ThreadLocal的值，运行完成后，执行任务的线程的ThreadLocal值不变。

> 另外TransmittableThreadLocal继承自InheritableThreadLocal，不需要设置copied值也能在子线程中get到，这里的设置copied的值是为了在holder中写入吗？

对于使用线程池的场景，提交任务和运行任务的线程之间没有父子线程关系，所以需要主动copy，保证功能是正确的。
