### ISSUE TITLE
基于什么license啊？

### ISSUE THREAD

**Issue by YoleYu** [alibaba/transmittable-thread-local#72]
想copy了在公司用，不敢用。求个宽泛的license，懒的动手写了 — —

**Comment by oldratlee** [comment]
@YoleYu Apache 2的license已经很宽了。

另外，推荐直接依赖，一是管理简单，二是方便升级。

问一下，有什么问题影响你直接使用了吗？ 😄

**Comment by YoleYu** [comment]
有这个需求（thread pool 里面缓存的thread传值的问题），本来想自己写，然后搜到这个项目了。
还没有开始用，所以没有问题和建议。
