### ISSUE TITLE
【用户反馈收集】说一下您的使用场景、使用项目、公司，感谢！

### ISSUE THREAD

**Issue by oldratlee** [alibaba/transmittable-thread-local#73]
说一下您的公司、使用场景、使用项目、开始使用时间、使用方式等信息
\# 如有敏感的信息，说个大概就好了

1. 方便大家了解项目实际使用的情况
2. 方便给大家反馈和支持

谢谢！

**Comment by wuwen5** [comment]
公司:[欧飞网](http://www.ofpay.com)
项目: 所有java项目
使用场景: logback日志uuid跟踪，支持跨线程池的uuid传递.
开始使用时间: 2015年

使用方式: [logback-mdc-ttl](https://github.com/ofpay/logback-mdc-ttl)

dubbo接口通过```filter```在```RpcContext```中传递,http接口在请求头中统一传递和接收.

**Comment by Qsimple** [comment]
最新的Logback1.2.3似乎不支持MDC线程继承了，贵公司现在是怎样的日志追踪方案

**Comment by oldratlee** [comment]
@Qsimple 这个问题开一个专门的Issue吧。 方便  @wuwen5 看看，大家跟进。

**Comment by yinjihuan** [comment]
我想问下能不能只改造InheritableThreadLocal就能解决这个传值的问题，我现在在Spring Cloud Zuul中使用的是InheritableThreadLocal。然后就发现线程复用的时候会出问题，如果按照目前的实现方式，我估计要对zuul中的线程进行处理，这样太麻烦了

**Comment by wuwen5** [comment]
@yinjihuan 你看下本项目首页介绍 
>使用类```TransmittableThreadLocal```来保存值，并跨线程池传递。
>```TransmittableThreadLocal```继承```InheritableThreadLocal```，使用方式也类似。

你的应用场景只需要将```InheritableThreadLocal```替换为```TransmittableThreadLocal```就好了，详细请见首页。

**Comment by duguyixiaono1** [comment]
公司 | 北京猫眼文化传媒有限公司
-- | --
项目 | 新业务
使用场景 | 日志中心、调用链
开始使用时间 | 2017年
使用方式 | agent+log4j2-mdc-ttl

非常赞的项目

**Comment by jinwandalaohu** [comment]
<table>
<tr><td>公司</td><td></td></tr>
<tr><td>使用场景</td><td>日志中心分类logId</td></tr>
</table>

**Comment by xwshiustc** [comment]
公司 |德邦
-- | --
项目 | 生产环境全链路压测项目
使用场景 | 线程中压测标的传递
开始使用时间 | 2017年


在生产环境全链路压测项目中，用于解决压测标的线程间传递问题。

理论上TransmittableThreadLocal 的原理为在线程启动时利用Map<Transmittable, Object>的数据结构从上一个“父”线程copy**引用**进入”子”线程进行工作，并在“子”线程结束工作使把其TransmittableThreadLocal里面的值还原为初始状态。（一般在使用线程池，并且使用完毕后如果threadlocal不去显式得remove时还原功能有作用），同时我们注意到 TransmittableThreadLocal 复制的是 **引用** ！ 但是根据性能压测的场景判断，即父线程在一旦结束时，其压测标记需要显式remove的情况下，子线程的压测标记不可被改变，所以压测场景中，技术上可能是要进行**值**复制。  为此我们在不覆盖TransmittableThreadLocal的任何方法的情况下，在TransmittableThreadLocal直接放入一个简单的 string天生只能值传递 解决该问题。（另外，在APM工具中 因为span id的递增，这时候需要放入一个对象进行引用传递）

在用户不覆盖java.util.concurrent.ThreadPoolExecutor，java.util.concurrent.ScheduledThreadPoolExecutor 等基本类的情况下（事实上业务代码几乎不覆盖这些类），目前仅发现了容器类org.jboss.threads.JBossThread没有覆盖该方法，但是由于其是从容器出发的第一个线程，在调用结束的时候我们会显式地remove TransmittableThreadLocal里面的值，所以没有影响。

**Comment by Ronustine** [comment]
项目|验收系统
------------ | -------------
时间|2018-9
使用场景|当前登录者存在ThreadLocal中，启动线程池执行任务，任务中一系列操作需记录操作人

**Comment by linxiaobai** [comment]
公司 | 国内某互联网金融公司
-- | --
项目 | 某BU中间件链路透传Tracer
使用场景 |  通过ttl的跨线程透传上下文信息的能力
开始使用时间 | 2021年
使用方式 | 见下面代码，wrap一层ExecutorService


```java
 public static ExecutorService createTracerExecutorService(ExecutorService executorService) {
        return TtlExecutors.getTtlExecutorService(executorService);
    }
```
