### ISSUE TITLE
支持 jdk1.7  ForkJoinPool 和   jdk1.8 parallel stream 

### ISSUE THREAD

**Issue by heroboy0923** [alibaba/transmittable-thread-local#74]
分布式场景下，需要全链路传递一些参数（`trace`信息等）,普通的线程池已经支持了，是否可以考虑 支持`jdk 1.7`  `ForkJoinPool`和`jdk1.8` `parallel stream`等新特性

--------------

（Added by @oldratlee ）

subtasks:

- [x]  #76 support ForkJoinPool of jdk 7 
- [x] #77  support parallel stream of jdk 8 
- [x]  Update Javadoc link to jdk 8, see f0441779082eff534b9b0013932979b32fec7d8a
- [x] Use jdk 8 build javadoc(more pretty javadoc). release 2.2.0 use jdk 8 build javadoc.

**Comment by oldratlee** [comment]
👍 

很自然的需求，要支持！

**Comment by oldratlee** [comment]
Task 

- [ ]  #76 
- [ ] #77 
- [ ]  Update Javadoc link to jdk 8
- [ ] use jdk 8 build javadoc
