### ISSUE TITLE
好像不支持Slf4j的MDC？

### ISSUE THREAD

**Issue by kaybinwong** [alibaba/transmittable-thread-local#78]
我们使用logback+slf4j收集日志，但是目前2.1.0版本不支持向MDC传递数据？

**Comment by wuwen5** [comment]
仅供参考，我们生产上是这么整合使用的。https://github.com/ofpay/logback-mdc-ttl

**Comment by oldratlee** [comment]
https://github.com/oldratlee/log4j2-ttl-thread-context-map

这个是log4j 2.6.2 的  集成

**Comment by oldratlee** [comment]
@kaybinwong `TTL`提供的是`ThreadLocal`的传递，和日志`MDC` 是要从日志来 **_集成_** `TTL`的。

即 从职责或是系统依赖上来说，日志 依赖 `TTL`，不是反过来。

**Comment by wuwen5** [comment]
```slf4j```没想好怎么去集成， 未发布版的```slf4j-1.8.0```版本支持```spi```的方式加载```logger```实现。

但是没想好怎么去替换```MDCAdapter```实现中的```context```，我的想法是需要保留日志框架自己的```MDCAdapter```实现方式的基础上去解决```context```的问题.

**Comment by shipengyan** [comment]
简单的验证了下 slf4j+logback的mdc，在多线程下是可以用的，

[https://github.com/ofpay/logback-mdc-ttl/issues/1](https://github.com/ofpay/logback-mdc-ttl/issues/1)

**Comment by oldratlee** [comment]
@shipengyan COOL~

我把 https://github.com/ofpay/logback-mdc-ttl 加到这个项目的文档中，方便大家了解&使用。
 @wuwen5  @shipengyan

**Comment by oldratlee** [comment]
已经 加到 https://github.com/alibaba/transmittable-thread-local/blob/master/docs/requirement-scenario.md 上了。

![image](https://user-images.githubusercontent.com/1063891/28701861-b6274888-738b-11e7-82ed-0bdac0ed1a60.png)
