### ISSUE TITLE
最新的Logback1.2.3似乎不支持MDC线程继承了，现在要怎样的日志追踪方案

### ISSUE THREAD

**Issue by oldratlee** [alibaba/transmittable-thread-local#81]
最新的Logback1.2.3似乎不支持MDC线程继承了，贵公司现在是怎样的日志追踪方案 @wuwen5  
(Question From @Qsimple see https://github.com/alibaba/transmittable-thread-local/issues/73#issuecomment-329192927 )

**Comment by oldratlee** [comment]
@wuwen5 的[logback-mdc-ttl](https://github.com/ofpay/logback-mdc-ttl)  做的logback的集成。

@wuwen5 可以帮忙看看 :)

**Comment by wuwen5** [comment]
> logback从1.1.5版本之后，新的commit将MDC内部维护的InheritThreadLocal修改成了ThreadLocal

```logback-mdc-ttl```本身就是使用```TransmittableThreadLocal ```替换了原来的```*ThreadLocal```实现。 和Logback这次版本的修改没有关系， 我们是通过```logback-mdc-ttl```整合[transmittable-thread-local](https://github.com/alibaba/transmittable-thread-local/)解决的
之前我在https://github.com/ofpay/logback-mdc-ttl/issues/1 的回复中也提到过.

**Comment by oldratlee** [comment]
@wuwen5 多谢解答！

ps： 是否有兴趣成为项目的维护者？ 😸 

可以来搞一下 #77 #76 ，自己一直没把这2个feature 做了 😖

**Comment by wuwen5** [comment]
@oldratlee 这两个feature 我不确定是否是重复的？java8的parallel stream 本身就是使用的共享```ForkJoinPool```

有兴趣参与和维护，很希望能为开源做点事情:blush: 这个feature我再研究研究。

**Comment by oldratlee** [comment]
好，期待啊
