### ISSUE TITLE
clean extra TTL value in destination thread

### ISSUE THREAD

**Issue by tianjialin** [alibaba/transmittable-thread-local#90]
您好，请教一个问题：

在TransmittableThreadLocal类中的 backupAndSet() 方法中，如下代码：
```
for (Iterator<? extends Map.Entry<TransmittableThreadLocal<?>, ?>> iterator = holder.get().entrySet().iterator();
             iterator.hasNext(); ) {
    Map.Entry<TransmittableThreadLocal<?>, ?> next = iterator.next();
    TransmittableThreadLocal<?> threadLocal = next.getKey();

    // 此处将线程池所在线程threadlocal备份
    backup.put(threadLocal, threadLocal.get());

    // 没太理解此处，为何将copied中不存在，holder中存在的 threadlocal remove？
    if (!copied.containsKey(threadLocal)) {
        iterator.remove();
        threadLocal.superRemove();
    }
}
```
一旦调用iterator.remove()本来不属于当前线程的threadlocal也会被remove，这样假如此时另外一个线程池中的线程调用了copy()方法，就会丢失部分数据？
不知我哪里理解错误，望批评指正。
期待回复

**此Issue为提交错误地址后粘贴过来的，可直接查看原文**
https://github.com/oldratlee/translations/issues/51#issuecomment-381977782

**Comment by tianjialin** [comment]
问题的原因是没注意到holder的几点需要注意的地方：
1、holder 是 InheritableThreadLocal 变量；
2、holder 是 static 变量；
3、value 是 WeakHashMap；
4、深刻理解 ThreadLocal 工作原理；

**Comment by oldratlee** [comment]
> 这样假如此时  **_另外一个线程池中的线程_** 调用了`copy()`方法

`holder.get()`是`ThreadLocal`的（`holder`本身是`ThreadLocal`），只属于当前线程。
\# `ThreadLocal#get()` **_只能_** 拿到 **_当前线程_** 的数据。

即这个数据不会被另一个线程访问使用的，没有并发问题。

更具体 可以再看看一下`ThreadLocal`的使用与限制。

------------------

> // 没太理解此处，为何将copied中不存在，holder中存在的 threadlocal remove？

```java
// clear the TTL value only in copied
// avoid extra TTL value in copied, when run task.
if (!copied.containsKey(threadLocal)) {
    iterator.remove();
    threadLocal.superRemove();
}
```

上面的代码注释 说明了。

如果不这么做这个删除，那么 `TTL`这些值 就比 `copied`  里多出来了，
不没有正确 恢复/回放值。

比如 原来的`copy`过来的值是 `a=1,b=2`，回放运行的线程原来就有值`z=100`。
不做这个删除，回放运行时，就有值`a=1,b=2,z=100`，不预期了。

可以自己写段代码运行Debug一下就好了，或者 自己理解一下`TTL`的执行过程，这个就很容易理解了。

---------

**此Issue为提交错误地址后粘贴过来的，可直接查看原文**
https://github.com/oldratlee/translations/issues/51#issuecomment-381935603
