### ISSUE TITLE
通过线程池继承threadlocal的问题

### ISSUE THREAD

**Issue by lailailai1209** [alibaba/transmittable-thread-local#91]
您好，请问您有没有不要侵入源代码的方法，agent方式也不行的， 有可能么

**Comment by oldratlee** [comment]
说明出 

- 你的需求/场景
- 这样做法的痛点

@lailailai1209 

因为

1. 你的推导思路 可能可以 改变， 这样 结论就可以变了。
2. 能从你的说明，引导出解决

**Comment by lailailai1209** [comment]
现在在做一个类似于google dapper的tracer系统，就是把context放入threadlocal传播，在线程池就遇到了问题，子线程没有父线程的threadlocalmap，最好不改任何被监控系统的代码，我看您用agent的形式可以做到0侵入，但是要加上jdk运行参数，所以想问问能不能直接把这个threadlocalmap传递给子线程

**Comment by oldratlee** [comment]
> 现在在做一个类似于google dapper的tracer系统，就是把context放入threadlocal传播，在线程池就遇到了问题，子线程没有父线程的threadlocalmap，

这是个 TTL解决的典型需求。

> 最好不改任何被监控系统的代码，我看您用agent的形式可以做到0侵入，但是要加上jdk运行参数，所以想问问能不能直接把这个threadlocalmap传递给子线程

没有找到这样的解法。

虽然不能给出形式的化的证明。但是 现在JDK的ThreadLocal的实现，不做任何设置，肯定不能有现在JDK没有能力，要不JDK出Bug了，是吧。

即使JDK自带了这个功能，也是要用 JVM参数来开启的，要不也是Bug了。

你觉得呢？

**Comment by lailailai1209** [comment]
恩 您说的我明白，直接去做0侵入的实现threadlocalmap传递到子线程，现在的jdk肯定不行，我在想有没有什么其他的办法，能间接的实现这个想法，

**Comment by oldratlee** [comment]
> 我在想有没有什么其他的办法，能间接的实现这个想法

期待 提供 思路或解法～  ❤️
