### ISSUE TITLE
是否有内存泄露的风险?

### ISSUE THREAD

**Issue by candyleer** [alibaba/transmittable-thread-local#96]
这种继承的`Threadlocal`，如果嵌入层次比较深，最后没有调用 `remove()` 方法，是否会引起内存泄露?

**Comment by oldratlee** [comment]
在内存持有的问题上，`TransmittableThreadLocal` 和 `ThreadLocal` 是一样的，本身是没有问题的。在业务使用上，了解/理解一下使用上的注意。

具体的确定，你可以： @candyleer 

1. 理解 `TransmittableThreadLocal` 和 `ThreadLocal` 的使用方式、过程 和 内存持有的实现。
2.  `TransmittableThreadLocal`有内存泄露的测试Case。你可以自己来直接运行验证一下
https://github.com/alibaba/transmittable-thread-local/blob/master/docs/performance-test.md#-%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F

![image](https://user-images.githubusercontent.com/1063891/42300426-073e1c00-8043-11e8-97ab-4d1b732cbb17.png)

**Comment by candyleer** [comment]
感谢回答

**Comment by oldratlee** [comment]
好的 ❤️ Close
